### ISSUE TITLE
20/06/16 - Repetir até encaixar - Renan Nery

### ISSUE THREAD

**Issue by renannery** [androiddevbr/agenda-medium#10]
* **Autor:** Renan Nery
* **Data escolhida:** 27/06/16
* **Título do artigo:** Repetir até encaixar
* **Descrição:** Uma abordagem diferente para desenhar repetidamente uma imagem sem utilizar o _tileMode="repeat"._

* **Link da publicação:** https://medium.com/@renannery/repetir-at%C3%A9-encaixar-390ade3f57bd#.7f769yti8

**Comment by davidtcdeveloper** [comment]
@renannery Adicionei à agenda. Mas o link para o post que está na issue dá 404 :disappointed:

**Comment by renannery** [comment]
@davidtcdeveloper atualizei o link, você poderia dar uma olhada se está funcionando agora?

vlw!

**Comment by walmyrcarvalho** [comment]
@renannery Caraca, excelente o artigo Renan! Curti muito a solução, aquela dica que eu dei ajudou em alguma coisa? hahaha

**Comment by walmyrcarvalho** [comment]
@renannery Ah, cê acha que esse tema é intermediário ou avançado? Só pra gente colocar umas tags aqui. :)

**Comment by renannery** [comment]
Eae @walmyrcarvalho tudo ajuda!  O Rodrigo Sicarelli também ajudou com a ideia do tileMode. Mas é isso ai, vamos fortalecendo a comunidade.

E eu acho que é hummmm sei la intermediário? não acho tão avançado.

**Comment by walmyrcarvalho** [comment]
@renannery Beleza, vou colocar como intermediário!

**Comment by davidtcdeveloper** [comment]
@renannery Excelente texto!
Te adicionei agora como escritor da nossa publicacao. Poderia incluir o post a publicacao, para ja deixar pronto para publicar?

**Comment by renannery** [comment]
@davidtcdeveloper acabei de mandar para review

**Comment by davidtcdeveloper** [comment]
Publicação antecipada para hoje :)

**Comment by walmyrcarvalho** [comment]
Publicado! https://medium.com/android-dev-br/repetir-at%C3%A9-encaixar-390ade3f57bd#.t1cj4dgdx
