### ISSUE TITLE
Android UI: Bottom App Bar

### ISSUE THREAD

**Issue by itscorey** [androiddevbr/agenda-medium#100]
* **Autor:** Lucas Cavalcante
* **Perfil no medium:** medium.com/@luke8.co
* **Data escolhida:** XX/06/19 (quando for possível)
* **Título do artigo:** Android UI: Bottom App Bar
* **Descrição:** Nesse artigo eu falo bastante sobre o componente Bottom App Bar, como implementar e assim vai...

Link: [Android UI: Bottom App Bar](https://medium.com/@luke8.co/android-ui-bottom-app-bar-e3630e581a2b?sk=ab68c5a0943d8260edb3e23d1977e9f5)

**Comment by orafaaraujo** [comment]
Fala @itscorey 
Parabéns pelo post, ficou completo com você disse no final. Um ótimo guia para quem quer utilizar o componente.
Deixei poucos comentários, depois que você responder já pode publicar e vamos tentar anunciar já amanhã se possivel.

Abraços

**Comment by itscorey** [comment]
Perdão pela descrição vaga (deu um pouquinho de preguiça)!

E obrigado pelos comentários, foram bastante úteis!

**Comment by orafaaraujo** [comment]
Nem esquenta, Lucas.
Obrigado mais uma vez por colaborar com a comunidade.

Abraços !
