### ISSUE TITLE
22/06/2019 - [Artigo] Code review - Tiago Dávila

### ISSUE THREAD

**Issue by TiagoDvl** [androiddevbr/agenda-medium#102]
* **Autor:** Tiago Dávila
* **Perfil no medium:** medium.com/@tdavilas
* **Título do artigo:** Revisão de código: Colaboração de ideias fazendo um time melhor.
* **Descrição:** Expor um caso de revisão de código em uma classe java (android) e demonstrando o passo a passo fácil a fim de realizá-la.
* **Link para o artigo:** https://medium.com/@tdavilas/revis%C3%A3o-de-c%C3%B3digo-7dc6a9eecb21

**Comment by orafaaraujo** [comment]
Oi, @TiagoDvl 

Parabens pelo post!
Me desculpe a demora... vamos publicar essa semana, tudo bem? :)
Abraços

**Comment by orafaaraujo** [comment]
Alias, poderia arrumar a mensagem do header? Ela está esticada :(

**Comment by orafaaraujo** [comment]
Te coloquei como Writer no nosso Medium, pode submeter!

**Comment by orafaaraujo** [comment]
Fala @TiagoDvl 
Pode subemter o post no nosso Medium?

Abraços
