### ISSUE TITLE
Android View: Prólogo

### ISSUE THREAD

**Issue by itscorey** [androiddevbr/agenda-medium#104]
* **Autor:** Lucas Cavalcante
* **Perfil no medium:** medium.com/@luke8.co
* **Título do artigo:** Android View: Prólogo
* **Descrição:** Essa artigo é o ínicio de uma série sobre View no Android. O objetivo desse é fazer uma introdução a respeito do componente e como ele está presente hoje.

**Comment by itscorey** [comment]
O artigo está disponível em: [Android View: Prólogo](https://medium.com/@luke8.co/android-view-pr%C3%B3logo-d44a89c14fd1)

**Comment by orafaaraujo** [comment]
Fala @itscorey 

Parabéns pelo post, ficou bem completo e cheio de questionamentos para amarrar quem está lendo. Ficou muito show!

Pode submeter em nosso Medium que publicamos essa semana. :)

Abraços

**Comment by orafaaraujo** [comment]
Ah, coloque um label nas imagens também, por favor. :)

**Comment by itscorey** [comment]
Obrigado, @orafaaraujo 

Adicionei as labels e submeti para o Medium!
