### ISSUE TITLE
Android View: ciclo de vida

### ISSUE THREAD

**Issue by itscorey** [androiddevbr/agenda-medium#105]
* **Autor:** Lucas Cavalcante
* **Perfil no medium:** medium.com/@luke8.co
* **Título do artigo:** Android View: ciclo de vida
* **Descrição:** Essa artigo é o segundo da série sobre View no Android, e ele já começa a ter uma introdução um pouco mais profunda a respeito da estrutura de uma View, falando de ponto como traversals, salvamento de estado e etc.

**Comment by itscorey** [comment]
Ele está disponível [aqui](https://medium.com/@luke8.co/android-view-ciclo-de-vida-2e228356d955).

**Comment by orafaaraujo** [comment]
Oi, @itscorey 

Outro post muito bom.
Só precisamos ajustar o código que está com Scroll mas está difíicil de perceber isso... acho que o melhor deixar só o código que interessa ou deixar expandido.
Por favor, também coloque descrição nas imagens/trechos de código.

Arrumando isso, pode submeter que publicamos essa semana.

Abraços.

**Comment by itscorey** [comment]
Boa! Obrigado @orafaaraujo 

Apliquei suas sugestões e submeti o artigo!
