### ISSUE TITLE
Explorando o Azure DevOps como uma alternativa de CI/CD para um aplicativo android 

### ISSUE THREAD

**Issue by victorlopesjg** [androiddevbr/agenda-medium#106]
* **Autor:** Victor Oliveira
* **Perfil no medium:** medium.com/@victorlopesjg
* **Título do artigo:** Explorando o Azure DevOps como uma alternativa de CI/CD para um aplicativo android 
* **Descrição:** Uma serie composta por dois artigos sobre o uso do Azure DevOps e o AppCenter como uma solução de CI/CD em um projeto android.

https://medium.com/@victorlopesjg/explorando-o-azure-devops-como-uma-alternativa-de-ci-cd-para-um-aplicativo-android-parte-1-d9ba1af07117?source=friends_link&sk=6144a42cfa645cc28f1f9dfb2713fbbf

https://medium.com/@victorlopesjg/explorando-o-azure-devops-como-uma-alternativa-de-ci-cd-para-um-aplicativo-android-parte-2-3cd97f9d3a63?source=friends_link&sk=16356987de4dee59e0a7e5068829db6c

**Comment by orafaaraujo** [comment]
Fala, @victorlopesjg 

Parabéns pelo post. Ficou bem legal e completo. 

Como sugestão, acho que ficaria melhor falar no começo da primeira parte porque usar o Azure DevOps e não outra ferramenta de CI/CD. Falar um pouco das vantagens, quanto custa ou se custa etc.

Feito isso, pode publicar ambos que publicamos :)

Abraços
