### ISSUE TITLE
Artigo - Introdução a Testes Unitários com JUnit e Mockito no Android

### ISSUE THREAD

**Issue by tadeumx1** [androiddevbr/agenda-medium#107]
* **Autor:** Matheus Tadeu
* **Perfil no medium:** https://medium.com/@tadeumx1
* **Título do artigo:** Introdução a Testes Unitários com JUnit e Mockito no Android
* **Descrição:** Esse artigo é uma introdução a testes unitários no Android de uma forma geral, explicando desde o conceito de teste unitário, porque testar sua aplicação, como estruturar a aplicação para isso utilizando nesse caso o MVVM e também como testar sua aplicação na prática, para isso estou apresentando testes para um aplicativo bem simples que cumpre esse objetivo

Link do artigo https://medium.com/@tadeumx1/introdução-a-testes-unitários-com-junit-e-mockito-no-android-67104232b878

Caso puderem postar o mais rápido possível, eu agradeço mas depois da revisão, claro

**Comment by tadeumx1** [comment]
@orafaaraujo Então hoje de manhã você apontou algumas coisas para eu corrigir no artigo, ele teve o tema aprovado ? E em uma das anotações você falou que já tinha um post sobre JUnit 5 você poderia me passar o link para eu também colocar lá ?

Obrigado pela atenção

**Comment by orafaaraujo** [comment]
Oi, @tadeumx1 
Me desculpe a demora.

Foi aprovado sim! Mas eu ainda não acabei a revisão... vou continuar em breve.

Abraços

**Comment by tadeumx1** [comment]
Tranquilo, obrigado @orafaaraujo qualquer coisa é só chamar

**Comment by orafaaraujo** [comment]
Oi, @tadeumx1 

Continuei avaliando o seu post e gostaria de pedir para você utilizar alguma ferramenta de correção para te ajudar com as pontuações.  Se tiver dificuldades, peça para alguém te ajudar. 

Temos uma diretriz descrita [aqui](https://github.com/androiddevbr/agenda-medium/blob/master/guideline.md) para ajudar os colaboradores do nosso Medium.

Nos avise quando finalizar.

Obrigado.

**Comment by tadeumx1** [comment]
Então @orafaaraujo terminei de corrigir todos os erros de pontuação do texto, quando tiver um tempo e puder revisar de novo

Obrigado

**Comment by tadeumx1** [comment]
Boa Tarde @orafaaraujo 

Você vai revisar ainda esse artigo ?

Obrigado pela atenção

**Comment by orafaaraujo** [comment]
Oi @tadeumx1 

Pode submeter o posto em nosso Medium?
Obrigado

**Comment by tadeumx1** [comment]
@orafaaraujo Então nesse meio tempo adicionei uma explicação mais detalhada de conceitos que estavam sendo usados no aplicativo apresentado no artigo como LiveData, Injeção de Dependência e mock de classes sendo assim estou finalizando o artigo com essas adições, e mando aqui pra você dar um olhada, acredito que daquela forma que estava por se tratar de um artigo de introdução estava superficial em alguns pontos que são importantes

**Comment by orafaaraujo** [comment]
Oi, @tadeumx1 
Seu post ficou esquecido aqui, mil perdões!

Te coloquei como writer, pode submeter :)

Abraços

**Comment by tadeumx1** [comment]
Opa @orafaaraujo beleza ?

Desculpa a demora, vou fazer uma última revisão do artigo, e já mando lá direto na página do Medium

Obrigado a oportunidade

**Comment by orafaaraujo** [comment]
Oi, @tadeumx1 

Lembre-se de verificar nossas diretrizes para subemter um post. O que notei que faltam marcar palavars em inglês ou que significam alguma coisa no contexto Android em negrito.

Também gostaria que cogitasse separar o post em 2 partes, ou remove partres que não acham necessarias para o entendimento do post (por exemplo, ele aborda tests, vale a pena mencioar layouts?). Com 13 minutos de leitura o post ficar muito grande e afasta possiveis leitores...

Abraços

**Comment by orafaaraujo** [comment]
Fala @tadeumx1 
Alguma novidade sobre este post?

Ele está quase pronto... falta pouco para publicarmos 🎉

Abraços
