### ISSUE TITLE
Generics e Variance em Kotlin (in, out, T) - Thiago Pereira

### ISSUE THREAD

**Issue by ThiFeonir** [androiddevbr/agenda-medium#108]
* **Autor:** Thiago Pereira
* **Perfil no medium:** https://medium.com/@litjc13
* **Título do artigo:** Generics e Variance em Kotlin (in, out, T)
* **Descrição:** O artigo aborda o conceito de generics e variance e sua motivação através de uma visão do Java, depois introduz como o conceito é tratado em Kotlin, e compara um pouco as duas abordagens.
* **Postagem:** https://medium.com/@litjc13/generics-e-variance-em-kotlin-in-out-t-ca5ca07c9fc5

**Comment by orafaaraujo** [comment]
Oi, @ThiFeonir 
Só passando para avisar que não esqueci do post não.
Vou revisar em breve.

Abraços

**Comment by orafaaraujo** [comment]
Oi @ThiFeonir 
Tudo bom?

Me desculpe pela demora, revisei o seu artigo e está bem legal, também não conhecia muito bem o assunto.

Só deixei alguns pequenos ajustes e como sugestão, usar Gist ao invés de printscreen no código Java pois está pequeno para ler. Ou, colocar prints com as letras maiores.

Feito isso, pode submeter em nosso Medium que já aprovo e publico.

Abraços e obrigado!

**Comment by orafaaraujo** [comment]
Olá, @ThiFeonir 
Tudo bom?

Alguma novidade sobre este post? Ele está bem legal e próximo de lançarmos. :)

Abraços

**Comment by ThiFeonir** [comment]
Fala Rafael, acabei não vendo o e-mail do comentário anterior. Fiz as mudanças que sugeriu lá no post.

**Comment by orafaaraujo** [comment]
Fala @ThiFeonir 

Te coloquei como writer, só publicar!
Abraços
