### ISSUE TITLE
Criando um chat com Firebase - Android

### ISSUE THREAD

**Issue by thiagomatheusms** [androiddevbr/agenda-medium#109]
* **Autor:** Thiago Matheus
* **Perfil no medium:** https://medium.com/@thiagomatheusms
* **Título do artigo:** Criando aplicativos com Firebase
* **Descrição:** Gostaria de falar um pouco mais sobre como criar aplicativos com Firebase. A idéia do meu artigo é demostrar na prática como integrar o Firebase a um projeto Android (Java) e utilizar alguns dos serviços oferecidos por esse poderoso Saas. O objetivo é criar uma aplicação simples onde o usuário pode logar-se via Google (Authentication) e salvar esse usuário no FireStore. A partir daí o usuário poderá interagir com qualquer outro usuário cadastrado na mesma base, enviando simples mensagens de textos em tempo real. O projeto segue o padrão de Architeture indicada pelo Google, com a utilização de Viewmodel - liveData -> Repository.

**Comment by orafaaraujo** [comment]
Olá, @thiagomatheusms 
Tudo bom?

Alguma novidade sobre este post?

Obrigado

**Comment by orafaaraujo** [comment]
Olá, @thiagomatheusms 
Vou fechar a issue, okay?

Caso retornar no assunto pode reaabrir

Abraços e obrigado
