### ISSUE TITLE
04/07/16 - React Native, por um desenvolvedor Android nativo - Walmyr Carvalho

### ISSUE THREAD

**Issue by walmyrcarvalho** [androiddevbr/agenda-medium#11]
* **Autor:** Walmyr Carvalho
* **Data escolhida:** 04/07/16
* **Título do artigo:** React Native, por um desenvolvedor Android nativo
* **Descrição:** A idéia do artigo é eu descrever a minha experiência, como desenvolvedor Android nativo, ao criar um aplicativo usando React pra Android. Vamos ver o que sai. :)

**Comment by walmyrcarvalho** [comment]
@davidtcdeveloper Só lembrando que essa semana vou terminar esse artigo pra cobrir o buraco que deixei na agenda, prometo!

**Comment by davidtcdeveloper** [comment]
Beleza, me organizarei para preparar o meu para a próxima semana.

**Comment by walmyrcarvalho** [comment]
Eu perdi a mão com esse tema e acho que vou fechar essa isso e pensar em algum outro artigo pra cobrir o spot vazio na agenda. Me organizei mal pra escrever o artigo, sorry. :(
