### ISSUE TITLE
06/10/2019 - Como lidar com erros com Retrofit e Coroutines - Douglas Iacovelli

### ISSUE THREAD

**Issue by douglasiacovelli** [androiddevbr/agenda-medium#110]
* **Autor:** Douglas Iacovelli
* **Perfil no medium:** https://medium.com/@douglas.iacovelli/
* **Título do artigo:** Como lidar com erros com Retrofit e Coroutines
* **Descrição:** Gostaria de publicar este artigo explicando como tratar os erros que acontecerem com Retrofit e Coroutines de uma forma eficiente e em um único lugar

link para o artigo: https://medium.com/@douglas.iacovelli/como-lidar-com-erros-com-retrofit-e-coroutines-7b5af3ce3ef

**Comment by orafaaraujo** [comment]
Olá, @douglasiacovelli 
Tudo bom?

Comecei a revisar o seu artigo e gostaria de te pedir por gentileza para utilizar uma linguagem impessoal, evitando "vou fazer", "eu fiz" etc. Prefira "foi feito", por exemplo.

Existe uma guideline aqui que você pode se basear.
https://github.com/androiddevbr/agenda-medium/blob/master/guideline.md

Obrigado

**Comment by douglasiacovelli** [comment]
Fala @orafaaraujo! Tudo bem e você?
Obrigado pelos toques. Arrumei o artigo para ficar impessoal e dei uma revisada pra seguir as guidelines que você mandou.

Você se importaria de olhar de novo, por favor?

**Comment by orafaaraujo** [comment]
Fala @douglasiacovelli 
Tudo bom?

Perfeito!
Pode subemter em nosso Medium?

Abraços

**Comment by douglasiacovelli** [comment]
Fala @orafaaraujo! Muito obrigado. Pode sim :)

**Comment by douglasiacovelli** [comment]
@orafaaraujo cara, no artigo não achei a opção de submeter pra publication do Android Dev BR. Como eu faço, por favor?

**Comment by douglasiacovelli** [comment]
@orafaaraujo parece que não fui adicionado na publication do androiddevbr. Não consigo enviar pra vcs

**Comment by orafaaraujo** [comment]
Oi @douglasiacovelli 

Mil desculpas, já está lá.
Só publicar :)
