### ISSUE TITLE
11/11/19 - Configurando o Firebase utilizando o Android Studio - Fernando de Jesus Grangeiro

### ISSUE THREAD

**Issue by FernandoGrangeiro** [androiddevbr/agenda-medium#111]
* **Autor:** Fernando de Jesus Grangeiro
* **Perfil no medium:** https://medium.com/@fernandojgrangeiro
* **Título do artigo:** Como configurar o Firebase utilizando o Android Studio
* **Descrição:** Gostaria de falar um pouco sobre como fazer a configuração do projeto firebase utilizando a IDE Android Studio e mostrar o quão simples é
* **Link:**  https://medium.com/@fernandojgrangeiro/como-configurar-firebase-utilizando-o-android-studio-f58aca8aef0d

**Comment by orafaaraujo** [comment]
Olá, @FernandoGrangeiro 
Tudo bom?

Comecei a revisar o seu artigo e deixei alguns comentários, a maioria sobre evitar linguagem pessoal e informal, e preferir uma linguagem mais formal e impessoal. Exemplo: "vou fazer", "eu fiz" etc. Prefira "foi feito", por exemplo.

Existe uma guideline aqui que você pode se basear.
https://github.com/androiddevbr/agenda-medium/blob/master/guideline.md

Obrigado

**Comment by FernandoGrangeiro** [comment]
Ok, vou dar uma olhada e arrumar

Em qua, 6 de nov de 2019 10:11, Rafael Araujo <notifications@github.com>
escreveu:

**Comment by FernandoGrangeiro** [comment]
Texto corrigido.

**Comment by FernandoGrangeiro** [comment]
@orafaaraujo  Texto corrigido

**Comment by FernandoGrangeiro** [comment]
Oi @orafaaraujo, tudo bem ? Tem alguma previsão de quando o artigo será lançado ?

**Comment by orafaaraujo** [comment]
Oi, @FernandoGrangeiro 
Tudo bom?

Acabei de reler, ficou bem legal!
Só gostaria de pedir para colocar as palavras em inglês, principalmente as não usuais como Cloud Message, Gradle, etc em itálico.

Feito isso, pode submeter em nosso post.
Abraços

**Comment by FernandoGrangeiro** [comment]
Oi @orafaaraujo, tudo bem? Obrigado pelo feedback, fiz todas as alterações, eu submeto para vcs ou vcs fazem? Não entendi bem essa parte

**Comment by FernandoGrangeiro** [comment]
Oi @orafaaraujo, tudo bem ? Algum posicionamento em relação a publicação do artigo?

**Comment by orafaaraujo** [comment]
OI, @FernandoGrangeiro 

Me desculpa pela demora.
Te coloquei como writer no nosso Medium e agora você já pode submeter.
Só gostaria de te pedir por gentileza de colocar as palavras chave em itálico como deixei nos comentários do Medium.

Obrigado.

**Comment by FernandoGrangeiro** [comment]
oi, @orafaaraujo obrigado pelo retorno, acabei de submeter com os ajustes das palavras em itálico

**Comment by orafaaraujo** [comment]
Publicado!
Vou aguardar outros posts para anunciar.
Muito obrigado!
