### ISSUE TITLE
Clean Architecture e MVVM em Android

### ISSUE THREAD

**Issue by bmattoso** [androiddevbr/agenda-medium#112]
* **Autor:** Bruno Mattoso Gonçalves
* **Expectativa de publicação:** espero que até dia 23/12/2019 esteja ok.
* **Perfil no medium:** medium.com/@brunomattoso
* **Título do artigo:** Clean Architecture e MVVM em Android
* **Descrição:** Gostaria de falar um pouco mais sobre como estruturar um app seguindo as guidelines do clean architecture(Já existe um post no medium com este conteúdo, porém gostaria de aprofundar mais nos códigos e estrutura do app). Gostaria de abordar também sobre alguns conceitos do SOLID (Tema que também já temos um post no medium) para firmar ainda mais o benefício dessa abordagem. A ideia é  mostrar em um projeto como podemos aplicar o mvvm, clean architeture e outras implementações que nos ajudam a produzir um código mais limpo (Modularização, Injeção de dependências, testes e CI).

Vou entender se acreditarem que os posts que temos são o suficiente para a comunidade. (:

**Comment by orafaaraujo** [comment]
Oi, @bmattoso 

Tudo bem se já temos outros posts com o mesmo tema, pode submeter. 

Abraços

**Comment by orafaaraujo** [comment]
Olá, @bmattoso 
Alguma novidade?
Se não podemos fechar essa issue e abrir novamente no futuro.

Abraços
