### ISSUE TITLE
CI/CD utilizando Circle CI

### ISSUE THREAD

**Issue by FernandoGrangeiro** [androiddevbr/agenda-medium#113]
* **Autor:** Fernando de Jesus Grangeiro
* **Perfil no medium:** https://medium.com/@fernandojgrangeiro
* **Título do artigo:** CI/CD utilizando o Circle CI e Fastlane para projetos Android
* **Descrição:** Gostaria de demonstrar  como fazer um CI/CD utilizando o Circle CI e Fastlane para projetos Android enviando para a PlayStore um Android App Bundle

Link da primeira parte: https://medium.com/@fernandojgrangeiro/ci-cd-utilizando-fastlane-e-circle-ci-parte-1-e339f3cf833a

**Comment by FernandoGrangeiro** [comment]
@orafaaraujo  tudo bem?  Posso dividir esse artigo em duas partes ? Percebi que ele está ficando muito extenso

**Comment by FernandoGrangeiro** [comment]
Link da primeiro parte https://medium.com/@fernandojgrangeiro/ci-cd-utilizando-fastlane-e-circle-ci-parte-1-e339f3cf833a

**Comment by orafaaraujo** [comment]
Fala, @FernandoGrangeiro 

Tudo bom?
Me desculpe a demora... revisie o post e deixei pequenos comentários. Pode dar uma olhada?
Após isso, pode submeter em nosso médium

Obrigado

**Comment by FernandoGrangeiro** [comment]
Oi @orafaaraujo, tudo bem ? 
Vou fazer os ajustes e  subir uma nova versão esse fds

**Comment by orafaaraujo** [comment]
Oi, @FernandoGrangeiro 

Chegou a fazer as alterações?

Abraços

**Comment by FernandoGrangeiro** [comment]
@orafaaraujo oi, tudo bem? Subi as alterações

**Comment by orafaaraujo** [comment]
Oi, @FernandoGrangeiro 

O post ficou bem legal. Achei muito bom explicar o que significa cada ferramenta (CI, Fastlane etc). Bora publicar?

Submete em nosso Medium quando puder.

Abraços

**Comment by orafaaraujo** [comment]
Muuuito obrigado novamente, @FernandoGrangeiro
