### ISSUE TITLE
Lições aprendidas com um aplicativo pessoal

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#114]
* **Autor:** Igor Escodro
* **Perfil no medium:** medium.com/@escodro
* **Título do artigo:** Lições aprendidas com um aplicativo pessoal
* **Descrição:** Gostaria de compartilhar algumas lições aprendidas nesses últimos anos desenvolvendo meu aplicativo pessoal. Neste artigo dou algumas dicas de técnicas, bibliotecas e tento encorajar os desenvolvedores a criar apps pessoais para aprendizado constante. Este artigo já foi publicado em inglês no Medium ProAndroidDev. [[link]](https://proandroiddev.com/lessons-learned-with-personal-application-97eab3cb094b)

**Comment by orafaaraujo** [comment]
Manda bala :)

**Comment by igorescodro** [comment]
Obrigado!

Enviada para publicação no AndroidDevBR.

**Comment by igorescodro** [comment]
Link do artigo traduzido:
https://medium.com/@escodro/licoes-aprendidas-com-um-aplicativo-pessoal-84ce53944970

**Comment by orafaaraujo** [comment]
Oi, @igorescodro 

Post revisado com 2 pequenos comentários apenas.
Pode arrumar e subemter?

Obrigado.
