### ISSUE TITLE
31/01/2020 - Entendendo e utilizando R8/Proguard 

### ISSUE THREAD

**Issue by Levi-Moreira** [androiddevbr/agenda-medium#115]
* **Autor:** Levi Albuquerque
* **Perfil no medium:** medium.com/@levi.m.albuquerque
* **Título do artigo:** Entendendo e utilizando R8/Proguard 
* **Descrição:** Neste post falarei um pouco sobre o que é R8/Proguard destacando as diferenças entre os dois, como funcionam e finalmente como aplicá-los aos seus projetos para otimizar e obfuscar o código de produção.

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 

Tudo bom?
Alguma novidade?

Obrigado

**Comment by Levi-Moreira** [comment]
Oi @orafaaraujo desculpe pelo atraso, estou com 80% do artigo pronto, até domingo eu te envio! Obrigado :)

**Comment by Levi-Moreira** [comment]
@orafaaraujo Vou fechar a issue por enquanto, estou um pouco sem tempo de avançar no artigo e acho melhor n ficar com a issue aberta até eu ter algo concreto para repassar pra vcs :/
