### ISSUE TITLE
Configurando e utilizando o Charles Proxy para interceptar Requisições e Respostas

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#116]
* **Autor:** Gabriel Prado
* **Perfil no medium:** medium.com/@sp4wna1
* **Data escolhida:** A definir
* **Título do artigo:** Configurando e utilizando Charles Proxy para interceptar requests
* **Descrição:** Gostaria de falar um pouco mais sobre como interceptar requests e alterar seus resultados, para criar determinados estados independentes do backend.
* **Draft: https://medium.com/android-dev-br/introdu%C3%A7%C3%A3o-charles-proxy-para-interceptar-requests-e-responses-876f66399c70

**Comment by orafaaraujo** [comment]
Fala @sp4wna1 
Tudo bom?

Mil desculpas pela demora... o post está perfeito!
Pode submeter?

Abraços

**Comment by sp4wna1** [comment]
Oi @orafaaraujo, tudo certo!

Podemos submeter sim! Sem problemas.

**Comment by orafaaraujo** [comment]
Publicado!

Muito obrigado novamente pelo post de alta qualidade :)
