### ISSUE TITLE
11/01/20 - Automação com Makefile no Android - Phellipe Silva

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#117]
* **Autor:** Phellipe Silva
* **Perfil no medium:** https://medium.com/@phellipealexandre
* **Título do artigo:** Automação com Makefile no Android
* **Descrição:** Nesse artigo eu mostro como automatizar comandos de terminal específicos de Android utilizando Makefile. Esse tipo de prática ajuda na automação e na entrega contínua da App que está em desenvolvimento. O artigo é introdutório e já está publicado no Medium.

https://medium.com/@phellipealexandre/automa%C3%A7%C3%A3o-com-makefile-no-android-af0dc4f00815

Observação: Confesso que tive um pouco de dificuldade em escrever todo o post em caracter impessoal conforme descrito nas diretrizes de submissão. Gostaria de um feedback sincero se esse fator é determinante na submissão do post ou não, para que eu possa saber se dedico energia na editando a postagem.

Obrigado e abraços pessoal!

**Comment by orafaaraujo** [comment]
Fala @phellipealexandre 
Tudo bom?

Mil desculpas pela demora... sobre sua dúvida, procuramos manter uma qualidade técnica e de escrita no post.  Pedimos para escrever no impessoal para não parecer que é uma opinião pessoal (já que o post estará no Medium da comunidade), mas não é algo impeditivo. Muitas vezes o post reflete uma experiencia de quem está escrevendo. :)

**Comment by orafaaraujo** [comment]
Acabei de ler o artigo e está perfeito!
Pode submeter :) 

(E vou aproveitar pra usar esse carinha que não conhecia também hahaha)
