### ISSUE TITLE
Elevando a qualidade do código com ferramentas de Análises Estática

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#118]
* **Autor:** Gabriel Prado
* **Perfil no medium:** medium.com/@sp4wna1
* **Data escolhida:** A definir
* **Título do artigo:** Elevando a qualidade do código com ferramentas de Análises Estática
* **Descrição:** Gostaria de falar sobre o Detekt, Ktlint e Danger em um CI, para elevar a qualidade do código de um Projeto Android e de seus desenvolvedores.

**Comment by orafaaraujo** [comment]
Fala, @sp4wna1 

Alguma noticia sobre este post?

Abraços

**Comment by sp4wna1** [comment]
Opa @orafaaraujo , estou começando ele agora! Assim que tiver um draft, coloco aqui.

**Comment by orafaaraujo** [comment]
Perfeito, estamos no aguardo :)

**Comment by sp4wna1** [comment]
Olá @orafaaraujo, pretendo escrever sobre esse tópico quebrando em outras stories.

1. [Elevando a qualidade do código com ferramentas de Análises Estática](https://medium.com/@sp4wna1/elevando-a-qualidade-do-c%C3%B3digo-com-ferramentas-de-an%C3%A1lises-est%C3%A1tica-642949c68da3)
2. [Introdução — Ktlint: análise estática de código](https://medium.com/@sp4wna1/introdu%C3%A7%C3%A3o-ktlint-an%C3%A1lise-est%C3%A1tica-de-c%C3%B3digo-876794faafb7)
3. [Introdução - Detekt: análise estática de código](https://medium.com/@sp4wna1/introdu%C3%A7%C3%A3o-detekt-an%C3%A1lise-est%C3%A1tica-de-c%C3%B3digo-7f5eefcd6d9c)
4. [Introdução — Danger](https://medium.com/@sp4wna1/introdu%C3%A7%C3%A3o-danger-fe41730eafa3) + [Introdução ao Bitrise CI/CD](https://medium.com/android-dev-br/introdu%C3%A7%C3%A3o-bitrise-ci-cd-para-android-ded947f2ee47)

Meu objetivo será abordar como podemos melhorar a qualidade de código utilizando todas essas ferramentas de análise estática em conjunto com o Danger e o Bitrise.

**Comment by sp4wna1** [comment]
Oi @orafaaraujo, pretendo finalizar os 4 artigos essa semana. E irei avaliar se essa é a melhor maneira de separá-los.

**Comment by orafaaraujo** [comment]
Show de bola, @sp4wna1 
Vou revisá-los em breve :)

**Comment by orafaaraujo** [comment]
Fala, @sp4wna1 

Obrigado de novo pelos posts, eu mesmo os uso como conferencia para mexer com CI 😂 
O de Danger vai me cair como uma luva ;) 

Deixei pequenos comentários nos posts...

E é fácil adicionar o Lint no Danger também? Se sim, acho que valeria mencionar.

Abraços

**Comment by sp4wna1** [comment]
Oi @orafaaraujo ,

Bacana, fico feliz em saber que você utiliza!

Eu vou ler os comentários e responder as questões levantadas. Ainda preciso terminar a parte de Danger e alguns outros detalhes.
Sobre o Lint, eu não tenho certeza. Preciso dar uma olhada...

Abraços.

**Comment by sp4wna1** [comment]
Olá @orafaaraujo, realizei as correções e removi o arquivo "mágico" ahaha. Ficou até mais simples... Vou enviar para a publicação e aguardo a avaliação de vocês. Obrigado pelos comentários.

Sobre o Lint, eu encontrei um plugin e ele funciona perfeitamente, porem pretendo apenas menciona-lo.

**Comment by orafaaraujo** [comment]
Fala @sp4wna1 

Valeu pelas correções. Sobre a ordem, por mim tudo bem... Você quer publicar por partes em dias diferentes ou tudo de uma vez? Isso é contigo, quanto a gente sem problemas!

Abraços

**Comment by sp4wna1** [comment]
Oi @orafaaraujo! 

Pode ser tudo no mesmo dia, só preciso que seja nesta ordem e que você espere um "Ok" para o lançamento do último, pois terei que corrigir as urls que estão sendo referenciadas nele. 

Abraços!

**Comment by orafaaraujo** [comment]
Show, publicado!

Obrigado mais uma vez, esta série ficou muito bom mesmo.

Abraços
