### ISSUE TITLE
Beacons e serviços em aplicações Android 8.0+

### ISSUE THREAD

**Issue by SandyaraPeres** [androiddevbr/agenda-medium#119]
* **Autor:** Sandyara Peres
* **Perfil no medium:** medium.com/@sandyaraperes
* **Título do artigo:** Beacons: Trabalhando com serviços em background contínuos em aplicações Android Oreo+ sem irritar o usuário. Previsão para publicar dia 23/01
* **Descrição:** Gostaria de falar um pouco sobre a tecnologia beacon bem como seu funcionamento qual o.problema que desenvolvedores Android enfrentaram após a versão Oreo com a restrição de serviços em background, assim aprofundando um pouco em uma arquitetura de AlarmManagers.

**Comment by SandyPeres** [comment]
Artigo publicado: https://medium.com/@sandyaraperes/beacons-trabalhando-com-servi%C3%A7os-em-background-cont%C3%ADnuos-em-aplica%C3%A7%C3%B5es-android-oreo-sem-irritar-5499a7710a5e

:)

**Comment by orafaaraujo** [comment]
Oi, @SandyaraPeres 
Tudo bom?

Me desculpe pela demora. Acabei de ler o post e está muito bom! 
É bem legal ver um tema diferente por aqui.

Já te coloquei como _writer_ em nosso Medium, pode submete-lo? 

Tenho dois feedback para os próximos post: 
- Se possível, faça post mais curtos, com mais ou menos 4, 5 minutos. Isso anima mais as pessoas a lerem o post. O seu é longo, porém lendo eu não vejo outra alterntiva pois é um tema incomum e é importante destacar suas particularidades. Talvez seria legal separar em duas partes, uma mais teorica e outra com mais código mas não se preocupe com isso agora.
- Use o [Gist](https://gist.github.com/) para apresentar trecho de código, ele deixa o código com cara de Github :)

**Comment by orafaaraujo** [comment]
Obrigado mais uma vez, @SandyaraPeres :) 

Estamos sempre abertos a novas publicações :)
