### ISSUE TITLE
11/07/16 - Criando library com Annotation Processing - Felipe Theodoro

### ISSUE THREAD

**Issue by ftgoncalves** [androiddevbr/agenda-medium#12]
* **Autor:** Felipe Theodoro Gonçalves
* **Data escolhida:** 11/07/16
* **Título do artigo:** Criando library com Annotation Processing
* **Descrição:** Irei demonstrar como Annotation Processing funciona, exemplos e quais as vantagens de utilizar na criação de Libraries para projetos Android.

**Comment by walmyrcarvalho** [comment]
Bacana Felipe, gostei do tema. Muito obrigado pela sua contribuição! :)

**Comment by davidtcdeveloper** [comment]
Publicado, faltou o link aqui :)

https://medium.com/android-dev-br/annotation-processing-no-android-d28b734b8043#.o1poif8v9
