### ISSUE TITLE
Dagger Android, tudo que você precisa entender em português.

### ISSUE THREAD

**Issue by nicconicco** [androiddevbr/agenda-medium#120]
* **Autor:** Carlos Nicolau Galves
* **Perfil no medium:** medium.com/@nicolaugalves
* **Título do artigo:** Dagger Android, tudo que você precisa entender em português.
* **Descrição:** Oi eu escrevi sobre Android Dagger recentemente. Seria muito legal ver ele postado por aqui. Segue o link: [Dagger Android](https://medium.com/@nicolaugalves/dagger-android-tudo-que-voc%C3%AA-precisa-entender-em-portugu%C3%AAs-144cc229264d)

Caso precisem posso alterar algo escrito. Valeu espero que de certo. Meu email: nicolaugalves@gmail.com

**Comment by nicconicco** [comment]
Opa tudo bem @orafaaraujo se precisar alguma mudanca me avise. Valeu.

**Comment by orafaaraujo** [comment]
Oi @nicconicco tudo bom?

Me desculpe pela demora. Comecei a revisar o post e notei alguns padrões, então resolvi vir comentar aqui ao invés de deixar os comentários lá no Medium.

- No parênteses, evite colocar espaços antes ou depois. E deixe os pontos finais depois que fechar os parênteses. Ex.: Então aqui é um text (e aqui tem uma observação).
- Deixe os nomes próprios começando com uma letra em maiúsculo, tipo Google, Android etc. 
- Se for um nome "diferente" deixe em itálico tipo _build.gradle_, _ DaggerAppComponent_, _Activity_ etc
- Escolha um padrão para compartilhar trecho de tudo: Gist ou a própria formatação do Medium.
- Se achar legal, deixe um link junto quando citar uma lib ou afins pela primeira vez. Ex.: Esse é o [Dagger.Android](https://dagger.dev/dev-guide/android.html).
- Sugestão: o post tem 12 minutos de leitura, isso pode afastar o leitor... se achar que é possível, divida ele em 2 partes. Uma introdução e outra com coisas mais avançadas, por exemplo. Se achar que não combina, tudo bem.

Por enquanto foi o que notei. Estas informações estão também nesta página onde é o nosso [guideline](https://github.com/androiddevbr/agenda-medium/blob/master/guideline.md).

Sobre o conteúdo eu achei excelente abordar esse tema tão complexo desde do começo. Vai ajudar muita gente a finalmente entender DI e Dagger. :) 

Me avise quando realizar as mudanças. Já te coloquei como writer em nosso Medium. Assim que tiver pronto pode submeter e a gente já publica e anuncia. :) 

Abraços e obrigado desde já pelo post.

**Comment by nicconicco** [comment]
Fala @orafaaraujo beleza? Obrigado por aceitar o topico. Vou fazer em 2 partes sim. Vou pegar e fazer um projeto isolado e dar uma melhorada nele ate. Vi que tenho o acesso la no Medium mesmo! Entao agora eh quando estiver ok te aviso por aqui e voce lanca ele certo? Enquanto isso vou deixando como rascunho ne? Valeu obrigado.

**Comment by orafaaraujo** [comment]
Tá ótimo, @nicconicco 

Qualquer novidade, pinga a gente aqui.

Abraços

**Comment by orafaaraujo** [comment]
Oi, @nicconicco 

Só para ficar mais fácil pra eu encontrá-los aqui:

- Parte 1 https://medium.com/p/f67956e13227
- Parte 2 https://medium.com/p/b9f5558e7820/edit

Vou revisar agora.

Abraços

**Comment by orafaaraujo** [comment]
Fala @nicconicco 

Li os dois, o primeito está muito bom. O segundo eu deixei alguns comentários na parte do Espreso. Depois disso eu acho que já podemos publicar.

Abraços!
