### ISSUE TITLE
Tips to reduce the Android package release size - André Guedes

### ISSUE THREAD

**Issue by andreguedes** [androiddevbr/agenda-medium#121]
* **Autor:** André Guedes
* **Perfil no medium:** medium.com/@andresguedes
* **Título do artigo:** Tips to reduce the Android package release size
* **Descrição:** No post publicado falo um pouco sobre uma experiência que tive para redução de tamanho de APK, com otimização de recursos por exemplo.

[Link da publicação](https://medium.com/@andresguedes/tips-to-reduce-the-android-package-release-size-ccd6b484726e)

Observação: o post está em Inglês, porém, posso escrevê-lo em Português para maior entendimento.

**Comment by sp4wna1** [comment]
Bacana seu artigo, parabéns!
Será que não seria bom adicionar informações sobre o App Bundle também? A maioria das features novas (Dynamic Delivery, Instant App, Instant Delivery, etc...) utilizam o App Bundle e acredito que o .AAB seja o futuro dos apps Android.

**Comment by andreguedes** [comment]
> Bacana seu artigo, parabéns!
> Será que não seria bom adicionar informações sobre o App Bundle também? A maioria das features novas (Dynamic Delivery, Instant App, Instant Delivery, etc...) utilizam o App Bundle e acredito que o .AAB seja o futuro dos apps Android.

Sim!!! Estava pensando em adicionar, pois atualmente estou trabalhando apenas com App Bundle. Posso atualizar ele, com uma nova sessão para App Bundle.
Assim que atualizar, notifico aqui!!!

**Comment by orafaaraujo** [comment]
Oi @andreguedes 
Tudo bom?

Para publicarmos em nosso Medium precisamos que o post esteja em portugues. 
Pode fazer a gentileza de traduzi-lo para a gente?

Obrigado :)

**Comment by orafaaraujo** [comment]
Oi, @andreguedes 

Ainda tem interesse em traduzi-lo?

Abraços
