### ISSUE TITLE
19/02/19 - Onde usar Log? - Tiago Dávila

### ISSUE THREAD

**Issue by TiagoDvl** [androiddevbr/agenda-medium#122]
* **Autor:** Tiago Dávila
* **Perfil no medium:** https://medium.com/@tdavilas
* **Título do artigo:** Onde usar Log?
* **Descrição:** A utilização do Log pela comunidade é, muitas vezes, usada sem muito sentido e nem intenção. A vontade por trás desse artigo é trazer uma visão mais padronizada e dar uma releitura ao que hoje se utiliza com logs que não sejam chaves sem valor real.
* **Link para o artigo:** https://medium.com/@tdavilas/onde-usar-log-99a5b3079286

**Comment by orafaaraujo** [comment]
Oi, @TiagoDvl 
Tudo bom?

Acabei de ler o seu post e tenho algumas sugestões para incrementá-lo:
- Explique a diferença entre Error, Verbose, Info etc... e quando usar cada uma delas.
- Explique como funciona no LogCat (quando coloca Verbose voce pega tudo, mas se colocar Debug só pega Debug pra baixo etc)
- Explique como funciona quando roda o proguard para remover os logs da build final.
- Explique como filtrar os logs com Regex no Logcat.
- Como bonus, coloque como mudar a cor do logcat no android, tipo [assim](https://androidredman.wordpress.com/2017/07/14/change-log-cat-colors-in-android-studio/)

Bom, não precisa adicionar tudo, mas acho que seriam coisas bem legais para se ter. Quem sabe uma parte 2? 

Abraços

**Comment by orafaaraujo** [comment]
Oi, @TiagoDvl 

O que achou das sugestões?
Quer publicar assim mesmo e depois você faz uma parte 2?

Abraços
