### ISSUE TITLE
Modularização Android Parte 4.1  e Modularização Android Parte 4.2 - Iago Fucolo

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#123]
* **Autor:** Iago Fucolo
* **Perfil no medium:** medium.com/@ifucolo
* **Título dos artigos:** Modularização Android Parte 4.1  e Modularização Android Parte 4.2 
* **Descrição:** Esses dois artigos são a continuação de outros 3 ja publicados no android dev br. Esses novos artigos são uma atualização e aplicação de conceitos que foram bastante falados no ultimo ano, como coroutines por exemplo.

**Comment by ifucolo** [comment]
O primeiro artigo já está submetido para review

**Comment by ifucolo** [comment]
Segundo artigo submetido para review @orafaaraujo

**Comment by orafaaraujo** [comment]
Oi, @ifucolo 
Tudo bem?

Tenho algumas pequenas sugestões:
- Deixar alguns nomes própios com a primeira letra em maisculo, tipo livedata -> LiveData, viewmodel -> ViewModel etc
- Colocar o link do Gist direto ao invés de um print dele.

E deixei alguns poucos comentários no post.

Abraços

**Comment by ifucolo** [comment]
Blz, já está atualizado.
Sobre os gists estou utlizando links sim.

Abraço

**Comment by orafaaraujo** [comment]
Muito obrigado novamente, @ifucolo !

**Comment by orafaaraujo** [comment]
Publicado :)
