### ISSUE TITLE
Utilizando Módulos Dinâmicos no seu app Android

### ISSUE THREAD

**Issue by angelica-oliv** [androiddevbr/agenda-medium#124]
* **Autor:** Angélica Oliveira
* **Perfil no medium:** medium.com/@angelica.liv
* **Título do artigo:** Utilizando Módulos Dinâmicos no seu app Android
* **Descrição:** Meu artigo é sobre a implementação de módulos dinâmicos em aplicativos Android, com uma breve introdução sobre o tema e uma explicação sobre as modificações necessárias em um projeto existente (ou novo projeto) para que a implementação deste tipo de módulo seja possível.

**Link**: https://medium.com/@angelica.liv/utilizando-m%C3%B3dulos-din%C3%A2micos-no-seu-app-android-e04875765586

**Comment by lucas-marciano** [comment]
Quero muito ver seu material @angelica-oliv

**Comment by orafaaraujo** [comment]
Oi, @angelica-oliv 

Quando tiver um rascunho ou estiver pronto, coloque o link aqui que damos uma olhada.

Obrigado.

**Comment by angelica-oliv** [comment]
Olá @orafaaraujo!
está aqui o link, o artigo está publicado :) 
https://medium.com/@angelica.liv/utilizando-m%C3%B3dulos-din%C3%A2micos-no-seu-app-android-e04875765586

**Comment by orafaaraujo** [comment]
Oi, @angelica-oliv 

Acabei de revisar o seu post ficou muito legal! Cheio de referencias, códigos de exemplo, gifs e emojis para deixar a leitura mais suave :) 

Te coloquei como writer em nosso Medium, agora você já pode subemter o post.
Assim que fizer, me avisa que eu publico, ok?

Muito obrigado pelo conteúdo :)

**Comment by angelica-oliv** [comment]
Olaa @orafaaraujo 

Muito obrigada pelos feedbacks :) 
Acabei de submeter o post, qualquer questão, só avisar!

**Comment by orafaaraujo** [comment]
Muuuito obrigado :)

Publicado!
