### ISSUE TITLE
Mostrando conteúdo rápido no Android: App Actions & Slices - Ana Coimbra

### ISSUE THREAD

**Issue by anacoimbrag** [androiddevbr/agenda-medium#125]
* **Autor:** Ana Coimbra
* **Perfil no medium:** https://medium.com/@anacoimbrag
* **Título do artigo:** Mostrando conteúdo rápido no Android - App Actions & Slices
* **Descrição:** Atualmente está cada vez mais frequente o uso de assistentes virtuais, principalmente em smartphones. Neste cenário, os aplicativos Android conseguem obter ainda mais engajamento dos usuários através de respostas rápidas de seus conteúdos integrando com o Google Assistant. Para isso, a Google lançou **App Actions**. No artigo explico o funcionamento das App Actions com exemplos de código. Pode ser acessado no [link](https://medium.com/@anacoimbrag/mostrando-conte%C3%BAdo-r%C3%A1pido-no-android-app-actions-slices-fe6132af54af)

**Comment by orafaaraujo** [comment]
Oi, @anacoimbrag 

Acabei de revisar e ficou show!
Deixei algumas pequenas sugestões no post mas nada que seja impeditivo para a publicação. Sendo assim, já pode submeter o post e fazer as alterações quando quiser.

Como uma sugestão maior, se você quiser, seria dividir o post em 2 partes. Uma falando de Actions e outra de Slice. Acho que deveria os posts menores e mais fáceis de ler. Aí fica a seu critério também. :) 

Abraços!

**Comment by anacoimbrag** [comment]
@orafaaraujo muito obrigada pelo retorno!
Concordo que fica melhor divido mesmo, segue os links dos artigos separados: [App Actions](https://medium.com/@anacoimbrag/mostrando-conte%C3%BAdo-r%C3%A1pido-no-android-app-actions-slices-fe6132af54af) e [Slices](https://medium.com/@anacoimbrag/mostrando-conte%C3%BAdo-r%C3%A1pido-no-android-slices-338c2b1cd5b3)
