### ISSUE TITLE
Continuous Delivery com Fastlane e Android - Wilson Filho

### ISSUE THREAD

**Issue by wilfilho** [androiddevbr/agenda-medium#127]
* **Autor:** Wilson Filho
* **Perfil no medium:** https://medium.com/@wilfilho
* **Título do artigo:** Continuous Delivery com Fastlane e Android
* **Descrição:** Uma introdução sobre como a fastlane pode ser útil em projetos android. Neste post também apresento como fazer deploy automático de apks na Google Play e como integrar a fastlane ao Slack.

**Comment by orafaaraujo** [comment]
Oi, @wilfilho 

Bom assunto! :) 
Quando tiver o link manda pra gente. Também não se esqueça de seguir nossas [guidelines](https://github.com/androiddevbr/agenda-medium/blob/master/guideline.md).

Abraços

**Comment by wilfilho** [comment]
Nossa, esqueci do principal. Segue o [link do post
](https://medium.com/@wilfilho/continuous-delivery-com-fastlane-e-android-6ccc8f12a336) @orafaaraujo

**Comment by orafaaraujo** [comment]
Fala, @wilfilho 
Bem legal e completo o seu post!

Minhca única sugestão seria você padronizar os nomes próprios em maiúsculo, tipo Android, Fastlane etc. E se possível, deixar os nomes termos em inglês em itálico. O que tiver de links, pode adicionar também.

Já te coloquei como writer em nosso Medium, quando acabar a edição já pode submeter que já publicamos.

Abraços e obrigado!

**Comment by orafaaraujo** [comment]
Fala @wilfilho, tudo bom?

Alguma novidade neste post?
Ele está bem legal e próximo de ser publicado... o que acha?

Abraços

**Comment by wilfilho** [comment]
Opa @orafaaraujo tudo ótimo.

Sobre o post, fiz as atualizações que pediu e também já submeti para vocês publicarem. Fico no aguardo da publicação.

Até mais

**Comment by orafaaraujo** [comment]
Fala, @wilfilho 

Show de bola, já foi publicado 🎉
Mais tarde faremos o anúncio na comunidade e nas rede sociais :) 

Você tem twitter? Aí a gente te marca lá também

Muito obrigado novamente, abraços!

**Comment by wilfilho** [comment]
Opa, show de bola. Meu twitter é @_wilfilho.

**Comment by anacoimbrag** [comment]
@all-contributors please add @wilfilho  for blog
