### ISSUE TITLE
25/05/20 - Utilizando  Merge Adapter no Android - João Gabriel

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#128]
* **Autor:** João Gabriel
* **Perfil no medium:** https://medium.com/@1jGabriel
* **Título do artigo:** Utilizando  Merge Adapter no Android
* **Descrição:** Gostaria de falar um pouco mais sobre como utilizar Merge Adapter no android, com um exemplo simples e prático [link](https://medium.com/@1jGabriel/utilizando-mergeadapter-no-android-cea089aa8df3).

**Comment by orafaaraujo** [comment]
Oi, @1jGabriel 

Por mim o post está bacana.
Só senti falta de um link onde você mencioa ter, mas não tem.

Pode dar uma olhada?

Obrigado

**Comment by orafaaraujo** [comment]
Também te coloquei como writer em nosso Medium. Quando acabar, pode submeter e já publicamos.

Abraços

**Comment by 1jGabriel** [comment]
> Oi, @1jGabriel
> 
> Por mim o post está bacana.
> Só senti falta de um link onde você mencioa ter, mas não tem.
> 
> Pode dar uma olhada?
> 
> Obrigado

Muito obrigado pela revisão, corrigi o link.

**Comment by 1jGabriel** [comment]
> Também te coloquei como writer em nosso Medium. Quando acabar, pode submeter e já publicamos.
> 
> Abraços

Submissão feita, obrigado @orafaaraujo .

**Comment by orafaaraujo** [comment]
Publicado!
