### ISSUE TITLE
Hilt Series: Injeção de Dependência em Android com Hilt - Ramon Rabello

### ISSUE THREAD

**Issue by ramonrabello** [androiddevbr/agenda-medium#129]
* **Autor:** Ramon Rabello
* **Perfil no medium:** https://medium.com/@ramonrabello
* **Título do artigo:** Hilt Series: Injeção de Dependência em Android com Hilt
* **Descrição:** Recentemente, a Google anunciou o [Hilt](https://dagger.dev/hilt/), o sucessor e versão mais amigável do Dagger que promete se tornar a engine de DI _de-facto_ do Jetpack para o Modern Android Development, com menos boilerplate no setup, mais aderência ao Architecture Components, dentre outras features. A ideia dessa série é explicar passo-a-passo como integrar o Hilt à sua aplicação, desde o zero até uma abordagem multi-módulos.
* Parte 1: Introdução ao Hilt
* Parte 2: Architecture Components com Hilt
* Parte 3: Migrando do Dagger para o Hilt
* Parte 4: Testes com Hilt

**Comment by orafaaraujo** [comment]
Manda bala, @ramonrabello :)

**Comment by ramonrabello** [comment]
@orafaaraujo, disponibilizei [neste link](https://medium.com/@ramonrabello/hilt-series-introdu%C3%A7%C3%A3o-ao-dagger-hilt-50faa1b3a194) o draft no meu Medium do primeiro artigo da série Hilt Series, onde falo brevemente sobre o histórico de DI no Android e como que o Hilt vem contornar os principais problemas e dores ao utilizar o Dagger, mostrando passo-a-passo como configurá-lo no projeto. Ficou com 8 min. de leitura, porém acredito que podemos "enxugar" mais ainda para não correr o risco de afastar o leitor. Veja o que você acha e me dê feedbacks :)

**Comment by orafaaraujo** [comment]
Oi, @ramonrabello 

Acabei de ler e ficou show de bola. 
Teve uma parte que estava pensando na perguntar e você a respondeu hahahaha

Uma dúvida, você mostrou como injetar um `Logger` em um `@AndroidEntryPoint`, como funciona para eu injetar em classes normais?
Se você irá abordar isso nos próximos posts tudo bem, se não, acho que vale a pena mencionar como é uma classe "normal" e como é um Android Entry Point.
O que acha?

Abraços e parabéns pelo post
A comunidade agradece 🙌

**Comment by ramonrabello** [comment]
Oi, @orafaaraujo ! Obrigado pelos feedbacks! Sobre sua pergunta, o que você quer dizer como classe "normal"? Pois basicamente, o Hilt (assim como o Dagger) só poderá injetar as classes que estiverem como `@Inject` no construtor ou em se em algum módulo estiver sido definido algum binding, por meio do `@Provides` ou `@Binds`. No Hilt, é possível definir novos _entry points_ para permitir injetar classes dentro de outras classes que não são `@AndroidEntryPoint`s, que pretendo falar em próximos artigos dessa série.

**Comment by orafaaraujo** [comment]
Oi, @ramonrabello 

Obrigado pelo reply. 
No caso, estava falando de uma classe que não são @AndroidEntryPoints (mas isso não exclui estar no grafo do Dagger).
Acho que está bom, pode submeter que já publicamos hoje.

Abraços

**Comment by ramonrabello** [comment]
@orafaaraujo , acabei de publicar o o artigo, adicionei ao final o link para o repositório exemplo que criei para o post.

**Link para o Post:**
https://medium.com/@ramonrabello/hilt-series-introdu%C3%A7%C3%A3o-ao-dagger-hilt-50faa1b3a194

**Link para o Repositório de exemplo:**
https://github.com/ramonrabello/dagger-hilt-series

**Comment by orafaaraujo** [comment]
Show de bola

Acho que falou subemter pra gente. Acabei te colocar como writer (pensei que já era, foi mal)!
Pode submeter :)

**Comment by ramonrabello** [comment]
heheh tranquilo. Acabei de submeter :)

**Comment by orafaaraujo** [comment]
Publicado!

Muuuuito obrigado em nova comunidade, Ramon
Esta série será muito massa!

Abraços :D

**Comment by ramonrabello** [comment]
Fico muito feliz em contribuir com a comunidade :) 

Abraços @orafaaraujo e em breve eu mando o draft da parte 2, onde irei explicar como utilizarmos MVVM + Architecture Components com Hilt.
