### ISSUE TITLE
25/07/16 - Como criar e lidar com tarefas em background e tarefas assíncronas - Jack Miras

### ISSUE THREAD

**Issue by jackmiras** [androiddevbr/agenda-medium#13]
- **Autor:** Jackson Miras
- **Data escolhida:** 25/07/16
- **Título do artigo:** Como criar e lidar com tarefas em background e tarefas assíncronas.
- **Descrição:** Gostaria de demonstrar algumas formas de se executar tarefas em background, como gerenciar múltiplas tarefas e algumas razões para se utilizar as técnicas que serão demonstradas.

**Comment by davidtcdeveloper** [comment]
Olá @jackmiras, muito obrigado pela contribuição.
Uma dúvida: existe a possibilidade de antecipar a publicação para  11/07/16 ? 
Desta forma teríamos uma sequência de artigos fechada.

**Comment by jackmiras** [comment]
Bom dia David,
É possível antecipar o artigo sim, eu submeti para o dia 25 por que eu vi que há um artigo para o dia 11/07/16 que já foi deferido.

**Comment by davidtcdeveloper** [comment]
Maravilha, antecipei para dia 11.
Muito obrigado.

**Comment by rsicarelli** [comment]
@jackmiras cara, perdão a confusão, mas realmente temos um post pro dia **11/07/16**. Nesse caso, podemos voltar esse seu post pro dia **27/07/16**? Se sim, peço que edite o título da _issue_, adicionando a data no inicio

**Comment by jackmiras** [comment]
@rsicarelli Não tem problema, pode ser dia 25/07/16 sim!

**Comment by rsicarelli** [comment]
Você é o cara! Valeu, mano 👊

**Comment by walmyrcarvalho** [comment]
Boa @jackmiras, ansioso pelo teu artigo! :)

**Comment by jackmiras** [comment]
Olá @walmyrcarvalho desculpe pela demora, estou vindo de umas semanas de problemas no PC e entregas de projeto, também estou na correria aqui para fechar meu artigo e estou muito ansioso visto que é uma responsabilidade e tanto escrever um artigo para o Medium do Android Dev BR! Espero que o artigo seja de grande utilidade para as pessoas que estão começando com desenvolvimento Android e tem dúvidas de como fazer esse tipo de coisa.

**Comment by jackmiras** [comment]
Bom dia pessoal, eu estou tendo problemas em terminar meu artigo e gostaria de saber se eu consigo mais um dia para enviar o mesmo para vocês.... Nessa semana minha Startup recebeu um a confirmação da seleção do Google Launch Pad e ai passamos a semana na correia para vir para São Paulo. O evento vai começar hoje 23/07 logo mais as 9h e por conta da viagem eu acho que não vou conseguir ler e ajustar meu artigo a algumas revisões que amigos desenvolvedores e algumas pessoas não tão técnicas me enviaram.
Eu tenho total consciência de que o compromisso de fazer/entregar o artigo até o dia 25/07 deveria ser respeitado independente das circunstâncias, mas dado que o tema do artigo é para iniciantes eu gostaria de publicá-lo de modo que a linguagem do texto fosse a mais simples e clara possível.

Emfim, caso seja possível postergar o envio do artigo por mais um dia eu ficaria muito grato.

**Comment by davidtcdeveloper** [comment]
Ok @jackmiras Vamos conversar entre os admins para analisar as alternativas.
Mas adicione o post na publicacao quando puder. Se quiser ja adicionar uma versao inicial, a gente ja vai revisando e acompanhando.
Obrigado.

**Comment by jackmiras** [comment]
@davidtcdeveloper tem algum e-mail que eu possa enviar o preview do artigo?

**Comment by davidtcdeveloper** [comment]
@jackmiras Pode adicionar a publicacao, vai ficar visivel para a gente revisar e voce pode continuar editando sem problemas. O artigo vai continuar privado ate que a gente efetue a publicacao.

**Comment by jackmiras** [comment]
Olá @davidtcdeveloper não entendi o que exatamente eu devo fazer para deixar o meu artigo visível para vocês... Caso alguém possa me ajudar com isso eu ficaria muito grato.

**Comment by davidtcdeveloper** [comment]
Passarei as instruções pelo slack, acho que ficará mais rápido pra resolver ;)

**Comment by davidtcdeveloper** [comment]
Publicado: https://medium.com/android-dev-br/trabalhando-com-tarefas-em-background-3d4da889ddfa#.odk4n9bu4
