### ISSUE TITLE
Java Home e Gradle Daemon - Rafa Araujo

### ISSUE THREAD

**Issue by orafaaraujo** [androiddevbr/agenda-medium#130]
* **Autor:** Rafa Araujo
* **Perfil no medium:** https://medium.com/@orafaaraujo
* **Título do artigo:** Java Home e Gradle Daemon
* **Descrição:** Saiba como usar a mesma instancia no terminal e IDE salvando seu tempo e sua memória.

Link com o draft: https://medium.com/@orafaaraujo/java-home-e-gradle-daemon-e66af394fd63

**Comment by anacoimbrag** [comment]
Ficou excelente @orafaaraujo ! Pode submeter! 👏
