### ISSUE TITLE
26/06/19 - Configurando GitHub Actions para Android - Arildo Borges Jr

### ISSUE THREAD

**Issue by arildojr7** [androiddevbr/agenda-medium#131]
* **Autor:** Arildo Borges Jr
* **Perfil no medium:** https://medium.com/@arildojr
* **Título do artigo:** Configurando GitHub Actions para Android
* **Link para o artigo:** https://medium.com/@arildojr/configurando-github-actions-para-android-91309fa9a62c
* **Descrição:** Gostaria de falar um pouco mais sobre como fazer uma implementação simples do GitHub Actions para CD/CD em ambiente android.

**Comment by orafaaraujo** [comment]
Oi, Arildo

Acabei de ler o post e está bem legal.
Só adicionei alguns comentários para deixar alguns nomes especiais em destaque.

Publicamos na semana que vem, tudo bem? :)

Abraços e muito obrigado.

**Comment by arildojr7** [comment]
Obrigado por ler Rafa, acabei de fazer os ajustes lá. Valeu 😎

**Comment by orafaaraujo** [comment]
Oi, Arildo

Já te coloquei como writer em nosso Medium.
Quando quiser, pode submeter!

Abraços e muito obrigado em nome da nossa comunidade. :)

**Comment by arildojr7** [comment]
Opa, show 😎 . Já submeti lá. Abração

**Comment by orafaaraujo** [comment]
Oi, Arildo

Pode dar uma olhada no post?
Não consigo submeter ele... só me aparece o botão desabilitados aqui.

Abraços

**Comment by orafaaraujo** [comment]
Ah, descobri... a data dele é 25 de Janeiro.
Vou pedir pro Medium alterar a data pra essa semana, aí ele fica lá em cima. :)

Abraços!
