### ISSUE TITLE
Implementando Jetpack Navigation Component com Módulos de Features Dinâmicas no Android

### ISSUE THREAD

**Issue by angelica-oliv** [androiddevbr/agenda-medium#132]
* **Autor:** Angélica de Oliveira
* **Perfil no medium:** medium.com/@angelica.liv
* **Título do artigo:** Implementando Jetpack Navigation Component com Módulos de Features Dinâmicas no Android
* **Descrição:** Neste artigo, vou falar sobre como a Navigation Library pode ajudar na implementação de módulos com funcionalidades dinâmicas, deixando o código bem mais simples e fácil. Para isso dou vários exemplos de código e adiciono as referências da documentação.

Link do rascunho: https://medium.com/@angelica.liv/implementando-jetpack-navigation-component-com-m%C3%B3dulos-de-features-din%C3%A2micas-no-android-e604c13d235f

**Comment by orafaaraujo** [comment]
Oi, Angélica, tudo bom?

Acabei de revisar o seu post, acho que ele ficou muito bom! 
Só faltou a imagem do cachorrinho feliz citada no texto :P 

Quando colocar, já pode submeter para o nosso Medium, okay?

Mais uma vez, nosso muito obrigado em nova da comunidade. :)

**Comment by angelica-oliv** [comment]
Olá! Estou bem e vc?
Obrigada Rafa!
Aparentemente tinha um problema com alguns links q eu tinha adicionado ao post.
Revisei, adicionei o que faltava e submeti. :)

**Comment by orafaaraujo** [comment]
Tudo ótimo :) 

Publicado, valeu!
