### ISSUE TITLE
10/07/20 - Acessibilidade em Android (Parte 1): UI - Sandyara Peres

### ISSUE THREAD

**Issue by SandyaraPeres** [androiddevbr/agenda-medium#133]
* **Autor:** Sandyara Peres
* **Perfil no medium:** medium.com/@sandyaraperes
* **Título do artigo:** Acessibilidade em Android (Parte 1): UI - Sandyara Peres
* **Descrição:** Início de uma série que pretendo fazer de Acessibilidade em Android! Esse primeiro artigo é um compilado de alguns toques de design - principalmente UI - para os desenvolvedores, a ideia é continuar a série de artigos por desenvolvimento e finalizando com testes (manuais e automatizados). Link para o artigo: https://medium.com/@sandyaraperes/acessibilidade-em-android-parte-1-ui-3e936b03168d

**Comment by orafaaraujo** [comment]
Oi, @SandyaraPeres 

O link está dando 404, poderia revisar? :) 

Obrigado :)

**Comment by SandyaraPeres** [comment]
@orafaaraujo consertei já!!! Obrigada por avisar ;D

**Comment by orafaaraujo** [comment]
Oi, @SandyaraPeres 

Adicionei alguns comentários no post. Alguns são apenas sugestões :)

Quando acabar, já pode submeter para o nosso Medium.

Obrigado mais uma vez :)

**Comment by SandyaraPeres** [comment]
@orafaaraujo não estou conseguindo visualizar os notes no Medium :(

**Comment by orafaaraujo** [comment]
Oi, @SandyaraPeres 

Deixei uma nota de teste, ve se aparece agora

**Comment by SandyaraPeres** [comment]
@orafaaraujo finalizei quase agora a parte 2 desse artigo e FINALMENTE achei os tais comentários HAUHAUHA estou me sentindo bem burra com isso! Farei as devidas correções! ;)

**Comment by orafaaraujo** [comment]
Olá, @SandyaraPeres 

Acabei de reler o post e está ótimo, vamos publicar? 🎉 
Você já está como Writer em nosso Medium, quando tiver um tempinho é só submeter que já aprovamos, ok?

Mais uma vez muito obrigado por sua contribuição para nossa comunidade 🙌
