### ISSUE TITLE
Testes em Android: Utilizando testes de Snapshot

### ISSUE THREAD

**Issue by soutoss** [androiddevbr/agenda-medium#134]
* **Autor:** Thiago Souto
* **Perfil no medium:** https://medium.com/@soutoss/
* **Título do artigo:** Testes em Android: Utilizando testes de Snapshot
* **Descrição:** Esse artigo tem como objetivo explicar o que é um teste de snapshot e trazer um exemplo prático de como configurar e aplicar esse teste em um aplicativo android utilizando a biblioteca do Facebook, screenshot-tests-for-android.

Artigo publicad em https://medium.com/@soutoss/utilizando-testes-de-snapshot-2fa770903ed7

**Comment by orafaaraujo** [comment]
Oi, @soutoss 

Parabéns pelo post, ficou bem direto e objetivo!
Deixei um comentário mas é só uma sugestão.

Bora publicar? É só submeter :) 

Abraços e muito obrigado em nome da comunidade.
