### ISSUE TITLE
Utilizando o Jetpack Paging v3

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#135]
* **Autor:** João Gabriel
* **Perfil no medium:** medium.com/@1jGabriel
* **Título do artigo:** Utilizando o Jetpack Paging v3
* **Descrição:** Gostaria de demonstrar como utilizar a nova versão da paging library do jetpack, com um exemplo simples e prático. [Link aqui](https://medium.com/@1jGabriel/utilizando-o-jetpack-paging-v3-460f59b9217e)

**Comment by orafaaraujo** [comment]
Fala @1jGabriel 
Tudo bom?

Acabei de revisar o post, está bem legal!
Não tenho nenhum comentário... então vamos publicar assim que você submeter em nosso Medium, tudo bem?

Mais uma vez, obrigado pela contribuição com a comunidade. 🎉

Abraços

**Comment by 1jGabriel** [comment]
Fala @orafaaraujo, tudo ótimo, e com você?

Já fiz a submissão.

Muito obrigado!
