### ISSUE TITLE
23/07/20 - Iniciação tardia de variáveis com lazy e lateinit - Armando Picon

### ISSUE THREAD

**Issue by DevPicon** [androiddevbr/agenda-medium#136]
* **Autor:** Armando Picon
* **Perfil no medium:** medium.com/@devpicon
* **Título do artigo:** Iniciação tardia de variáveis com lazy e lateinit
* **Descrição:** A idéia do meu artigo é falar de forma introdutória sobre iniciação tardia de variáveis.

**Comment by orafaaraujo** [comment]
Tema show, @DevPicon 

No aguardo :)

**Comment by orafaaraujo** [comment]
Fala, @DevPicon, tudo bom?

Alguma novidades?
Abraços!

**Comment by DevPicon** [comment]
Oi @orafaaraujo !! Desculpe, mas esqueci de compartilhar o link

https://medium.com/@devpicon/inicia%C3%A7%C3%A3o-tardia-de-vari%C3%A1veis-com-lazy-e-lateinit-895689dc39a6

**Comment by DevPicon** [comment]
ping @orafaaraujo @angelica-oliv ?

**Comment by orafaaraujo** [comment]
Olá, @DevPicon 

Acabei de revisar o post está OK.
Eu colocaria como sugestão apenas três pontos:

1. Ambos `by lazy` e `lateinit` são chamados para evitar que você precise checar nulo toda vez que precisar acessar o objeto. Exemplo: `user?.id`
2. Mencionar que o `by lazy` só será iniciado quando a variável for chamada, então caso precisar de algum objeto que só será criado posteriormente a criação da classe (`Context`) é seguro usar o `by lazy`.
3. E que `lateinit` pode ser perigoso e só deve ser usado quando o app tem certeza que encontrará aquele objeto preenchido. Caso contrário você receberá uma exception `UninitializedPropertyAccessException`.

Mas fica ao seu critério. :) 

Te coloquei como **writer** em nosso Medium, quando quiser é so submeter que já publicamos.

Obrigado pela contribuição com a nossa comunidade, as portas estão sempre abertas! 🎉

**Comment by orafaaraujo** [comment]
Olá, @DevPicon 
Tudo bom?

alguma novidade?

Obrigado

**Comment by DevPicon** [comment]
Oi @orafaaraujo 
Sim, agora mesmo tou fora da cidade, mas já submetei o artigo.
Quando esteja de volta em casa vou adicionar seus comentários. 
Muito obrigado pelo feedback! :)

**Comment by orafaaraujo** [comment]
Perfeito!

Abraços e obrigado mais uma vez, @DevPicon .
As portas estarão sempre abertas :D

**Comment by orafaaraujo** [comment]
Só mais um detalhe que me passou batido. Também precisamos de uma imagem de header, pode ser qualquer uma. :)

**Comment by DevPicon** [comment]
Oi @orafaaraujo !
Done!

**Comment by anacoimbrag** [comment]
@all-contributors please add @DevPicon  for blog
