### ISSUE TITLE
Hilt Series: Architecture Components com Dagger Hilt - Parte 2

### ISSUE THREAD

**Issue by ramonrabello** [androiddevbr/agenda-medium#137]
Autor: Ramon Rabello
Perfil no medium: https://medium.com/@ramonrabello
Título do artigo: Hilt Series: Architecture Components com Dagger Hilt
Descrição: Essa é a segunda parte da Hilt Series, onde será apresentado um breve histórico sobre Architecture Components, as dores e complexidade em torno da injeção do ViewModel com Dagger e como que o Hilt veio simplificar bastante todo esse processo.

**Comment by ramonrabello** [comment]
Oi @orafaaraujo !

Segue o link (draft) do artigo:
https://medium.com/@ramonrabello/hilt-series-architecture-components-com-dagger-hilt-3f10b6345f42

**Comment by ramonrabello** [comment]
@orafaaraujo adicionei os links de referências que tinha esquecido :sweat_smile:

**Comment by orafaaraujo** [comment]
Oi, @ramonrabello 

Este é aqueles posts que se estivesse em inglês eu compartilhava para os amigos daqui da onde trabalho hahaha
Ficou muito bom e ilustrativo.

Pode submeter que postamos já.

Abraços

**Comment by ramonrabello** [comment]
> Este é aqueles posts que se estivesse em inglês eu compartilhava para os amigos daqui da onde trabalho hahaha

Que bom que curtiu, valeu pelo feedback! Em breve, eu vou postar a série também em Inglês no meu Medium, primeiro to dando prioridade para a comunidade brasileira, que encontramos poucas informações em Português ainda sobre Dagger Hilt.

**Spoiler:** Essa semana eu termino a parte 3 que fala sobre Migração do Dagger para o Hilt e mando o draft aqui para você revisar.

Vou adicionar à publicação do ADBR essa parte 2 e te aviso.

Abraços!

**Comment by ramonrabello** [comment]
Done @orafaaraujo !

**Comment by orafaaraujo** [comment]
Publicado, Ramon
Obrigado novamente!

Abraços!
