### ISSUE TITLE
01/08/16 - Continuous Deployment no Android - Júlio Zynger

### ISSUE THREAD

**Issue by julioz** [androiddevbr/agenda-medium#14]
* **Autor:** Júlio Zynger
* **Data escolhida:** 01/08/16
* **Título do artigo:** Continuous Deployment no Android
* **Descrição:** Overview sobre o conceito de continuous deployment, apresentação da Publishing API e exemplos de como utilizá-la para automatizar os releases dos apps.

O artigo já foi publicado [aqui](https://medium.com/@juliozynger/continuous-deployment-no-android-f42b96ece80d#.1q4dotvk1), mas através do medium da comunidade o conhecimento pode ser disseminado mais rapidamente.

**Comment by davidtcdeveloper** [comment]
Excelente artigo @julioz!
Poderia adicioná-lo a publicação do Android Dev BR? Só o autor pode adicionar à publicação.
Depois que ele for adicionado, vamos conversar aqui sobre a melhor data para publicação.

**Comment by julioz** [comment]
@davidtcdeveloper O que quer dizer com "adicioná-lo a publicação do Android Dev BR" (se refere ao Medium?), e como posso fazê-lo?

**Comment by davidtcdeveloper** [comment]
@julioz Nossa página do medium é uma publicação, ou seja, os autores precisam incluir seus textos a ela para que a gente possa publicá-los.
O Medium tem mais informações sobre isso aqui: https://help.medium.com/hc/en-us/articles/213904978-Add-to-publication

**Comment by julioz** [comment]
@davidtcdeveloper Obrigado pela ajuda, incluí para a publicação. _Vivendo e aprendendo_ :)

**Comment by davidtcdeveloper** [comment]
Publicado :tada: https://medium.com/android-dev-br/continuous-deployment-no-android-f42b96ece80d#.6bhiypdv8
