### ISSUE TITLE
Configurando CI/CD com Github Actions e Firebase App Distribution para projetos Android - Denis Vieira

### ISSUE THREAD

**Issue by denisvieira05** [androiddevbr/agenda-medium#143]
**Autor**: Denis Vieira
**Perfil no medium**: medium.com/@denisvieira
**Título do artigo**: Configurando CI/CD com Github Actions e Firebase App Distribution para projetos Android
**Descrição**: Artigo com o objetivo de ser bem prático e simples onde procuro demonstrar a aplicação de uma automação simples para CI/CD utilizando o Github Actions para agilizar o processo de desenvolvimento no Android. Link do Artigo: https://dev.to/denisvieira05/configurando-ci-cd-com-github-actions-e-firebase-distribution-para-projetos-android-5b47

**Comment by orafaaraujo** [comment]
Fala, Danis, tudo bom?

Acabei de ler o seu post, ficou bem bacana. 
Como sugestão, eu só falaria para você colocar alguns prints dos passos iniciais no GitHub.

Pode mandá-lo para o nosso Medium e submete-lo?
Quando fizer, só vou conferir os links e já publico. 

Abraços e muito obrigado :)

**Comment by denisvieira05** [comment]
@orafaaraujo Opa Rafa, que bom que gostou . Não sei especificamente os passos que você fala dos prints mas adicionei algumas que imaginei nessa parte inicial aqui e fiz o publish lá no medium. Como faço pra submete-lo ? . Segue o link abaixo

https://medium.com/denisvieira/configurando-ci-cd-com-github-actions-e-firebase-app-distribution-para-projetos-android-8df02096610b

**Comment by orafaaraujo** [comment]
Fala @denisvieira05 

Bom, neste link do Medium você já colocou o print que eu pensava :) 

Te coloquei como writer em nosso Medium, agora você pode clicar em "editar post" lá em cima nos 3 pontinhos que lá tem a opção de submeter. 

Fazendo isso eu já aprovo aqui e já fica publicado 🎉

Obrigado novamente :)

**Comment by denisvieira05** [comment]
show @orafaaraujo !! muito obrigado você pela ajuda !! submeti lá !! abraço !

**Comment by orafaaraujo** [comment]
Feito!

Você tem twitter pra gente te marcar lá? 

Abraços

**Comment by denisvieira05** [comment]
tenho sim @orafaaraujo , segue : https://twitter.com/fromdenisvieira

**Comment by anacoimbrag** [comment]
@all-contributors please add denisvieira05 for blog
