### ISSUE TITLE
Escreva código mais rápido com Live Templates - João Gabriel

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#144]
* **Autor:** João Gabriel
* **Perfil no medium:** https://medium.com/@1jGabriel
* **Título do artigo:** Escreva código mais rápido com Live Templates
* **Descrição:** Artigo demonstrativo de como utilizar Live Templates no android com 1 exemplo
link : https://medium.com/@1jGabriel/escreva-c%C3%B3digo-mais-r%C3%A1pido-com-live-templates-83e1765f796e

**Comment by orafaaraujo** [comment]
Fala, João

Ficou bacana o post, eu, pessoalmente adoro Live Templates 🔥
Como sugestão, só pediria para você deixar em itálico algumas palavras chaves e/ou palavras em inglês.

Feito isso, pode submeter. :) 

Abraços e obrigado novamente.

**Comment by 1jGabriel** [comment]
Fala Rafa !

Obrigado, também tenho curtido essas automações para acelerar o processo de desenvolvimento =) .

Fiz as alterações e submeti.

Obrigado pelo feedback, abraços!

**Comment by orafaaraujo** [comment]
Publicado, @1jGabriel 

Obrigado mais uma vez.

Abraços!
