### ISSUE TITLE
 Como Flow pode nos ajudar a fazer um carrossel - João Victor

### ISSUE THREAD

**Issue by jaozinfs** [androiddevbr/agenda-medium#145]
Autor: João Victor Oliveira
Perfil no medium: medium.com/@joaofgz123
Título do artigo: Flow e ViewPager
Descrição: Pessoal, hoje vamos ver um pouco como Flow pode nos ajudar fazer de uma forma elegante e bem mais organizada a se fazer um carrossel.

**Comment by orafaaraujo** [comment]
Olá, @jaozinfs 
Tudo bem?

Já tem o link para a gente dar uma olhada?

Obrigado :)

**Comment by jaozinfs** [comment]
Oi @orafaaraujo ,

**Comment by jaozinfs** [comment]
Oi @orafaaraujo , Jóia ?
Teria algo que eu possa melhorar no artigo ?
É meu primeiro artigo, e estou bastante ansioso.

**Comment by orafaaraujo** [comment]
Fala, @jaozinfs 
Tudo bem?

Eu ainda não revisei, tentarei fazer isso no final de semana ou na próxima semana.
Qualquer feedback eu te mando aqui e a gente resolve rapidinho :) 

Obrigado desde já 🎉

**Comment by jaozinfs** [comment]
@orafaaraujo Boa noite, jóia?
Alguma novidade ?
Desde já agradeço!

**Comment by angelica-oliv** [comment]
Olá @jaozinfs ! Tudo bem?
Estou dando uma força por aqui também...

Li seu artigo e gostei muito do assunto! Coloquei algumas sugestões de melhorias nos comentários, se puder analisar e ver o que faz sentido para vc! ;)

Obrigada pela contribuição!!

**Comment by jaozinfs** [comment]
Oi @angelica-oliv ! Tudo bem e com você ?
Obrigado novamente! 
Realizei as alterações, poderia reavaliar ?
Obrigado.

**Comment by angelica-oliv** [comment]
Olaa @jaozinfs ! Obrigada por rever :) 
Deletei todos os comentários que já estão OK...
Tiveram alguns que acredito que tenha passado despercebido, e ainda ficaram lá. Se você puder revisar por favor...
Também coloquei mais alguns comentários para facilitar a leitura dos códigos adicionados, movendo-os para gist, veja o que acha! 😄

**Comment by jaozinfs** [comment]
Oi @angelica-oliv ! 
Revi os comentários e os gist, ja realizei todas alterações.
Obrigado novamente !

**Comment by angelica-oliv** [comment]
Olá @jaozinfs !
Revisei aqui e está tudo OK! 😃 
Te adicionei como writer da nossa página do Medium...
Pode submeter seu artigo!

Mais uma vez, muito obrigada pela contribuição! 🥳

**Comment by jaozinfs** [comment]
Oi @angelica-oliv !
Estou muito feliz que gostou do conteúdo, pretendo escrever muito ainda.
É um passo muito grande que estou dando, mais uma vez, obrigado por tudo !
Já realizei a submissão.

**Comment by angelica-oliv** [comment]
Seu artigo foi publicado!! 
Mais uma vez, obrigada 🎉

**Comment by angelica-oliv** [comment]
Olá @jaozinfs ! Tudo bem?
Vc está no nosso slack Android Dev BR?
Se sim, poderia me passar o seu usuário lá para podemos te marcar em uma publicação de divulgação do seu artigo?

**Comment by jaozinfs** [comment]
Oi @angelica-oliv ! Tudo bem e com você ?
Estou sim, meu nome é Joao Victor Oliveira, Android Engineer Zup.
Obrigado novamente !

**Comment by anacoimbrag** [comment]
@all-contributors please add @jaozinfs for Blogposts

**Comment by anacoimbrag** [comment]
@all-contributors please add jaozinfs for Blogposts

**Comment by anacoimbrag** [comment]
@all-contributors please add jaozinfs for blog
