### ISSUE TITLE
Como implementar InAppReview - Nome do Autor

### ISSUE THREAD

**Issue by iagofucolo** [androiddevbr/agenda-medium#146]
* **Autor:** Iago Mendes Fucolo
* **Perfil no medium:** medium.com/@ifucolo
* **Título do artigo:** Como implementar InAppReview
* **Descrição:** Artigo explicando como implementar InAppReview nativamente

**Comment by orafaaraujo** [comment]
Fala, @iagofucolo 
Tudo bem?

Bom tema!
Quando tiver um rascunho manda pra gente

Abraços!
