### ISSUE TITLE
Como implementar InAppReview - Iago Fucolo

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#147]
Autor: Iago Mendes Fucolo
Perfil no medium: medium.com/@ifucolo
Título do artigo: Como implementar InAppReview
Descrição: Artigo explicando como implementar InAppReview nativamente

**Comment by orafaaraujo** [comment]
Fala, @ifucolo 
Tudo bem?

Quanto tiver o link manda pra gente

Abraços!

**Comment by ifucolo** [comment]
opa @orafaaraujo 
tudo certo e por ai?

Segue o link do draft e também já adicionei a publicação ao medium do AndroidDevBr.

https://medium.com/android-dev-br/como-implementar-inappreview-83ae04e1f5c8

**Comment by angelica-oliv** [comment]
E aí @ifucolo !
Tudo bem? Estou ajudando o pessoal na revisão de artigos por aqui :)
Li o seu, muito bom! Bem direto e simples de entender!
Só fiz alguns comentários de pequenas melhorias no artigo, veja o que acha...

**Comment by ifucolo** [comment]
Eaai @angelica-oliv, tudo certo e por ai?
Já fiz as alterações de acordo com seus comentários.

**Comment by angelica-oliv** [comment]
Olaa @ifucolo ! Tudo bem sim!
Seu artigo foi publicado 😄 
Muito obrigada pela contribuição!
