### ISSUE TITLE
Como exibir o grafo de dependências do seu projeto Android no README - Fred Porciúncula

### ISSUE THREAD

**Issue by tfcporciuncula** [androiddevbr/agenda-medium#149]
* **Autor:** Fred Porciúncula
* **Perfil no medium:** https://medium.com/@tfcporciuncula
* **Título do artigo:** Como exibir o grafo de dependências do seu projeto Android no README
* **Descrição:** Eu achei que ia ser legal ter o grafo de dependências do meu projeto no README e escrevi uma GitHub Action pra manter o grafo sempre atualizado automaticamente. O blogpost fala sobre isso mostrando todos os detalhes da implementação.

Link do draft: https://medium.com/@tfcporciuncula/como-mostrar-o-grafo-de-depend%C3%AAncias-do-projeto-m%C3%B3dulos-gradle-no-seu-readme-b83656185e2f

Isso na real será a tradução de um [post em inglês](https://medium.com/@tfcporciuncula/how-to-display-the-project-dependency-graph-gradle-modules-in-your-readme-file-e52dcadafa7a) que eu também vou publicar. A ideia com a tradução é aumentar o alcance do post.

Faz muito tempo que eu não escrevo nada em português (zero orgulho disso) e eu acho que talvez o texto tenha ficado um pouco informal, mas eu confesso também que eu não queria deixá-lo muito formal -- eu acho que a informalidade nesse caso ajuda um pouco na narrativa. Mas estarei aberto ao feedback :)

**Comment by orafaaraujo** [comment]
Olá, @tfcporciuncula 
Tudo bem?

Acabei de ler o post e está bem bacana. Pretendo usá-lo no futuro também 🚀 

Te coloquei como _writer_ em nosso Medium. Pode submete-lo?

Feito isso já anunciamos na comunidade :) 

Muito obrigado!

**Comment by tfcporciuncula** [comment]
@orafaaraujo Obrigado! 🙌 

Tudo bem se adiarmos a publicação para terça-feira da próxima semana? Eu queria publicar ele mais perto da versão em inglês que eu acho que vai ser publicada no começo da próxima semana (mas se não for tudo bem, podemos fechar na próxima terça independente).

Mas já vou submeter o artigo para a publicação de qualquer forma.

**Comment by orafaaraujo** [comment]
Olá, @tfcporciuncula 

Sim, sem problemas! Se puder, nos avise aqui quando podemos publicar 🎉

Sobre a linguagem informações, eu acho que ficou bom porque você está expondo sua experiência, ficou bacana. :) 

Abraços e muito obrigado novamente.

**Comment by tfcporciuncula** [comment]
@orafaaraujo pode publicar! 🚀

**Comment by orafaaraujo** [comment]
Obrigado mais uma vez, @tfcporciuncula 

Publicado 🎉

Abraços!

**Comment by anacoimbrag** [comment]
@all-contributors please add @tfcporciuncula  for blog
