### ISSUE TITLE
01/08/16 - Builds Types e Flavors! - Rafael de Araújo

### ISSUE THREAD

**Issue by orafaaraujo** [androiddevbr/agenda-medium#15]
* **Autor:** Rafael de Araújo
* **Data escolhida:** 01/08/16
* **Título do artigo:** Builds Types e Flavors!
* **Descrição:** Post sobre Flavors e BuildType. Explicando o que é, quando utilizar e como utilizar.

**Comment by davidtcdeveloper** [comment]
A ideia é muito boa @orafaaraujo. Apenas uma sugestão: colocar no título que se tratam de _builds_ e _flavours_. Desta forma fica mais fácil para o leitor e torna mais fácil encontrar nas buscas.

**Comment by orafaaraujo** [comment]
O link do draft está aqui caso queiram ir vendo
https://medium.com/@orafaaraujo/2fa7b2ba4a9a

Estou acabando a parte de código para poder postar lá

(sugestões, é claro, são sempre bem-vindas)

**Comment by davidtcdeveloper** [comment]
Legal @orafaaraujo :)
Lerei esta semana ainda. Se assim que tiver completo avisa que eu leio de novo.
Detalhe: gostei da imagem do header.

**Comment by davidtcdeveloper** [comment]
@orafaaraujo Li agora, acho que está ficando bem legal.
Senti falta de uma comparação dos flavors com build types. São conceitos bem parecidos e que muita gente confunde.
Outra sugestão é mostrar nos exemplos como obter no código java valores definidos nos flavors, bem como a criação de resources diferentes para flavors diferentes.

**Comment by orafaaraujo** [comment]
Opa, pode deixar!
O código está nesse repositório https://github.com/orafaaraujo/SweetDroid
Já fiz a distinção de resources, só falta fazer a parte de classes para importar no post e finalizar ele.

**Comment by orafaaraujo** [comment]
Acabei de publicar o post no meu medium 
Segue o link: https://medium.com/@orafaaraujo/flavors-2fa7b2ba4a9a#.gti1tdczy

Qualquer coisas, estamos aí!

**Comment by davidtcdeveloper** [comment]
Publicado! https://medium.com/android-dev-br/flavors-2fa7b2ba4a9a#.fnfta3mfq
