### ISSUE TITLE
Animando Items da RecyclerView - Luis Filipe de Almeida

### ISSUE THREAD

**Issue by luisAlmeidaf** [androiddevbr/agenda-medium#152]
* **Autor:** Luis Filipe de Almeida
* **Perfil no medium:** https://medium.com/@luisalmeidaf
* **Título do artigo:** Animando Items da RecyclerView
* **Descrição:** No artigo eu faço um tutorial simples de como animar os itens de uma recyclerView. assim eles nao aparecem na tela todos de uma vez, aumentando um pouco a UX. segue aqui o link: 
https://luisalmeidaf.medium.com/animando-o-loading-de-items-da-recyclerview-35adbebfb937

**Comment by orafaaraujo** [comment]
Fala @luisAlmeidaf Tudo bem?

Parabéns pelo post! 🎉 
Deixei pequenas sugestões. Basicamente destacar as palavras "diferentes" que podem ajudar o leito a se localizar na leitura. :) 

Do mais, está show!
Já te coloquei como **writer** em nosso Medium também. Quando realizar as edições pode submeter em nosso Medium.

Em nome da comunidade, muito obrigado!

**Comment by orafaaraujo** [comment]
Olá, @luisAlmeidaf 
Pode submeter o post em nosso Medium?
Se precisar de ajuda, me chama.  

Abraços

**Comment by orafaaraujo** [comment]
Olá, @luisAlmeidaf 

Alguma novidade sobre a submissão?
Se tiver alguma novidade, me dá um alô.

Obrigado :D

**Comment by orafaaraujo** [comment]
Publicado!

**Comment by orafaaraujo** [comment]
@all-contributors please add @luisAlmeidaf  for blog

**Comment by anacoimbrag** [comment]
@all-contributors please add @luisAlmeidaf  for blog
