### ISSUE TITLE
Ícones Animados Android - Diego Salviano de Souza

### ISSUE THREAD

**Issue by coopoot** [androiddevbr/agenda-medium#153]
* **Autor:** Diego Salviano de Souza
* **Perfil no medium:** medium.com/@diegosalviano2007
* **Título do artigo:** Ícones Animados Android
* **Descrição:** Pessoal hoje vamos ver um pouco sobre animação, vamos dar vida ao menu onde ao invés de ser um ícone fixo podemos adicionar uma animação

https://medium.com/@diegosalviano2007/%C3%ADcones-animados-android-f18f192f18d7

**Comment by angelica-oliv** [comment]
Olá @coopoot! Desde já, obrigada pela contribuição!
Comecei a revisar seu artigo, mas ainda não terminei. Coloquei algumas dicas para melhorar a escrita, veja se fazem sentido. :) 
Agora, gostaria de te dar duas sugestões: 
- Primeiro, vi que parte do artigo é bem focada na elaboração do ícone, e a outra parte é focada na implementação no Android Studio, o que acha  de dividir o artigo em 2 artigos? Com parte 1 e parte 2.
- Segundo, na parte referente ao Android, temos exemplos de código, que acredito que se mudar a forma de apresentação dos exemplos de código, usando gist, poderia facilitar a leitura. Veja aqui um artigo sobre como fazer isso: https://blog.medium.com/yes-we-get-the-gist-1c2a27cdfc22.

Veja o que acha, qualquer dúvida pode perguntar! 😉

**Comment by coopoot** [comment]
Olá @angelica-oliv muito obrigado por levantar esses pontos, acabei de fazer os ajustes sugeridos.

**Comment by angelica-oliv** [comment]
Olá @coopoot me desculpe pela demora, mas hoje terminei de revisar seu artigo!
Obrigada por ter aceitado minhas primeiras sugestões, agora tem mais algumas lá, removi todas que já estavam OK. ;)

Você poderia dar uma olhada lá?

**Comment by angelica-oliv** [comment]
Olá @coopoot !
Acabei de ver que fez os ajustes, apenas coloquei mais 2 comentários... Vc poderia analisá-los?
Depois avisa por aqui que fazemos a publicação! ;)

**Comment by diegosalvianozup** [comment]
olá bom dia eu fiz o ajuste poderíamos finalizar ?

**Comment by coopoot** [comment]
olá bom dia eu fiz o ajuste poderíamos finalizar ?

**Comment by angelica-oliv** [comment]
Sim, podemos!!
Muito obrigada por revisar, e perdão pela demora no processo... :( 
Vi que vc já é writer no nosso Medium, então é só vc submeter o artigo para a nossa publicação! ;)

Obrigada pela contribuição! 🥳

**Comment by coopoot** [comment]
olá bom dia até o momento não recebi feedback se foi concluido a publicação

**Comment by angelica-oliv** [comment]
Olá, bom dia!
Acabei de aceitar a publicação...
Muito obrigada por contribuir! \o/

**Comment by angelica-oliv** [comment]
@all-contributors please add @coopoot for blog
