### ISSUE TITLE
Espresso — Como criar uma ViewAction customizada para um RatingBar - Haldny Santos

### ISSUE THREAD

**Issue by haldny** [androiddevbr/agenda-medium#154]
* **Autor:** Haldny Santos
* **Perfil no medium:** medium.com/@haldnysantos
* **Título do artigo:** Espresso — Como criar uma ViewAction customizada para um RatingBar
* **Descrição:** Gostaria de mostrar como podemos criar ViewAction customizada para tipos de "View" Android, podendo adicionar comportamentos que as APIs padrão do Espresso não fornece.

Link: https://medium.com/@haldnysantos/espresso-como-criar-uma-viewaction-customizada-para-um-ratingbar-710db3021e3c

**Comment by orafaaraujo** [comment]
Fala, @haldny 

Obrigado mais uma vez por mais uma contribuição em nosso Medium 🙌 
Deixei apenas 2 comentários no post:
Explicar um pouco melhor o que é um ViewAction na parte da introdução.
Deixar o nome dos componentes Android em itálico, para diferenciar do resto do texto.

Feito isso, já pode subemter no Medium que já publicamos  🎉 

Fico no aguardo,
Abraços

**Comment by haldny** [comment]
Oi @orafaaraujo,

Fiz os ajustes que você sugeriu no post, podes verificar?

Abraços,

**Comment by orafaaraujo** [comment]
Está tudo ok @haldny 

Pode submeter :D 

Abraços

**Comment by haldny** [comment]
Valeu @orafaaraujo.

publicado!

**Comment by orafaaraujo** [comment]
Muuuuito obrigado novamente, @haldny 

As portas estão sempre abertas :D
