### ISSUE TITLE
Melhorando a velocidade do desenvolvimento utilizando File Templates - João Gabriel

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#155]
Autor: João Gabriel
Perfil no medium: https://medium.com/@1jGabriel/
Título do artigo: Melhorando a velocidade do desenvolvimento utilizando File Templates
Descrição: Artigo mostrando como aumentar a velocidade no desenvolvimento utilizando File Templates
Link : https://medium.com/@1jGabriel/melhorando-a-velocidade-do-desenvolvimento-utilizando-file-templates-733d2a9303ff

**Comment by orafaaraujo** [comment]
Mais um artigo direto e objetivo, @1jGabriel 
Muito obrigado novamente! 🎉

**Comment by 1jGabriel** [comment]
Obrigado @orafaaraujo =)
