### ISSUE TITLE
O guia definitivo sobre dublês de teste no Android  (Parte 1 e 2) - Phellipe Silva

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#156]
* **Autor:** Phellipe Silva
* **Perfil no medium:** https://phellipealexandre.medium.com/ ou @phellipealexandre
* **Título do primeiro artigo:** O guia definitivo sobre dublês de teste no Android - Parte 1: Teoria
* **Título do segundo artigo:** O guia definitivo sobre dublês de teste no Android - Parte 2: Prática
* **Descrição:** Essa série com dois artigos busca explicar da forma mais fácil e direta possível um tema que é super complexo e que gera muitas dúvidas. A diferença entre todos os dublês de teste e como utilizá-los no Android. Eu tentei fazer uma curadoria com as melhores referências sobre o assunto para tentar deixar registrado aqui para a comunidade. A primeira parte abordamos a teoria de maneira agnostica à tecnologia e a segunda parte partimos para temas mais específicos do Android. Estou aberto a qualquer sugestão ou feedback em relação a escrita. Obrigado!

Link para primeira parte: https://medium.com/@phellipealexandre/o-guia-definitivo-sobre-dubl%C3%AAs-de-teste-no-android-parte-1-teoria-341441a91a4e

Link para segunda parte: https://medium.com/@phellipealexandre/o-guia-definitivo-sobre-dubl%C3%AAs-de-teste-no-android-parte-2-pr%C3%A1tica-233bf4f284f

**Comment by phellipealexandre** [comment]
Inspirado depois do papo no AndroidDevBrCast! Agora com explicações muito mais detalhadas!

**Comment by angelica-oliv** [comment]
Olá @phellipealexandre !!
Acabei de ler seus 2 artigos, parabéns o conteúdo está incrível!!
Quando puder, é só submeter para a nossa publicação que aprovamos. :)

Muuito obrigada por contribuir com a nossa comunidade! \o/\o/

**Comment by phellipealexandre** [comment]
Obrigado @angelica-oliv! Submissão feita!

**Comment by angelica-oliv** [comment]
Artigos publicados!!
Mais uma vez, obrigada! 🙌

**Comment by orafaaraujo** [comment]
@all-contributors please add @phellipealexandre for blog
