### ISSUE TITLE
Azure DevOps — CI/CD de aplicações Android para iniciantes — Parte 1 - Jeffersson Semin

### ISSUE THREAD

**Issue by JefferssonSemin** [androiddevbr/agenda-medium#157]
* **Autor:** Jeffersson Semin
* **Perfil no medium:** medium.com/@jefferssonsemin
* **Título do artigo:** Azure DevOps — CI/CD de aplicações Android para iniciantes — Parte 1
* **Descrição:** O objetivo real do artigo é contribuir ainda mais com a comunidade devops e android para que alguns problemas que tive particularmente, logo eu iniciante, um passo a passo de como gerar seu apk nesta primeira parte (CI), seguido de uma parte 2 com deploy na play store (CD).

**Comment by orafaaraujo** [comment]
Fala, @JefferssonSemin 
Bom dia, tudo bem?

É este o post?
https://jefferssonsemin.medium.com/azure-devops-ci-cd-de-aplica%C3%A7%C3%B5es-android-para-iniciantes-dbc964d8c7f1

Obrigado :D

**Comment by JefferssonSemin** [comment]
Opa, bom dia. Tudo certo!

Isso, é esse link mesmo.

Valeeeu 👊

**Comment by orafaaraujo** [comment]
Oi, @JefferssonSemin tudo bem?

Acabei de ler o seu post e ele está ótimo!
Te coloquei como _writer_ em nosso Medium, então quando tiver um tempinho, pode submeter por gentileza?

Obrigado e parabéns pelo post! 🎉

**Comment by JefferssonSemin** [comment]
Valeuu @orafaaraujo!!

Já submeti lá. Em breve postarei a parte 2 realizando o CD na play store.

Espero poder contribuir cada vez mais com a comunidade, abraço e obrigado pelo espaço.

**Comment by orafaaraujo** [comment]
Magina, @JefferssonSemin 
A gente que te agradece, as portas estarão abertas :)

Em nome da comunidade, muito obrigado! 🎉

**Comment by anacoimbrag** [comment]
@all-contributors please add @JefferssonSemin  for blog
