### ISSUE TITLE
Atividades dispensáveis e reutilizáveis no Android

### ISSUE THREAD

**Issue by gcherubini** [androiddevbr/agenda-medium#159]
**Autor:** Guilherme Cherubini
**Perfil no medium:** https://medium.com/@gcherubini
**Título do artigo:** Atividades dispensáveis e reutilizáveis no Android
**Descrição:** Gostaria de falar um pouco mais sobre como criar atividade reutilizáveis de forma nativa no Android. A idéia é trazer um exemplo prático de como isso pode ser desenvolvido, destacando a reutilização e centralização do código.

**Artigo para revisão:**
https://medium.com/@gcherubini/atividades-dispens%C3%A1veis-e-reutiliz%C3%A1veis-no-android-4284bd2898f8

Espero que possa ajudar a comunidade ! :D

**Comment by orafaaraujo** [comment]
Fala, @gcherubini, tudo bom?

Acabei de ler o seu post e só tenho uma sugestão: utilizar o https://gist.github.com/ para trechos de código. Isso deixará a leitura muito mais agradável :)  

Outro detalhe é que você precisará colocar uma imagem no header do post. Ela irá aparecer no feed da comunidade.
Você poderá encontrar alguma free em algum repositório de imagens, por example https://unsplash.com/

Do mais, parabéns pelo post. ficou bem legal!

Te coloquei como _writer_ em nosso Medium. Assim que fizer os ajustes, pode submeter que já publicamos. :) 

Em nome da comunidade, muito obrigado!

**Comment by gcherubini** [comment]
Maravilha @orafaaraujo. 

Agradeço pela revisão e disponiblidade de ser um writter da comunidade 👍 

Ajustei os trechos de código para **gist** conforme você mencionou.

Pretendo publicar 03/02/2021 o post.

Obrigado, e abraços!

**Comment by gcherubini** [comment]
Mandei a publicação pra review no medium @orafaaraujo 

Abraço!

**Comment by orafaaraujo** [comment]
Fala @gcherubini 

Publicado, mais uma vez muito obrigado pela contribuição, as portas estão abertas 🙌

Até!
