### ISSUE TITLE
Novo artigo: 7 Referências Técnicas para Desenvolvimento de Apps Android!

### ISSUE THREAD

**Issue by fredelinhares** [androiddevbr/agenda-medium#160]
Autor: Frederyk Linhares
Perfil no medium: https://frederyk.medium.com/7-refer%C3%AAncias-t%C3%A9cnicas-para-desenvolvimento-de-apps-android-764b60dac10d
Título do artigo: 7 Referências Técnicas para Desenvolvimento de Apps Android!
Descrição: Esse é o primeiro artigo com referências técnicas podem ajudara qualquer desenvolvedor Android a buscar conteúdo técnico de alta qualidade.

**Comment by orafaaraujo** [comment]
Oi, @fredelinhares Tudo bom?

Acabei de ler o seu post e tenho algumas sugestões. 
O objetivo da nossa comunidade é gerar e compartilhar conteúdo em português. A ideia do seu post é bacana e está de acordo com as nossas diretrizes, mas a maioria das recomendações que você compartilhou só tem conteúdo em inglês. Você acha que seria possível adicionar mais referências em português?

Obrigado pela compreensão. Qualquer dúvida é só falar com a gente.

Abraços!

**Comment by orafaaraujo** [comment]
Oi, @fredelinhares 

Outra dica que vou é você fazer uma versão de referencias brasileiras, ai podemos aproveitar os dois posts. O que acha?

Qualquer dúvida é so falar! ;)

**Comment by RBJUR** [comment]
Fala @fredelinhares blz?
Conversamos internamente no grupo de moderação, e entendemos que seu artigo não fere as regras para publicação em nosso medium, tendo em vista que é em Português. Entendemos que são suas referencias pessoais, e nao queremos que vc altere isso somente por nao ter muitos brasileiros na lista, quem sabe mais pra frente juntos a gente consiga trazer novas referencias brasileiras para nossa comunidade :)

**Comment by fredelinhares** [comment]
Olá Roque, tudo bom?

Então o artigo vai ser publicado? Ainda fiquei nessa dúvida...

Em seg., 1 de fev. de 2021 às 04:39, Roque Buarque Junior <
notifications@github.com> escreveu:

**Comment by RBJUR** [comment]
@fredelinhares tudo tranquilo por aqui, valeu por perguntar :)

Seu artigo vai ser publicado sim, te coloquei como `writer` em nosso Medium, quando quiser pode submeter.

Em nome da comunidade agradecemos sua contribuição!

**Comment by fredelinhares** [comment]
Obrigado Roque!

Em seg., 1 de fev. de 2021 às 13:01, Roque Buarque Junior <
notifications@github.com> escreveu:

**Comment by fredelinhares** [comment]
Olá Roque, tudo bem?

Gostaria de saber se o ADBR recebeu o artigo? (acabei de submeter o mesmo).
O link dele é esse aqui:

https://frederyk.medium.com/7-technical-references-for-android-apps-development-808912dcb273

Obrigado e desculpe--me o incômodo.

Abs

Em seg., 1 de fev. de 2021 às 13:01, Roque Buarque Junior <
notifications@github.com> escreveu:

**Comment by orafaaraujo** [comment]
Publicado, @fredelinhares 
Muito obrigado pela contribuição, as portas estão sempre abertas :)

**Comment by fredelinhares** [comment]
Obrigado

Em ter, 9 de fev de 2021 10:33, Rafael Araujo <notifications@github.com>
escreveu:
