### ISSUE TITLE
Simple Analytics with Kotlin - William Gouvea

### ISSUE THREAD

**Issue by amsterdatech** [androiddevbr/agenda-medium#161]
Autor: William Gouvea
Perfil no medium: https://medium.com/@williamgouvea
Título do artigo: Android Kotlin Analytics Made Simple!
Descrição: O artigo fala um pouco sobre o que ja passei durante o desenvolvimento de apps em diferentes mercados como fintechs, healthtechs , edutechs e OTT.  Em algum momento da carreira como Androider , aconteceu pelo menos uma vez um padrão de trocas e mais trocas de SDK de analytics por motivos de segurança, custo , flexibilidade ou mesmo solução interna para atender growth ou marketing e dependendo de como esses eventos foram implementados no legado , mudar isso ou migrar pra outra taxonomia pode ser algo realmente impossivel e erro prone devido ao acoplamento, falta de padrões entre outros problemas das soluções mais faceis.  A ideia é usar as ideias do SOLID e composição de forma a criar componentes com partes intercambeaveis que adicionam

O artigo ja foi publicado em inglês no ProAndroidDev,  devo traduzi-lo para português?

https://proandroiddev.com/android-kotlin-analytics-made-simple-c494caa0e787

Obrigado

**Comment by orafaaraujo** [comment]
Oi, @amsterdatech tudo bem?

Muito bacana, e é isso mesmo. Para publicarmos em nosso Medium você precisará fazer uma versnao em português. Consegue fazer isso para a gente?

Desde já, muito obrigado!

**Comment by amsterdatech** [comment]
Oi @orafaaraujo  , ja publiquei a versão em português, pode dar uma olhada?
https://williamgouvea.medium.com/simplificando-analytics-com-kotlin-no-android-bc4c5a1c5c4c
Obrigado!

**Comment by orafaaraujo** [comment]
Oi, @amsterdatech 
Tudo bem?

Acabei de revisar e deixei apenas um comentário sobre um typo.
Te coloquei como _writer_ em nosso Medium, quando tiver um tempinho pode submeter pra gente?

Parabéns pelo post e muito obrigado em nome da comunidade. :D 

Abraços

**Comment by amsterdatech** [comment]
Boa tarde

Já corrigi o typo e publiquei.

Aguardando o approve de vocês!

**Comment by orafaaraujo** [comment]
Fala, @amsterdatech 
Valeu demais!

Publicado!
As portas estão sempre abertas 😄

**Comment by anacoimbrag** [comment]
@all-contributors please add @amsterdatech  for blog
