### ISSUE TITLE
Como utilizar ListAdapter com Kotlin

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/agenda-medium#162]
**Autor:** Bruno Hensel
**Perfil no medium:** (Ainda não possuo) tenho um perfil no dev.to (https://dev.to/brunohensel)
**Título do artigo:** Como utilizar ListAdapter com Kotlin
**Descrição:** Gostaria de falar um pouco mais sobre como trabalhar com ListAdapter, quando começei na área esse era um tema que não conseguia absorver muito bem e demorei até entender. Acho que pode ajudar quem estiver começando.
Eu planejei começar a escrever posts no ano passado, e até agora só escrevi esse do Adapter. Depois de ver o meetup de ontem, tive o interesse de adaptá-lo para o português e submetê-lo para avalição. 
**Post:** https://dev.to/brunohensel/how-to-use-a-listadapter-2d2i

**Comment by orafaaraujo** [comment]
Oi, @brunohensel tudo bem?

Acho este tema interessantíssimo porque ainda há muito desenvolvedores que não conhecem o `ListAdapter` e eu sou fã 🤩 .

Mas para publicamos em nosso Medium, eu gostaria de te pedir para fazer uma versão em português, que é o foco de nosso Medium.

Poderia fazer por gentileza?

Desde já, muito obrigado. :)

**Comment by brunohensel** [comment]
Fala @orafaaraujo, beleza?

Sim, essa é a ideia, gerar conteúdo em português. Só mandei o link do artigo já publicado para uma análise prévia. 
Fiz agora os ajustes para publicação em português, aguardo seu feedback.

https://medium.com/@bruno.hensel/como-criar-um-listadapter-usando-kotlin-1f2259840ebc

**Comment by orafaaraujo** [comment]
Oi, @brunohensel 

Acabei de ler o post, tá bacana!
Deixei algumas sugestões de Gist, mas vi que no final você está usando, então fica ao seu critério atuliazar ou não. :) 

Te coloquei como _writer_ em nosso Medium, então quando quiser pode submeter que já publicamos, tudo bem?

Em nome da comunidade, muito obrigado por sua contribuição. 🎉

Abraços

**Comment by brunohensel** [comment]
Valeu @orafaaraujo pela rapidez. Adicionei mais alguns Gists e também coloquei uma conclusão ao final. Vou dar uma última olhada e já submeto. Valeu!

**Comment by orafaaraujo** [comment]
Publicado, @brunohensel 

Valeu demais!
As portas estão sempre abertas :)

**Comment by anacoimbrag** [comment]
@all-contributors please add @brunohensel  for blog
