### ISSUE TITLE
Transformando um APP Android em iOS com KMM - Jean Patricio

### ISSUE THREAD

**Issue by jeancsanchez** [androiddevbr/agenda-medium#164]
Autor: Jean Patricio
Perfil no medium: https://jeancsanchez.medium.com
Título do artigo: Transformando um APP Android em iOS com KMM - Um exemplo real.
Descrição: Gostaria de falar da minha experiência ao migrar uma aplicação real em Android para o iOS utilizando o Kotlin Multiplatform.

**Comment by orafaaraujo** [comment]
Fala, @jeancsanchez , tudo bem?

Cara, acabei de ler o seu post e ficou muito bom! KMM é algo que afzem os olhos dos devs brilharem. 🤩

Te coloquei como _writer_ em nosso Medium, quando tiver um tempinho pod subemter?
Assim que o fizer, a gente publica a anuncia. :) 

Obrigado em nome da comunidade e parabéns pelo post. 🎉

**Comment by jeancsanchez** [comment]
@orafaaraujo  Muito obrigado! Fico feliz que tenha gostado. Vou submenter \o/

**Comment by orafaaraujo** [comment]
Publicado!

🎉

**Comment by anacoimbrag** [comment]
@all-contributors please add @jeancsanchez  for blog
