### ISSUE TITLE
Listas paginadas com Jetpack Compose - João Gabriel

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#165]
* **Autor:** João Gabriel
* **Perfil no medium:** 1jgabriel.medium.com
* **Título do artigo:** Criando aplicativos com Firebase
* **Descrição:** Artigo demonstrando como utilizar a biblioteca paging juntamente com o Jetpack Compose

https://1jgabriel.medium.com/paging-v3-jetpack-compose-2899a6877bef

**Comment by orafaaraujo** [comment]
Fala, @1jGabriel Tudo bom?

Acabei de ler o post e você manteve a qualidade dos outros que você já publicou hahahaha 🎉
Obrigado pela submissão, já vou publicar em nosso Medium :) 

Abraços!

**Comment by 1jGabriel** [comment]
Muito Obrigado @orafaaraujo, pelo feedback e por permitir a publicação.

Abraços!
