### ISSUE TITLE
Diferença entre Flatmap, ConcatMap & SwitchMap RxJava

### ISSUE THREAD

**Issue by RBJUR** [androiddevbr/agenda-medium#166]
Autor: Roque Buarque
Perfil no medium: medium.com/@roque.buarque/
Título do artigo: Diferença entre Flatmap, ConcatMap & SwitchMap RxJava
Descrição: A ideia do meu artigo é demonstrar a diferença entre alguns dos operadores do RxJava. 

Link do post: https://medium.com/@roque.buarque/diferen%C3%A7a-entre-flatmap-switchmap-e-concatmap-rxjava-e517d420a7a2

**Comment by orafaaraujo** [comment]
Show de bola, Roque!

Uma sugestão: os mesmo conceitos usando `Flow`, o que acha? :)

**Comment by RBJUR** [comment]
Ta no radar :)

**Comment by RBJUR** [comment]
@orafaaraujo algum ajuste que preciso fazer?

**Comment by angelica-oliv** [comment]
Olá @RBJUR !!
Tá ótimo o artigo, parabéns!!
Bem explicado e simples de entender, adorei a sugestão do @orafaaraujo 👀  rs

Obrigada por além de ajudar na moderação, também compartilhar por aqui! 
Agora, é só submeter no nosso Medium que já aprovamos! 😃

**Comment by RBJUR** [comment]
Oi @angelica-oliv 
Que bom que gostou do artigo :) 
A sugestão de artigos sobre flow está no radar, não vou demorar muito para começar. 
Eu quem agradeço, estar perto de um time de moderadores que temos no ADBR é um privilégio, só tem gente massa.
Já submeti o artigo e que venham os próximos.

**Comment by angelica-oliv** [comment]
@all-contributors please add @RBJUR for blog
