### ISSUE TITLE
RxJava e Kotlin #1

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/agenda-medium#178]
Autor: Bruno Hensel
Perfil no medium: medium.com/@bruno.hensel
Título do artigo: RxJava e Kotlin #1
Subtítulo: Entendendo o que é RxJava e como criar Observables
Descrição: Muito embora a novidade seja o Flow, como ferramenta para tornar nosso código reativo a eventos, acredito que muitas vagas ainda exijam conhecimentos em RxJava. Dada falta de conteúdo em português sobre o assunto, gostaria de iniciar uma série sobre o tema.
Aqui está o link para visualização do rascunho: https://medium.com/@bruno.hensel/rxjava-and-kotlin-1-ca6c20fb389f

**Comment by RBJUR** [comment]
Fala @brunohensel blz?

Parabéns pelo artigo, muito bom ter vc novamente submetendo artigo para nossa comunidade.
Cara adicionei alguns comentários privados ao seu artigo, caso tenha alguma dúvida sobre só chamar.
Assim que os ajustes forem feitos, seu artigo estará pronto para publicação em nosso medium.

Abraços e ate mais
Roque

**Comment by brunohensel** [comment]
Fala meu caro @RBJUR, muito obrigado pelo review. Bem notado a parada da nulabilidade entre o Rx1 e os subsequentes, não havia me atentado. Fiz alguns ajustes que vc mencionou, e submeti o post.

Um abraço.
Bruno

**Comment by RBJUR** [comment]
Show de bola @brunohensel 

Eu quem agradeço por sua contribuição, tamo junto.

Abraço 
Roque
