### ISSUE TITLE
15/08/16 - Configurando múltiplos arquivos Java e recursos usando flavor no  Gradle

### ISSUE THREAD

**Issue by thiagoolsilva** [androiddevbr/agenda-medium#18]
* **Autor:** Thiago lopes da silva
* **Data escolhida:** 15/08/16
* **Título do artigo:** Configurando múltiplos arquivos Java e recursos usando flavor no  Gradle
* **Descrição:** Gostaria de falar um pouco mais sobre como configurar múltiplos builds no android. A idéia do meu artigo é falar sobre como usar a estratégia de múltiplos builds usando diferentes arquivos javas para cada tipo de produto, assim como explicar a estratégia de usar múltiplos recursos da pasta res/ do android para diferentes tipos de produtos. Hoje tenho este post escrito em inglês no meu blog pessoal. Caso a comunidade tenha interesse , eu posso traduzi-lo para PT e colocar aqui.

**Comment by orafaaraujo** [comment]
Olá Thiago,
Já estou com este tema!

Estou quase finalizando... até a data estará pronto :-)

**Comment by thiagoolsilva** [comment]
Opa.. Acabei não vendo. Vou então trabalhar com outro tema. Abraços !

**Comment by thiagoolsilva** [comment]
Acredito que podemos fechar a issue
