### ISSUE TITLE
Threads, Handler, Looper e Message Queue - Jeziel Lago

### ISSUE THREAD

**Issue by jeziellago** [androiddevbr/agenda-medium#180]
* **Autor:** Jeziel Lago
* **Perfil no medium:** https://jeziellago.medium.com/
* **Título do artigo:** Threads, Handler, Looper e Message Queue (Parte 1 e Parte 2)
* **Descrição:** São dois posts (partes 1 e 2) com o objetivo de explicar brevemente o que são Threads, Handler, Looper e Message Queue, como eles funcionam e como trabalham juntos.

__Links dos posts__: 
- [Parte 1](https://jeziellago.medium.com/threads-handler-looper-e-message-queue-parte-1-thread-635364a0697d)
- [Parte 2](https://jeziellago.medium.com/threads-handler-looper-e-message-queue-parte-2-3711ee9d1b4)

**Comment by angelica-oliv** [comment]
@jeziellago muito obrigada por contribuir! :)
Acabei de ler a Parte 1, fiz apenas 2 comentários, com relação a apenas detalhes mesmo.
Parabéns pelo artigo está explicando tudo de forma bem simples de se entender!!!
Ainda hoje pretendo dar uma olhada na parte 2. 

Se puder revisar os comentários, e qualquer dúvida, pode me falar! ;)

**Comment by angelica-oliv** [comment]
@jeziellago acabei de ler a parte 2. 🔝 
Realmente, muito bom!
Obrigada mais uma vez!!
Coloquei mais alguns comentários, quando puder dê uma olhada, por favor. :)
Depois de rever e ajustar o que achar necessário, já pode submeter para o Medium da nossa comunidade! ;)
Apenas me avise aqui para que eu aceite lá no Medium!

**Comment by jeziellago** [comment]
@angelica-oliv Muito obrigado pela revisão!
Fiz os ajustes solicitados nos dois posts 😅
Não tenho certeza mas acredito que preciso ser adicionado como writer no blog para fazer a submissão 👀.

**Comment by angelica-oliv** [comment]
Ah, desculpa @jeziellago!
Já te adicionei, agora deve conseguir submeter! =D

**Comment by jeziellago** [comment]
> Ah, desculpa @jeziellago!
> Já te adicionei, agora deve conseguir submeter! =D

Show! Submeti :D

**Comment by angelica-oliv** [comment]
@all-contributors please add @jeziellago for blog
