### ISSUE TITLE
RxJava and Kotlin #2

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/agenda-medium#181]
Autor: Bruno Hensel
Perfil no medium: medium.com/@bruno.hensel
Título do artigo: RxJava and Kotlin #2
Descrição: Esse é o segundo capítulo sobre RxJava e Kotlin onde abordarei conceitos como subjects e como encerrar manualente uma stream.
draft link: https://medium.com/@bruno.hensel/rxjava-and-kotlin-2-e7549f3de4ad

**Comment by RBJUR** [comment]
Fala @brunohensel blz?

Revisei seu artigo e adicionei  alguns pontos para serem ajustatos, qualquer dúvida só chamar.

**Comment by brunohensel** [comment]
Boas dicas @RBJUR, fiz alguns ajustes apontados. 
Valeu.

**Comment by RBJUR** [comment]
Boa, então quando quiser pode submeter que já publicamos 👍 
Valeu pela contribuição e até a próxima.
