### ISSUE TITLE
Testando sua aplicação: Testando APIs do retrofit com MockWebServer - Thiago Souto

### ISSUE THREAD

**Issue by othiagosouto** [androiddevbr/agenda-medium#182]
* **Autor:** Thiago Souto
* **Perfil no medium:** https://medium.com/@othiagosouto
* **Título do artigo:** Testando sua aplicação: Testando APIs do retrofit com MockWebServer
* **Descrição:** Post puxa um pouco sobre a importância de testes e como testar as apis do retrofit com o MockWebServer
* **Draft link:** https://medium.com/@othiagosouto/testando-apis-do-retrofit-com-mockwebserver-80bc80e543ce

**Comment by othiagosouto** [comment]
@RBJUR acabei de submeter as alterações!

**Comment by RBJUR** [comment]
Boa, vi aqui que vc fez as alterações.
Vi que vc ja esta como `writer`  em nosso medium, qnd quiser é só submeter seu artigo que a gente já aprovamos! 
Abração até a próxima.

**Comment by othiagosouto** [comment]
submetido!
