### ISSUE TITLE
Testando sua aplicação: Criando repositórios testáveis - Thiago Souto

### ISSUE THREAD

**Issue by othiagosouto** [androiddevbr/agenda-medium#183]
* **Autor:** Thiago Souto
* **Perfil no medium:** https://medium.com/@othiagosouto
* **Título do artigo:** Testando sua aplicação: Criando repositórios testáveis
* **Descrição:** Post explica um pouco sobre como estruturar e testar o repository/camada de acesso a dados
* **Draft link:** https://medium.com/@othiagosouto/criando-reposit%C3%B3rios-test%C3%A1veis-558049e25d2b

**Comment by RBJUR** [comment]
@othiagosouto conforme conversamos vou segurar esse artigo para o primeiro anuncio de Março.

**Comment by RBJUR** [comment]
@othiagosouto muito obrigado por mais um artigo, muita qualidade, gostei bastante.
Levantei alguns pontos, se tiver alguma dúvida só chamar.

**Comment by othiagosouto** [comment]
@RBJUR, valeu pelo feedback!

Fiz os ajustes, teria como dar uma olhada novamente?

**Comment by RBJUR** [comment]
Fala @othiagosouto blz?

Cara acho que fui mal interpretado em uma sugestão que deixe, muito pq eu coloquei pouca info pra vc tbm.

Comentei la nessa sugestão, qualquer coisa da um toque.

Abs.

**Comment by RBJUR** [comment]
@othiagosouto quando quiser pode submeter

**Comment by RBJUR** [comment]
Artigo publicado

Muito obrigado pela contribuição.
