### ISSUE TITLE
Flow timeout - Roque Buarque

### ISSUE THREAD

**Issue by RBJUR** [androiddevbr/agenda-medium#185]
* **Autor:** Roque Buarque
* **Perfil no medium:** https://medium.com/@roque.buarque
* **Título do artigo:** Flow timeout
* **Descrição:** Gostaria de abordar um pouco de programação reative com flow e compartilhar uma experiencia que tive ao descobrir que flow não vem com operador timeout, mostrar como fiz para implementar isso usando coroutines, esse é o primeiro de dois artigos sobre o tema flow/timeout.
* **Artigo: https://medium.com/@roque.buarque/flow-timeout-ce20c171b017**

**Comment by angelica-oliv** [comment]
Olá @RBJUR !!
Acabei de ler seu artigo, muito bom mais uma vez!! :)

Apenas coloquei no comentário alguns detalhes, quando puder revisar...
Depois disso é só publicar!
Novamente, obrigada por compartilhar!!! \o/

**Comment by RBJUR** [comment]
@angelica-oliv obrigado pelo review

Apliquei as alteraçōes solicitadas e vou publicar.
Até a próxima :)
