### ISSUE TITLE
Como entrei para o programa Google Developers Experts - Angélica Oliveira

### ISSUE THREAD

**Issue by angelica-oliv** [androiddevbr/agenda-medium#186]
* **Autor:** Angélica Oliveira
* **Perfil no medium:** medium.com/@angelica-oliveira
* **Título do artigo:** Como entrei para o programa Google Developers Experts
* **Descrição:** Nesse artigo compartilho parte de minha jornada como desenvolvedora Android, e falo como é o processo para fazer parte do programa Google Developers Experts, dando dicas para as pessoas que desejem fazer parte do programa. Essa é a versão em PT-BR do artigo que publiquei no Medium do Google Developer Experts.

Link do Artigo: https://medium.com/@angelica-oliveira/como-entrei-para-o-programa-google-developers-experts-b8954edfb47f
Link do Artigo em Inglês: https://medium.com/google-developer-experts/how-i-joined-the-google-developers-experts-program-52428d2c2d06

**Comment by RBJUR** [comment]
Oi @angelica-oliv gostei muito do seu artigo, já havia lido ele em inglês e revisar em português foi bem interessante.

Eu levantei apenas um comentário :) 
Quando quiser pode submeter.

Obrigado pela contribuição e até a próxima.
