### ISSUE TITLE
Builder Inference annotation - João Victor Oliveira

### ISSUE THREAD

**Issue by jaozinfs** [androiddevbr/agenda-medium#188]
* **Autor:** João Victor Oliveira
* **Perfil no medium:** medium.com/@joaofgz123
* **Título do artigo:** Builder Inference annotation
* **Descrição:** Gostaria de falar um pouco mais sobre alguns benefícios do Kotlin que talvez muitos ainda não conheçam, como por exemplo a anotação BuilderInference.

Link do Artigo: https://medium.com/@joaofgz123/builder-inference-annotation-f5582503f22

**Comment by orafaaraujo** [comment]
Fala, @jaozinfs 

Só uma pequena correção: deixar ide em maiúsculo, do resto está ótimo :) 

Obrigado pela contribuição!

**Comment by jaozinfs** [comment]
@orafaaraujo Opa,
Alterei para maiúsculo, muito obrigado !

**Comment by orafaaraujo** [comment]
Publicado!

Em nome da comunidade, muito obrigado @jaozinfs 
As portas estão abertas 🙌
