### ISSUE TITLE
RxJava and Kotlin #3 - Bruno Hensel

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/agenda-medium#189]
* **Autor:** Bruno Hensel
* **Perfil no medium:** https://bruno-hensel.medium.com/
* **Título do artigo:** RxJava and Kotlin #3 Separando o joio do trigo com os filtering operators do RxJava.
* **Descrição:** Dando sequencia na saga do RxJava, nesse novo posto vou abordar os operadores de filtro e como utilizá-los. Link do artigo: https://bruno-hensel.medium.com/rxjava-and-kotlin-3-17fc46151d35

**Comment by RBJUR** [comment]
Fala @brunohensel blz?

Muito bacana sua serie de artigos, apontei algumas coisinhas, assim que resolvidas pode submeter.

Qualquer dúvida só chamar.

Abs

**Comment by brunohensel** [comment]
Obrigado pelo review, artigo submetido.

Abs

**Comment by RBJUR** [comment]
Valeu @brunohensel 

Muito obrigado novamente por mais uma contribuição para a comunidade.

Abs
Roque
