### ISSUE TITLE
21/07/2016 - Estrutura de Resources Alternativa para Projetos Android

### ISSUE THREAD

**Issue by marcellogalhardo** [androiddevbr/agenda-medium#19]
* **Autor:** Marcello Galhardo
* **Data escolhida:** 00/00/00 - Já está feito! :+1: 
* **Título do artigo:** Estrutura de Resources Alternativa para Projetos
* **Descrição:** https://medium.com/@marcellogalhardo/estrutura-de-resources-para-android-alternativa-2869d99a41f7#.co3yaehgr

**Comment by davidtcdeveloper** [comment]
Publicado: 
https://medium.com/android-dev-br/estrutura-de-resources-para-android-alternativa-2869d99a41f7#.caa2sf85u 
:smile:
