### ISSUE TITLE
Complexidade ciclomática no Android - Arildo Borges Jr

### ISSUE THREAD

**Issue by arildojr7** [androiddevbr/agenda-medium#190]
* **Autor:** Arildo Borges Jr
* **Perfil no medium:** medium.com/@arildojr
* **Título do artigo:** Complexidade ciclomática no Android
* **Link para o artigo:** https://medium.com/@arildojr/complexidade-ciclom%C3%A1tica-no-android-e69fd4362bdd

Obs.: artigo não foi publicado ainda

**Comment by RBJUR** [comment]
@arildojr7 gostei bastante do tema escolhido, artigo ta show de bola.

Quando quiser pode submeter que irei aprovar em seguida. 

Obrigado por sua contribuição
Abs

**Comment by arildojr7** [comment]
@RBJUR Opa, muito obrigado :D . Acabei de submeter. Abração

**Comment by arildojr7** [comment]
@RBJUR Boa tarde, eu enviei pelo `Add to Publication`. Está correto? Abraços

**Comment by RBJUR** [comment]
@arildojr7 seu artigo foi publicado, em breve iremos anunciar na comunidade.

Obrigado por sua contribuição.

Abs
Roque
