### ISSUE TITLE
Simplificando Analytics com Kotlin no Android! — Part 2 Reportando Crashes da Aplicação - William Gouvea

### ISSUE THREAD

**Issue by amsterdatech** [androiddevbr/agenda-medium#191]
Autor: William Gouvea
Perfil no medium: https://medium.com/@williamgouvea
Título do artigo: Simplificando Analytics com Kotlin no Android! — Part 2 Reportando Crashes da Aplicação
Descrição: O artigo fala um pouco mais sobre coleta de dados no Android com Kotlin focando nos relatorios de crash, mostrando como as ferramentas do mercado atuam e como customizar este processo se necessario.

O artigo ja foi publicado em inglês no ProAndroidDev, segue tambem abaixo link para um versão em portugues.

- https://proandroiddev.com/android-kotlin-analytics-part-2-crash-reporter-1703432e6dcd

- https://williamgouvea.medium.com/simplificando-analytics-com-kotlin-no-android-part-2-reportando-crashes-da-aplica%C3%A7%C3%A3o-c35b823e88c8

Obrigado

**Comment by orafaaraujo** [comment]
Fala, @amsterdatech 

Tudo bem?
O post está bacana! Só faltou a tradução de uma linha, deixei um comentário falando onde. Quando alterar, me diga quer já publicamos o post e anunciamos, beleza?

Obrigado :D

**Comment by amsterdatech** [comment]
Fala @orafaaraujo ,

Vlw pela  leitura e pelo feedback. Ja alterei  e salvei, aguardo a publicação

Obrigado 👍

**Comment by orafaaraujo** [comment]
Valeu mais uma vez, @amsterdatech 

Publicado 🚀
