### ISSUE TITLE
Constraint Layout com Jetpack Compose - João Gabriel

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/agenda-medium#192]
* **Autor:** João Gabriel
* **Perfil no medium:** 1jgabriel.medium.com
* **Título do artigo:** Constraint Layout com Jetpack Compose
* **Descrição:** 
https://1jgabriel.medium.com/constraint-layout-com-compose-8928d4dbdf
Artigo demonstrando como utilizar Constraint Layouts com Jetpack Compose e um comparativo com AndroidX

**Comment by orafaaraujo** [comment]
Fala, @1jGabriel 
Beleza?

Mais um artigo show de bola, sem comentários 😎
Já publiquei em noosso Meidum, tudoo bem?

Obrigado mais uma vez em nome da comunidade 🙌
