### ISSUE TITLE
Testes Instrumentados: tipos de teste e como são executados. - Natan Ximenes

### ISSUE THREAD

**Issue by Senemix29** [androiddevbr/agenda-medium#193]
* **Autor:** Natan Ximenes
* **Perfil no medium:** https://medium.com/@natanximenes
* **Título do artigo:** Testes Instrumentados: tipos de teste e como são executados.
* **Descrição:** Nesse post, explico, de forma teórica, como funciona um teste instrumentado, suas ramificações e sua importancia no nosso desenvolvimento.
* **Artigo:** https://medium.com/@natanximenes/testes-instrumentados-tipos-de-teste-e-como-s%C3%A3o-executados-1f13a8cfe4c4

**Comment by orafaaraujo** [comment]
Oi, @Senemix29 
Tudo bem?

Acabei de ler o seu post e tudo show!
Te coloquei como writer, quando tiver um tempinho é só submeter

Obrigado!

**Comment by Senemix29** [comment]
Opa @orafaaraujo, valeu! Ja submeti!

**Comment by orafaaraujo** [comment]
@all-contributors please add @Senemix29 for blog
