### ISSUE TITLE
Canal quente e Canal frio - João Victor

### ISSUE THREAD

**Issue by jaozinfs** [androiddevbr/agenda-medium#194]
* **Autor:** João Victor Chaves de Oliveira
* **Perfil no medium:** medium.com/@joaofgz123
* **Título do artigo:** Canal quente e Canal frio
* **Descrição:** Então chega um ponto que você não sabe mais a diferença de canais. Com tantas opções disponível atualmente em linguagens modernas eu não te julgaria.
* **Link:** [https://medium.com/@joaofgz123/canal-quente-e-canal-frio-9d96c7367f72](url)

**Comment by orafaaraujo** [comment]
Publicado, obrigado mais uma vez, @jaozinfs 🙌
