### ISSUE TITLE
Activity Result APIs: Como tratar permissões com o Android Jetpack - Paulo Víctor Corazza

### ISSUE THREAD

**Issue by pvcorazza** [androiddevbr/agenda-medium#195]
* **Autor:** Paulo Víctor Corazza
* **Perfil no medium:** medium.com/@pvcorazza
* **Título do artigo:** Activity Result APIs: Como tratar permissões com o Android Jetpack
* **Descrição:** A ideia do artigo é demonstrar através de exemplos como solicitar permissões através das APIs de Activity Results, presentes do AndroidX. Achei interessante abordar sobre o tema pois as APIs se tornaram estáveis desde fevereiro e atualmente é a forma recomendada pelo Google de tratar as permissões em tempo de execução de acordo com a documentação.
* **Link:** https://pvcorazza.medium.com/uma-nova-forma-de-solicitar-permissoes-com-o-android-jetpack-activity-result-apis-404a7a5cd460

**Comment by orafaaraujo** [comment]
Fala, @pvcorazza 

Muito bom o artigo, acabei de revisar e já te coloquei como writer em nosso Medium.

Quando tiver um tempinho, pode submeter pra gente?

Obrigado em nome da comunidade!

**Comment by pvcorazza** [comment]
Obrigado, @orafaaraujo. Acabei de submeter.

**Comment by orafaaraujo** [comment]
Publicadoo, @pvcorazza 

Muito obrigado pela contribuição, me breve faremos o anuncio nas redes sociais.
Você tem twitter? Aí podemos te citar por lá

Até!

**Comment by orafaaraujo** [comment]
@all-contributors please add @pvcorazza for blog

**Comment by pvcorazza** [comment]
Valeu @orafaaraujo. Infelizmente Twitter eu não tenho 🙁
