### ISSUE TITLE
RxJava and Kotlin #4 - Bruno Hensel

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/agenda-medium#197]
* **Autor:** Bruno Hensel
* **Perfil no medium:** https://bruno-hensel.medium.com/
* **Título do artigo:** RxJava and Kotlin #4 - Transformando objetos dentro de uma mesma chain
* **Descrição:** Episódio 4 da série sobre RxJava onde abordarei os operadores que transformam elementos emitidos. 
* **Link:** https://medium.com/@bruno-hensel/rxjava-and-kotlin-4-433c0a570e61

**Comment by orafaaraujo** [comment]
Fala, Bruno, tudo bem?

O post está bem bacana, só tenho uma sugestão quanto a formatação: deixar as palavras em inglês (as que você acha que fazem sentido) ou paralvras reservadas em itálicos, para destacar a atenção nelas.
Exemplo de palavras: Observable<ResponseDTO>, FlatMap, BehaviorSubject, amphibians etc.

E quando for citar um código no meio do texto, use a formatação em quotes `como esta daqui` para destacá-las, assim como fez em `mammal.type.onNext("Sheep")`.

E por último, tirar o itálico de partes que não fazem muito sentido, por exemplo na definição de `SwitchMap`.

Sendo assim, já pode subemter que quando realizar as alterações eu já publico também. :) 

Muito obrigado por mais uma contribuição! 🙌

**Comment by orafaaraujo** [comment]
Oi, @brunohensel 

Alguma novidade sobre as alterações e submissão?
Qualquer coisa é só nos pingar

Obrigado! 😉

**Comment by brunohensel** [comment]
Fala @orafaaraujo. Desculpa a demora, várias coisas aconteceram nessas últimas semanas que me impediram de aplicar as sugestões.

Revisei o artigo e apliquei o que disse e já submeti o artigo.

Valeu pela revisão.

**Comment by orafaaraujo** [comment]
Publicado!

Obrigado mais uma vez :)
