### ISSUE TITLE
30/05/16 - Primeiros Passos com Realm - Douglas Drumond

### ISSUE THREAD

**Issue by douglasdrumond** [androiddevbr/agenda-medium#2]
* **Autor:** Douglas Drumond
* **Data escolhida:** 09/05/16
* **Título do artigo:** Primeiros Passos com Realm
* **Descrição:** A ideia do artigo é apresentar o Realm como alternativa ao SQLite e como configurar e usar o Realm no seu aplicativo.

**Comment by walmyrcarvalho** [comment]
Muito bom o tópico, quero muito ler! :)

**Comment by walmyrcarvalho** [comment]
@douglasdrumond Você acha que o tema é iniciante ou intermediário? Estou colocando umas labels pra identificar :)

**Comment by douglasdrumond** [comment]
Acho que está mais próximo de intermediário.

**Comment by walmyrcarvalho** [comment]
Data atualizada pois o post foi postergado pro dia 30. :)

**Comment by douglasdrumond** [comment]
https://medium.com/@douglasdrumond/inicia%C3%A7%C3%A3o-ao-realm-b7624e380194#.7y3eg95za

Preciso atualizar, tem algumas mudanças no Realm. O post não está errado, mas existem opções, por exemplo, em vez de estender `RealmObject`, é possível também implementar a interface `RealmModel`. Isso é recente.

**Comment by davidtcdeveloper** [comment]
@douglasdrumond: O post esta excelente, muito bom mesmo. Fiz uma ou duas sugestoes so por preciosismo mesmo.
Podes adicionar a publicacao? Dai ja fica preparado para publicar :)
