### ISSUE TITLE
10/10/16 - Android Wear - Introdução ao desenvolvimento com o emulador.  -  Wellington Barbosa

### ISSUE THREAD

**Issue by wellingtonmb88** [androiddevbr/agenda-medium#20]
- **Autor:** Wellington Barbosa
- **Data escolhida:** 10/10/16
- **Título do artigo:** Android Wear - Introdução ao desenvolvimento com o emulador.
- **Descrição:**Gostaria de falar dos primeiros passos para iniciar o desenvolvimento com Android Wear utilizando o emulador. Seria um guia para ajudar o desenvolvedor a configurar um projeto simples de notificação, enviada do celular físico/emulador para um emulador do Android Wear.

**Comment by walmyrcarvalho** [comment]
@wellingtonmb88 Muito bom, obrigado pela submissão! Quando tiver algo que queira mostrar pra gente, só submeter no publication do Android Dev BR que a gente olha! :)

**Comment by wellingtonmb88** [comment]
@walmyrcarvalho @davidtcdeveloper Fala pessoal conseguir finalizar meu artigo, se poderem dar uma olhada e passar alguns feedbacks serei muito grato!
https://medium.com/@wellingtonmb88/a00c3c82b15b

**Comment by davidtcdeveloper** [comment]
Maravilha, veremos assim que possivel @wellingtonmb88, obrigado.

**Comment by wellingtonmb88** [comment]
@walmyrcarvalho @davidtcdeveloper Fala pessoal algum feedback?

**Comment by walmyrcarvalho** [comment]
Publicado: https://medium.com/android-dev-br/android-wear-introdu%C3%A7%C3%A3o-ao-desenvolvimento-com-o-emulador-a00c3c82b15b#.azgpw46u5
