### ISSUE TITLE
Tradução de Design System: como fazer isso com Jetpack Compose - Pablo Baldez

### ISSUE THREAD

**Issue by pablobaldez** [androiddevbr/agenda-medium#200]
* **Autor:** Pablo Baldez
* **Perfil no medium:** medium.com/@pablo-baldez
* **Título do artigo:** Tradução de Design System: como fazer isso com Jetpack Compose
* **Descrição:** A ideia é explicar como abstraímos o design system da empresa em que trabalho para configurar o Material Design do app. Trago a modelagem da solução, explico como design systems tendem a ser diferentes e como abstraí essas diferenças para fazer tudo de forma elegante
* **link:** https://medium.com/warren-tech/tradu%C3%A7%C3%A3o-de-design-system-como-fazer-isso-com-jetpack-compose-66b94abe376c

**Comment by orafaaraujo** [comment]
O mesmo do outro post, precisamos dele em sua conta pessoal.

**Comment by orafaaraujo** [comment]
Olá, @pablobaldez 

Alguma novidade?
Obrigado!

**Comment by pablobaldez** [comment]
Oi @orafaaraujo 
Vou remover as publicações da Warren Tech e publicar apenas na androiddevbr. Acredito que terá mais vsibilidade e não será preciso duplicar nada.

Pretendo fazer isso entre hoje ou amanhã. Tudo bem pra vocês?

**Comment by pablobaldez** [comment]
Oi @orafaaraujo 
Escolhi remover esse post do Warren Tech. Não gostei muito da ideia de ter posts duplicados, então optei por deixar publicado apenas para vocês.
Preciso fazer algo a mais?

**Comment by pablobaldez** [comment]
oi @orafaaraujo alguma novidade? (agora eu quem pergunto hehe)

Abraço!

**Comment by orafaaraujo** [comment]
Oi, @pablobaldez 

Mals a demora, vou olhar essa semana e te passo um retorno 

Obrigado!

**Comment by orafaaraujo** [comment]
Oi, @pablobaldez 

Li o post e está ótimo.
Pode submeter em nosso Medium?

Obrigado novamente!

**Comment by pablobaldez** [comment]
Feito!
