### ISSUE TITLE
Design system com Jetpack Compose: Criando componentes - Pablo Baldez

### ISSUE THREAD

**Issue by pablobaldez** [androiddevbr/agenda-medium#201]
* **Autor:** Pablo Baldez
* **Perfil no medium:** medium.com/@pablo-baldez
* **Título do artigo:** Design system com Jetpack Compose: Criando componentes
* **Descrição:** Explico como utilizamos a ferramenta Jetpack Compose para criar componentes customizáveis 
* **link**: https://medium.com/warren-tech/design-system-com-jetpack-compose-criando-componentes-ea82884957f9

**Comment by orafaaraujo** [comment]
Fala, @pablobaldez 
Tudo bem?

Acabei de revisar este post e está pronto para ser publicado cm nosso Medium 🚀

Mas, notei que você já o publicou no Medium do Warren Tech, certo? 
Sendo assim, acho que não é possível republicar em nosso. Se for possível, provavelmente ele deixará de existir no Warren Tech.

Minha sugestão é criar outro post e copiar todo o contéudo. Aí você submete este novo post, o que acha?

Já te coloquei como wirter em nosso Medium

Muito obrigado!

**Comment by pablobaldez** [comment]
Oi @orafaaraujo 
Como comentei na outra issue, esses posts foram removidos do Warren Tech

**Comment by orafaaraujo** [comment]
Oi, @pablobaldez 
Pode submeter também!

Obrigado mais uma vez :)

**Comment by pablobaldez** [comment]
Feito!

**Comment by orafaaraujo** [comment]
Ambos publicado, muito obrigado! 

@all-contributors please add @pablobaldez for blog
