### ISSUE TITLE
Metodologias Ágeis: Nem tudo na vida deve ser eXtreme GoHorse - Diego Braun da Cunha

### ISSUE THREAD

**Issue by diegocunhawarren** [androiddevbr/agenda-medium#202]
* **Autor:** Diego Braun da Cunha
* **Perfil no medium:** medium.com/@diego-cunha
* **Título do artigo:** Metodologias Ágeis: Nem tudo na vida deve ser eXtreme GoHorse
* **Descrição:** Falar um pouco sobre metodologias ágeis e desmitificar que devemos seguir tudo como está escrito em pedra.
* **Link:** https://medium.com/warren-tech/metodologias-%C3%A1geis-nem-tudo-na-vida-deve-ser-extreme-gohorse-de1e2a2db51d

**Comment by orafaaraujo** [comment]
Olá, @diegocunhawarren 
Tudo bem?

Li o seu post e notei que não menciona muito o desenvolvimento android, que é o foco da nossa comunidade. 
Sendo assim, aconselho você a incrementar com algum comentário sobre desenvolvimento mobile e/ou principalmente Android. Caso contrário não podemos publicar em nosso Medium.

Abraços!

**Comment by diegocunhawarren** [comment]
Achei que podiamos postar sobre outros assuntos tech, pode fechar essa issue então :D
