### ISSUE TITLE
In-App Updates: Como gerenciar updates no Android - Lucas Wottrich

### ISSUE THREAD

**Issue by Wottrich** [androiddevbr/agenda-medium#203]
* **Autor:** Lucas Cruz Wottrich
* **Perfil no medium:** medium.com/@wottrich (https://wottrich.medium.com/)
* **Título do artigo:** In-App Updates: Como gerenciar updates no Android
* **Descrição:** Esse artigo fala sobre como gerenciar updates no Android utilizando a biblioteca Google Play Core, mas o principal foco é na tomada de decisões em cima dessa ferramenta de In-App Updates
* **Link:** https://wottrich.medium.com/in-app-updates-como-gerenciar-updates-no-android-41c09a4cdd04

**Comment by Wottrich** [comment]
Alguma novidade sobre a revisão do artigo?

**Comment by orafaaraujo** [comment]
Fala, @Wottrich 

Acabei de ler o post e está bem maneiro, parabéns!

No começo pensei em sugerir quebrá-lo pois 8 minutos é "bastante", mas ele está bem dinâmico, sem frases longas e com exemplos, ficou show!

Te coloquei como writer em nosso Medium, quando puder, pode submeter?

Em nome da comunidade, muito obrigado!

**Comment by Wottrich** [comment]
Eae @orafaaraujo!

Eu que agradeço :) e submeti o artigo lá no medium.

**Comment by orafaaraujo** [comment]
Publicado! :D 

@all-contributors please add @Wottrich for blog
