### ISSUE TITLE
Testando ApolloGraphQL Subscriptions no Android + Kotlin Flow + Turbine - Diego Braun da Cunha

### ISSUE THREAD

**Issue by diegocunhawarren** [androiddevbr/agenda-medium#204]
* **Autor:** Diego Braun da Cunha
* **Perfil no medium:** medium.com/@diego-cunha
* **Título do artigo:** Testando ApolloGraphQL Subscriptions no Android + Kotlin Flow + Turbine
* **Descrição:** Artigo ensinando sobre testes unitários de Subscriptions do Graphql usando Flow como camada de transmissão de dados e Turbine para testes unitários.

**Comment by orafaaraujo** [comment]
Olá, @diegocunhawarren 

O tema é bem interessante!
Quando tiver um rascunho ou ele finalizado, manda o link pra gente dar uma olhada.

Obrigado :)

**Comment by diegocunhawarren** [comment]
Oi @orafaaraujo segue link, esqueci de anexar a issue
 https://diego-cunha.medium.com/testando-apollographql-subscriptions-no-android-kotlin-flow-turbine-3753dd9dc099

**Comment by orafaaraujo** [comment]
Oi, @diegocunhawarren 

Obrigado pelo retorno.
Acabei de ler o post e está bem bom!
Deixei 2 sugestões de Gist porque acho que melhoraria a visualização de código. E outra que deixo aqui é deixar os nomes dos componentes Kotlin/Android ou nomes em inglês em itálico, acho que ajudaria na leitura também.

Dito isso, te coloquei como writer em nosso Medium. Quando puder, pode submeter. :) 

Em nome da comunidade, muito obrigado.

**Comment by Diego-Cunha** [comment]
Não sou Diego Cunha Warren. Agradeço não me enviar novamente e buscar o email do destinatário correto.

________________________________
De: Rafael Araujo ***@***.***>
Enviado: quinta-feira, 24 de junho de 2021 14:26
Para: androiddevbr/agenda-medium
Cc: Diego Cavalcanti Cunha; Mention
Assunto: Re: [androiddevbr/agenda-medium] Testando ApolloGraphQL Subscriptions no Android + Kotlin Flow + Turbine - Diego Braun da Cunha (#204)


Oi, @diegocunhawarren<https://github.com/diegocunhawarren>

Obrigado pelo retorno.
Acabei de ler o post e está bem bom!
Deixei 2 sugestões de Gist porque acho que melhoraria a visualização de código. E outra que deixo aqui é deixar os nomes dos componentes Kotlin/Android ou nomes em inglês em itálico, acho que ajudaria na leitura também.

Dito isso, te coloquei como writer em nosso Medium. Quando puder, pode submeter. :)

Em nome da comunidade, muito obrigado.

-

**Comment by diegocunhawarren** [comment]
@orafaaraujo Realizei os ajustes de gist, sobre o compnente em italico eu não entendi muito bem.
Como eu submeto agora que realizei os ajustes?

**Comment by orafaaraujo** [comment]
Oi, @diegocunhawarren 

Deixei um exemplo no post, e acabei de publicá-lo também. Muito obrigado!

Oi, @Diego-Cunha, acho que você está recebendo email por que está assinado para receber notificações desta issue, ou deste repo. De qualquer foram, nos desculpe! 

Abraços

**Comment by orafaaraujo** [comment]
@all-contributors please add @gcherubini for blog

**Comment by orafaaraujo** [comment]
@all-contributors please add @diegocunhawarren for blog

Me desculpem o flood!
