### ISSUE TITLE
How to implement Android Accessibility Part 1 - Bruno Brustoloni e Oliveira

### ISSUE THREAD

**Issue by bbrustolalter** [androiddevbr/agenda-medium#205]
* **Autor:** Bruno Brustoloni e Oliveira
* **Perfil no medium:** medium.com/@bbrustol
* **Título do artigo:** How to implement Android Accessibility Part 1
* **Descrição:** This first article, I talked about the accessibility universe, Why are accessibility, my motivation to study it, and some Android tools.
* **Link:** https://bbrustol.medium.com/how-to-implement-android-accessibility-part-1-general-by-bruno-brustoloni-a46f906ff067
*  **ps.:** Tenho esse texto em português qualquer coisa.

**Comment by orafaaraujo** [comment]
Oi, @bbrustolalter 
Tudo bem?

Para publicar em nosso Medium, precisamos que o post esteja em português que é o foco da nossa comunidade.

Te aconselho a traduzi-lo em um novo post, aí você pode linkar a tradução de um no outro, o que acha?

Obrigado!

**Comment by bbrustol** [comment]
Olá pode ser.
Eu já tenho em português.
Só teria que publicar mesmo.

Vou tentar fazer isso até a próxima semana.
Entro em contato por aqui ou preciso abrir um novo?

Obrigado

Obrigado -- Bruno Brustoloni e Oliveira
Telegram/WhatsApp +351 914 85 88 81

**Comment by orafaaraujo** [comment]
Fala, @bbrustol 

Sem problemas, manda por aqui mesmo!

Abraços

**Comment by walmyrcarvalho** [comment]
@bbrustol Ainda pretende mandar o artigo? Se sim, só falar, caso contrário posso fechar a issue também!

**Comment by walmyrcarvalho** [comment]
@bbrustol Vou fechar a issue e caso tenha interesse em submeter de novo em pt-BR, só avisar que reabrimos, abraço!
