### ISSUE TITLE
Android Single Shot Events com Flow

### ISSUE THREAD

**Issue by jaozinfs** [androiddevbr/agenda-medium#206]
* **Autor:** João Victor Oliveira
* **Perfil no medium:** https://medium.com/@joaofgz123
* **Título do artigo:** Android Single Shot Events com Flow
* **Descrição:** Gostaria de compartilhar a maneira de solucionar um problema de único eventos observado no Android.
* **Link:** https://medium.com/@joaofgz123/android-single-shot-events-com-flow-d2d6ab8d220f

**Comment by orafaaraujo** [comment]
Fala, @jaozinfs 
Tudo bem?

Acabei de ler o post e deixei algumas sugestões. 
Aplicando-as, já pode submeter que publicamos o post, está bem show!

Obrigado mais uma vez!

**Comment by orafaaraujo** [comment]
Oi, @jaozinfs 

Vi que você já submeteu. 
Vou publicar, mas se puder dá uma olhada nas minhas sugestões, tudo bem?

Em nome da comunidade, muito obrigado!

**Comment by jaozinfs** [comment]
Opa @orafaaraujo 
Beleza e você ?
Que bom que gostou, fico feliz em poder ajudar de alguma forma a comunidade !
Obrigado pelas sugestões, ficou muito bom !
Já alterei todas 🗡️ 
Obrigado !!
