### ISSUE TITLE
 Executando Testes Instrumentados em uma tarefa Gradle - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#207]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com/
* **Título do artigo:** Executando Testes Instrumentados em uma tarefa Gradle
* **Descrição:** Compartilhar um pouco sobre as novidades de testes mostradas no Google I/O 2021, especialmente o Gradle Managed Virtual Devices. Ele permite a execução de testes instrumentados diretamente no AGP, sem configurações externas ou emuladores.
* **Link:** https://medium.com/@escodro/executando-testes-instrumentados-em-uma-tarefa-gradle-83df913edbc5
* **Publicação original:** https://proandroiddev.com/running-instrumented-tests-in-gradle-task-83bd483e6edd

**Comment by orafaaraujo** [comment]
Fala, @igorescodro 
Tudo bem?

Acabei de ler o post e está muito bom!
Objetivo e com exemplos, parabéns :D 

Quando puder, pode submete-lo em nosso Medium?

Em nome da comunidade, muito obrigado!

**Comment by orafaaraujo** [comment]
Publicado 🙌
