### ISSUE TITLE
Continuous Integration em projetos mobile (Android e iOS) - Guilherme Cherubini

### ISSUE THREAD

**Issue by gcherubini** [androiddevbr/agenda-medium#208]
* **Autor:** Guilherme Cherubini
* **Perfil no medium:** https://gcherubini.medium.com/
* **Título do artigo:** Continuous Integration em projetos mobile (Android e iOS)
* **Descrição:** Apresento uma arquitetura de Continuous Integration para projetos mobile.

Artigo para revisão:
https://medium.com/@gcherubini/continuous-integration-em-projetos-mobile-android-e-ios-5ed785cd5f16

**Comment by orafaaraujo** [comment]
Fala, @gcherubini 
Tudo bem?

Acabei de ler o seu post e está muito bom!
Quando puder, pode submete-lo em nosso Medium? Assim já publicamos :) 

Em nome da comunidade, muito obrigado!

**Comment by gcherubini** [comment]
Enviei @orafaaraujo , fico no aguardo.

Obrigado pelo feedback,
Abraço!

**Comment by orafaaraujo** [comment]
Publicado!

@all-contributors please add @gcherubini for blog
