### ISSUE TITLE
26/09/16 - Usando Java 8 no Android - Eduardo Bonet

### ISSUE THREAD

**Issue by ebonet** [androiddevbr/agenda-medium#21]
- **Autor:** Eduardo Bonet
- **Data escolhida:** 26/09/16
- **Título do artigo:** Usando Java 8 no Android
- **Descrição:** Java 8 trouxe diversas API's e mudanças de linguagem para o Java, porém mesmo com a nova Jack toolchain o suporte oficial no Android é bem limitado. Esse artigo visa mostrar alternativas para portar essas funcionalidades, como lambda, JSR-310 e streams. O artigo é baseado na talk de mesmo título disponível em https://github.com/ebonet/talk-java8-android.

**Comment by walmyrcarvalho** [comment]
Cara, por mim o tema tá aprovado! É um assunto mega interessante e vale a pena falar sobre.

Você acha que é um tema avançado ou rola de deixar como intermediário? Só pra eu ajustar as tags.

Sobre a data, se quiser pode colocar alguma data mais recente sem problemas também!

**Comment by walmyrcarvalho** [comment]
Boa, valeu @ebonet!

**Comment by ebonet** [comment]
Acho que não existe nada avançado. É mais expositivo do que apresentação de um novo conceito ou algo do gênero, coisas que qualquer um pode começar a usar sem muita dificuldade.

**Comment by walmyrcarvalho** [comment]
Entendi, maravilha! Fico no aguardo do seu artigo então, daí a gente dá uma revisada e publica. Mas o processo nem é burocrático, só pedimos que você mande alguns dias antes da data de publicação, como sugere o README! :) 

Novamente, muito obrigado pela contribuição!

**Comment by davidtcdeveloper** [comment]
Publicado :)
https://medium.com/android-dev-br/usando-java-8-no-android-d351e4ad391b#.lzsdf9dcd
