### ISSUE TITLE
Implementando a Core Splashscreen API - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#213]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com/
* **Título do artigo:** Implementando a Core Splashscreen API
* **Descrição:** Compartilhar como implementar a nova API de Splash Screen do Androdi 12 que foi backported até a API 23. Uma vez que ainda não existe documentação oficial ou tutoriais, resolvi escrever um artigo para ajudar a comunidade.
* **Link:** https://medium.com/@escodro/implementando-a-core-splashscreen-api-642c7f8c581b
* **Publicação original:** https://proandroiddev.com/implementing-core-splashscreen-api-e62f0e690f74

**Comment by angelica-oliv** [comment]
Olá Igor!!

Acabei de ler seu artigo, conteúdo muito bom, parabéns!! E obrigada por contribuir com nossa comunidade. :)
Vi aqui que você já está como writer no nosso medium, então quando quiser, só publicar o artigo e submeter para a nossa publicação.

Obrigada mais uma vez!

**Comment by igorescodro** [comment]
Olá, Angélica.

Muito obrigado!
Submetido!

Obrigado pelo review e feedback!

**Comment by angelica-oliv** [comment]
Imagina, nós que agradecemos!

Artigo publicado!
