### ISSUE TITLE
Acessando dependências de projeto com type-safe no Gradle - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#215]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** Acessando dependências de projeto com type-safe no Gradle
* **Descrição:** Compartilhar sobre a nova funcionalidade adicionado no Gradle 7.0, o _type-safety project accessors_. Esse novo recurso facilita o gerenciamento de dependências entre módulos com suporte a type-safety e auto-completion.
*  **Link:** https://medium.com/@escodro/usando-depend%C3%AAncias-de-projeto-com-type-safe-no-gradle-1672a8fc5375
* **Publicação original:** https://proandroiddev.com/using-type-safe-project-dependencies-on-gradle-493ab7337aa

**Comment by igorescodro** [comment]
Boa tarde,

O artigo precisa de alguma alteração?

Muito obrigado! 😊

**Comment by RBJUR** [comment]
Bom dia Igor, tudo bem?

Muito bacana o artigo, peguei somente uma coisinha minor que apontei em um comentário privado.
Assim que estiver ok pode submeter que eu farei a publicação.

Abraços
Roque

**Comment by igorescodro** [comment]
Bom dia, Roque.

Muito obrigado pela review! Já arrumei o seu comentário e submeti para publicação.

Abraços!

**Comment by RBJUR** [comment]
Artigo publicado!

Desculpe a demora para revisar.
Muito obrigado por sua contribuição :) 

Abraços!
Roque
