### ISSUE TITLE
Guia rápido de alarmes no Android 12 - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#216]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** Guia rápido de alarmes no Android 12
* **Descrição:** Um guia rápido e leve das particularidades da nova permissão de alarme exato lançada no Android 12. Esse artigo aborda o porquê, como e em quais momentos essas alterações são necessárias no seu app
* **Link do artigo:** https://medium.com/@escodro/guia-r%C3%A1pido-de-alarmes-no-android-12-4decb034c156

**Comment by RBJUR** [comment]
Fala @igorescodro blz?
Primeiro desculpa a demora em revisar seu artigo, final de ano ta corrido na comunidade.

Deixei um comentário bem minor e opcional, qnd quiser pode submeter seu artigo que vamos aprovar.
Obrigado por sua contribuição.

Abraços, 
Roque

**Comment by igorescodro** [comment]
Muito obrigado, Roque.
Artigo alterado com a sua alteração e submetido para publicação.

Abraços!

**Comment by RBJUR** [comment]
Artigo publicado
Valeu mais uma vez por sua contribuição.

Abraços!
