### ISSUE TITLE
UnidirectionalDataFlow no Android com JetpackCompose - Lucas Wottrich

### ISSUE THREAD

**Issue by Wottrich** [androiddevbr/agenda-medium#217]
* **Autor:** Lucas Cruz Wottrich
* **Perfil no medium:** medium.com/@wottrich (https://wottrich.medium.com/)
* **Título do artigo:** UnidirectionalDataFlow no Android com JetpackCompose
* **Descrição:** Hoje vamos conversar um pouco sobre o design pattern Unidirectional Data Flow (UDF) e como ele se deu bem com um carinha que nós, desenvolvedores android, estamos ficando cada dia mais apaixonados: O JetpackCompose.
* **Link:** https://wottrich.medium.com/unidirectionaldataflow-no-android-com-jetpackcompose-cf5f0f3e0d98

**Comment by Wottrich** [comment]
Opa @orafaaraujo! Tudo certo? Algum update sobre o artigo?

**Comment by roquebuarquejr** [comment]
Lucas, bom dia, tudo bem?

Revisei seu artigo e adicionei pequenos comentários, fique a vontade em me questionar. 
Assim que você resolver os comentários pode submeter o artigo que eu farei a publicação.

Abraços
Roque

**Comment by Wottrich** [comment]
Submetido @roquebuarquejr!
Muito obrigado pelo review e dicas!

**Comment by roquebuarquejr** [comment]
Publicado @Wottrich 
Obrigado por sua contribuição

Abraços
Roque
