### ISSUE TITLE
Criando um tema customizável com Jetpack Compose! - Lucas Yuji Yoshimine

### ISSUE THREAD

**Issue by DevLucasYuji** [androiddevbr/agenda-medium#218]
* **Autor:** Lucas Yuji Yoshimine
* **Perfil no medium:** https://medium.com/@lucasyujideveloper
* **Título do artigo:** Criando um tema customizável com Jetpack Compose!
* **Descrição:** Um guia de como criar um tema customizado do zero com Jetpack Compose, sem a dependência nenhuma do MaterialTheme, abordando tanto uma leve introdução de como funciona Material por debaixo dos panos, e depois criando o seu próprio.
* **Link:** https://medium.com/@lucasyujideveloper/criando-um-tema-customiz%C3%A1vel-com-jetpack-compose-3bb7b7a845ed

**Comment by roquebuarquejr** [comment]
Fala Lucas, blz? @DevLucasYuji 

Acabei de revisar seu artigo, fique a vontade para submeter, irei aprovar e publicar assim que estiver disponível.

Abraços
Roque

**Comment by roquebuarquejr** [comment]
Opa my bad 😄 
Acabei de te adicionar como writer @DevLucasYuji, fique a vontade para submeter.

Abraços
Roque

**Comment by DevLucasYuji** [comment]
Submetido @roquebuarquejr

Obrigado pelo review!

Abraços

**Comment by roquebuarquejr** [comment]
Artigo publicado
Obrigado por sua contribuição para comunidade :) 

Abraços
Roque
