### ISSUE TITLE
28/11/16 - RxJava - Morte a AsyncTask - Clêrton Leal

### ISSUE THREAD

**Issue by clertonleal** [androiddevbr/agenda-medium#22]
- **Autor:** Clêrton Leal
- **Data escolhida:** 28/11/16
- **Título do artigo:** RxJava - Morte a AsyncTask
- **Descrição:** Esse artigo é uma explanação básica do funcionamento do geral do RxJava como um framework complexo e poderoso e sua aplicação no mundo Android. Com exemplos práticos de códigos, e diversas indicações de uso para o RxJava em aplicações Android.
  Esse artigo é baseado em uma talk que ocorreu em Belo Horizonte: http://www.slideshare.net/ClertonLeal/rxjava-programao-assncrona-para-android

**Comment by walmyrcarvalho** [comment]
@clertonleal Fala Clerton, tudo bem? Você acha que vai conseguir terminar o artigo até amanhã? Se não, peço que atualize a data!

**Comment by clertonleal** [comment]
Opa, tudo ótimo @walmyrcarvalho . =D
Até amanhã não será possível mesmo, estava esperando a validação do tema e aprovação do post.
Tudo ok com esse tema? Se sim, pode deixar que eu remarco a data. ;)

**Comment by walmyrcarvalho** [comment]
@clertonleal Tudo bem com o tema, só escolher uma data boa! :)

**Comment by clertonleal** [comment]
Combinado então @walmyrcarvalho. Fica para o dia 28/11 então. =D

**Comment by walmyrcarvalho** [comment]
Beleza @clertonleal! 👍

**Comment by davidtcdeveloper** [comment]
@clertonleal  Estamos reorganizando a agenda de publicações para retomar o ritmo em 2017. Como está o post? Temos uma previsão de versão inicial?

**Comment by davidtcdeveloper** [comment]
Oi @clertonleal , caso o post volte a evoluir reabrimos a issue.
