### ISSUE TITLE
Revisão de Código em Projetos Android - Gabriel Bronzatti Moro

### ISSUE THREAD

**Issue by gabrielbmoro** [androiddevbr/agenda-medium#220]
* **Autor:** Gabriel Bronzatti Moro
* **Perfil no medium:** medium.com/@gabrielbronzattimoro.es
* **Título do artigo:** Revisão de Código em Projetos Android
* **Descrição:** Gostaria de falar um pouco sobre revisões de código em projetos Android. A ideia do artigo é falar sobre alguns pontos, os quais acredito serem fundamentais em um  _Code Review_: vazamentos de memória, violação arquitetural, layouts profundos, anotações de recursos, componentes similares, entre outros.
* **Link:** https://medium.com/@gabrielbronzattimoro.es/revis%C3%A3o-de-c%C3%B3digo-em-projetos-android-8288c6969617

**Comment by roquebuarquejr** [comment]
Gabriel, bom dia! Tudo bem?

Fiz alguns comentários bem minors no seu artigo e já te adicionei como writer.
Fique a vontade para aplicar as mudanças e submeter seu artigo. 

Qualquer dúvida só chamar.
Abraços
Roque

**Comment by gabrielbmoro** [comment]
> Gabriel, bom dia! Tudo bem?
> 
> Fiz alguns comentários bem minors no seu artigo e já te adicionei como writer. Fique a vontade para aplicar as mudanças e submeter seu artigo.
> 
> Qualquer dúvida só chamar. Abraços Roque

Olá Roque, obrigado pelas tuas sugestões. Eu já fiz as correções.

Grato 🤗

**Comment by roquebuarquejr** [comment]
Artigo publicado

Muito obrigado por sua contribuição para com a comunidade :) 

Abraços
Roque
