### ISSUE TITLE
Um primeiro olhar para o Material You - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#222]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** Um primeiro olhar para o Material You
* **Descrição:** O Google revelou o Material You durante o I/O 2021 e desde então lançou diversos tutoriais, bibliotecas e ferramentas. Vamos dar uma olhada nas novidades!
* **Link do artigo:** https://medium.com/android-dev-br/um-primeiro-olhar-para-o-material-you-b28cea80dc53
* **Publicação original:** https://proandroiddev.com/a-first-look-at-material-you-f8daea85b0d

**Comment by roquebuarquejr** [comment]
Artigo publicado!

Muito obrigado mais uma vez por sua contribuição @igorescodro.
Abraços
Roque
