### ISSUE TITLE
Construindo um projeto Android com UnidirectionalDataFlow e JetpackCompose - Lucas Wottrich

### ISSUE THREAD

**Issue by Wottrich** [androiddevbr/agenda-medium#223]
* **Autor:** Lucas Cruz Wottrich
* **Perfil no medium:** [medium.com/@wottrich](https://medium.com/@wottrich)
* **Título do artigo:** Construindo um projeto Android com UnidirectionalDataFlow e JetpackCompose
* **Descrição:** 
  * Depois de um artigo sobre porque é [recomendado utilizar Jetpack Compose com UnidirectionalDataFlow(UDF)](https://medium.com/android-dev-br/unidirectionaldataflow-no-android-com-jetpackcompose-cf5f0f3e0d98) vamos para um papo mais prático sobre como aplicar o UDF em um projeto feito em Compose.
Achei importante e interessante fazer esse artigo pois acompanho alguns projetos que utilizam esse design pattern e todos tem uma forma diferente de resolver as coisas, aqui quero trazer um pouco do que estudei e ando utilizando nos meus projetos.

Draft link: https://medium.com/@wottrich/construindo-um-projeto-android-com-unidirectionaldataflow-e-jetpackcompose-6018ce1f142e

**Comment by angelica-oliv** [comment]
Olá @Wottrich !
Acabei de ler seu artigo, muito bom e interessante.
Apenas coloquei algumas sugestões nos comentários, veja o que acha e me dê um retorno por aqui! ;)

Muito obrigada pela contribuição! 👏

**Comment by Wottrich** [comment]
Olá @angelica-oliv !
Muito obrigado pela revisão do artigo! Realmente ficou muito melhor com os seus pontos!
Fiz as alterações, fico no aguardo para o próximo passo.

Abraços!

**Comment by angelica-oliv** [comment]
Muito obrigada @Wottrich !
Já te adicionei como writer na nossa publicação, então agora é só vc submeter o artigo pra gente! 😄

**Comment by Wottrich** [comment]
Feito @angelica-oliv !

**Comment by angelica-oliv** [comment]
Artigo publicado!! Mais uma vez, muito obrigada! 🥳
