### ISSUE TITLE
Primeiros passos com Jetpack Glance para App Widgets - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#224]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** Primeiros passos com Jetpack Glance para App Widgets
* **Descrição:** Em dezembro, o Google anunciou o Glance para a criação de Widgets usando Compose. Esse artigo mostra como mergulhar nessa nova biblioteca.
* **Link do artigo:** https://medium.com/android-dev-br/primeiros-passos-com-jetpack-glance-para-app-widgets-399d045eac4c
* **Publicação original:** https://proandroiddev.com/first-steps-with-glance-app-widgets-b1e28e25a107

**Comment by angelica-oliv** [comment]
Eii @igorescodro !
Muito bom o artigo, já revisei aqui e pode publicar assim que você preferir!! 

Obrigada pela contribuição! 🥳

**Comment by igorescodro** [comment]
Muito obrigado, @angelica-oliv!
Artigo submetido do meu lado. Creio que agora você precise aceitar do lado do Medium do Android Dev BR. 😊

**Comment by angelica-oliv** [comment]
Feito 👏 👏
