### ISSUE TITLE
Primeiro Contato com Navigation no Compose - Gabriel B. Moro

### ISSUE THREAD

**Issue by gabrielbmoro** [androiddevbr/agenda-medium#225]
**Autor:** Gabriel Bronzatti Moro

**Perfil no medium:** [medium.com/@gabrielbronzattimoro.es](https://medium.com/@gabrielbronzattimoro.es)

**Título do artigo:** Primeiro Contato com Navigation no Compose

**Descrição:** 
Gostaria de falar um pouco sobre o meu primeiro contato com Navigation no Compose, definição do grafo de navegação e passagem de parâmetros customizados.

**Link:** https://medium.com/@gabrielbronzattimoro.es/primeiro-contato-com-navigation-no-compose-f0b2a5bde37d

**Comment by angelica-oliv** [comment]
Olá @gabrielbmoro !
Fiz apenas um comentário com uma sugestão de ajuste.

Veja o que acha! :) 
Perdão pela demora em te dar um retorno aqui...

**Comment by gabrielbmoro** [comment]
> Olá @gabrielbmoro ! Fiz apenas um comentário com uma sugestão de ajuste.
> 
> Veja o que acha! :) Perdão pela demora em te dar um retorno aqui...

Olá @angelica-oliv , que isso, entendo, deve tá super puxado.

Obrigado pela tua sugestão, eu atualizei a introdução para não ser tão direto 😅 

Aguardo retorno.
Obrigado 🤗

**Comment by gabrielbmoro** [comment]
Olá @angelica-oliv, já tinha feito o ajuste e fiz a submissão.

Qualquer coisa me avisa. 

Obrigado 🤗

**Comment by walmyrcarvalho** [comment]
@gabrielbmoro Gabriel, tudo bem?

Peço desculpas pela demora, vamos retomar as revisões dos artigos essa semana e aviso aqui se estiver tudo OK!

Abraço!

**Comment by gabrielbmoro** [comment]
@walmyrcarvalho show de bola, grato!

**Comment by gabrielbmoro** [comment]
Olá @angelica-oliv eu fiz os ajustes que tu solicitou.

Alguma outra sugestão?

Cc: @walmyrcarvalho / @davidtcdeveloper

**Comment by walmyrcarvalho** [comment]
@gabrielbmoro Tudo bem Gabriel?

Revisei o artigo e pra mim tá tudo certo! Adicionei o seu artigo na nossa publication e o link é esse!

[https://medium.com/@gabrielbronzattimoro.es/primeiro-contato-com-navigation-no-compose-f0b2a5bde37d](https://medium.com/@gabrielbronzattimoro.es/primeiro-contato-com-navigation-no-compose-f0b2a5bde37d)

Obrigado novamente pela sua contribuição e peço desculpas novamente pela demora na revisão, por conta de alguns problemas organizacionais na moderação a gente deixou a bola cair em alguns aspectos, mas estamos arrumando a casa e a revisão de artigos é um dos pontos que vamos trabalhar pra melhorar.

Abraço!
