### ISSUE TITLE
Simultaneidade estruturada e Coroutines

### ISSUE THREAD

**Issue by jaozinfs** [androiddevbr/agenda-medium#226]
Autor: João Victor Oliveira
Perfil no medium: https://medium.com/@joaofgz123
Título do artigo: Simultaneidade estruturada e Coroutines
Descrição: Hoje vamos falar um pouco de algumas features muito pouco comentadas no nosso dia a dia com a biblioteca Coroutines.

**Comment by angelica-oliv** [comment]
Oii @jaozinfs !
O artigo é esse né?
https://medium.com/@joaofgz123/simultaneidade-estruturada-e-coroutines-54c20a04c0d2

Se sim, o que vc acha do ajuste que mencionei? Sobre deixar os códigos em gists?

**Comment by walmyrcarvalho** [comment]
@jaozinfs João, tudo bem?

Você pretende fazer os ajustes mencionados?

Abraço!

**Comment by jaozinfs** [comment]
> @jaozinfs João, tudo bem?
> 
> Você pretende fazer os ajustes mencionados?
> 
> Abraço!
@walmyrcarvalho Tudo bem e com vc ?
Atualizado :)

**Comment by jaozinfs** [comment]
> @jaozinfs Tudo bem?
> 
> Com os gists, acho que você pode remover as imagens, pois possuem o mesmo conteúdo, consegue fazer esse ajuste? Daí publicamos!
> 
> Abraço!

Bom dia, tudo bem? 
Deixei a imagem para exemplificar o output, ficaria mais fácil a leitura.
Acredito que seria melhor os dois.

**Comment by walmyrcarvalho** [comment]
@jaozinfs Fala João, beleza?

Cara, gostei do seu artigo, deixei alguns comentários de ajustes leves mas em geral tá tudo certo! O link dele na nossa publication é esse:

https://medium.com/android-dev-br/simultaneidade-estruturada-e-coroutines-54c20a04c0d2?postPublishedType=repub

Novamente, agradeço pela sua contribuição e peço desculpas pela demora gigante nas revisões, estamos revisitando nossas iniciativas e as coisas devem melhorar por aqui nesse aspecto. 

Um abraço! :D
