### ISSUE TITLE
D&D - Party Perfeita para sua Aplicação Android - Rodrigo Vianna Calixto de Oliveira

### ISSUE THREAD

**Issue by rviannaoliveira** [androiddevbr/agenda-medium#227]
* **Autor:** Rodrigo Vianna Calixto de Oliveira
* **Perfil no medium:** medium.com/@rodrigo.vianna.oliveira
* **Título do artigo:** D&D - Party Perfeita para sua Aplicação Android
* **Descrição:** É um artigo explicando uma solução que junta 4 soluções que deram origem a 3 bibliotecas que estão linkadas tb. Mas de um jeito um pko diferente do habitual fazendo uma associação de RPG com tecnologias.
Ai se vcs acharem que faz sentido, podemos tb pensar em colocar os outros artigos linkados

link: https://medium.com/@rodrigo.vianna.oliveira/d-d-party-perfeita-para-sua-aplica%C3%A7%C3%A3o-android-6fa4b94d8618

**Comment by angelica-oliv** [comment]
Olá @rviannaoliveira !!
Gostei bastante do seu artigo, parabéns pela criatividade e iniciativa!!

Fiz alguns comentários de alguns ajustes.
Veja o que acha! :)
Obrigada pela contribuição!

**Comment by rviannaoliveira** [comment]
Valeu!!!!! eu estou fazendo agora as alterações, e muito obrigado pelo elogio!

**Comment by walmyrcarvalho** [comment]
@rviannaoliveira Rodrigo, tudo bem?

Peço desculpas pela demora na resposta, estamos retomando a organização aqui do Medium. 
Gostei bastante do seu texto, ótimo tema e ficou bem organizado, parabéns!

Depois dos ajustes, o recomendado é você submeter o seu texto para a nossa publicação!

Aqui explica um pouco: https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publicatio

Daí te adicionamos como writer e seu texto entra na publicação!

Abraço!

**Comment by rviannaoliveira** [comment]
Eu fiz as obs, e li o passo a passo, mas eu ja travo no passo 4, pois não estou em outro grupo, soh esses da imagem

![Captura de Tela 2022-06-20 às 11 38 08](https://user-images.githubusercontent.com/7690931/174625837-128b4ab9-6d7d-4279-b04d-08a0f2250f91.png)

**Comment by rviannaoliveira** [comment]
tranquilo mano fico no aguardo _o/

**Comment by rviannaoliveira** [comment]
@walmyrcarvalho deu certo, mandei o submit

**Comment by walmyrcarvalho** [comment]
@rviannaoliveira Beleza mano, vou dar uma olhada e se tudo estiver OK a gente sobe, qualquer outro comentário eu te aviso!

**Comment by rviannaoliveira** [comment]
claro mano precisando soh da um toque

**Comment by rviannaoliveira** [comment]
@walmyrcarvalho curiosidade, mas sem pressa, alguma novidade?

**Comment by walmyrcarvalho** [comment]
@rviannaoliveira Foi mal pela demora, Rodrigo, adicionada a publicação!

https://medium.com/android-dev-br/d-d-party-perfeita-para-sua-aplica%C3%A7%C3%A3o-android-6fa4b94d8618
