### ISSUE TITLE
Guia completo sobre viewModelScope e conceitos de Coroutines - Jhonatan Sabadi

### ISSUE THREAD

**Issue by jhonatansabadi** [androiddevbr/agenda-medium#228]
* **Autor:** Jhonatan Sabadi
* **Perfil no medium:** medium.com/@jjhonsabadi
* **Título do artigo:** Guia completo sobre viewModelScope e conceitos de Coroutines
* **Descrição:** Gostaria de falar sobre a utilização do viewModelScope e toda estrutura de coroutines envolvida para o seu funcionamento. A ideia principal é mostrar de forma clara como utilizar viewModelScope da mais correta para o cenário de cada projeto. Falo também sobre os conceitos principais de coroutines e dou exemplos práticos de uso.
*  **Link medium:** https://medium.com/@jhonsabadi/guia-completo-sobre-viewmodelscope-e-conceitos-de-coroutines-ffc667d0a445

**Comment by walmyrcarvalho** [comment]
@jhonatansabadi Obrigado pelas correções, o artigo está revisado e o texto foi adicionado à nossa publicação!

https://medium.com/android-dev-br/guia-completo-sobre-viewmodelscope-e-conceitos-de-coroutines-ffc667d0a445
