### ISSUE TITLE
07/11/16 - Iniciação ao Realm, parte 2: Migrations - Douglas Drumond

### ISSUE THREAD

**Issue by douglasdrumond** [androiddevbr/agenda-medium#23]
- **Autor:** Douglas Drumond
- **Data escolhida:** 07/11/16
- **Título do artigo:** Iniciação ao Realm – Migrations
- **Descrição:** Continuando o primeiro post sobre Realm, vamos continuar falando das migrações de versões de bancos e como migrar de SQLite p/ Realm, caso já esteja usando um aplicativo com SQLite

**Comment by davidtcdeveloper** [comment]
@douglasdrumond Como eu comentei, estou reorganizando a agenda da publicação? Tem uma previsão de quando podemos retomar esse post? Qualquer coisa fechamos a issue e abrimos uma nova mais para a frente.

**Comment by douglasdrumond** [comment]
Vamos colocar p/ próximo disponível, 30/01.

**Comment by walmyrcarvalho** [comment]
@douglasdrumond Acho que esse vai conflitar com o do Rafa (https://github.com/androiddevbr/agenda-medium/issues/30), pode ser pra próxima data? (13/02)

**Comment by orafaaraujo** [comment]
@walmyrcarvalho se o @douglasdrumond preferir pode deixar no dia *30/01* mesmo
Ele havia comentado antes... como não vi no título achei que o dia estava vago

:+1:

**Comment by walmyrcarvalho** [comment]
@orafaaraujo pode ser então, vamos colocar os eu mais pra frente! :)
