### ISSUE TITLE
Organização de dependências com version catalogs no gradle - Lucas Yuji

### ISSUE THREAD

**Issue by ujizin** [androiddevbr/agenda-medium#230]
* **Autor:** Lucas Yuji Yoshimine
* **Perfil no medium:** https://medium.com/@lucasyujideveloper
* **Título do artigo:** Organização de dependências com version catalogs no gradle
* **Descrição:** Gostaria de falar um pouco mais sobre como criar uma organização usando a feature nova do gradle. De uma forma introdutória para a feature e com exemplos de implementações em um projeto.

Link: https://medium.com/@lucasyujideveloper/organiza%C3%A7%C3%A3o-de-depend%C3%AAncias-com-version-catalogs-no-gradle-28ba050f9e52

**Comment by walmyrcarvalho** [comment]
@DevLucasYuji Opa Lucas, tudo bem?

Peço desculpas pela demora, estamos retomando as revisões de artigos aqui no Medium, aviso assim que olhar o seu, tudo bem?

Abraço!

**Comment by orafaaraujo** [comment]
Oi, @ujizin 

Muito bacana o seu post, acabei de ler e está pronto pra ser publicado.

Pode submete-lo, por favor? Quando faze-lo, irei publicar.

Obrigado pela contribuição!

**Comment by orafaaraujo** [comment]
Oi @ujizin 
Artigo publicado!

Mais uma vez, obrigado pela colaboração 🙏
