### ISSUE TITLE
Criando testes confiáveis para notificações Android - Igor Escodro

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#232]
* **Autor:** Igor Escodro
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** Criando testes confiáveis para notificações Android
* **Descrição:** Notificações são uma parte muito importante dos apps Android, e nesse artigo vamos analisar como criar testes mais confiáveis.
* **Link do artigo:** https://medium.com/android-dev-br/criando-testes-confi%C3%A1veis-para-notifica%C3%A7%C3%B5es-android-aa16dd51e969
* **Publicação original:** https://proandroiddev.com/creating-reliable-tests-for-android-notifications-4b3aa7aa147a

**Comment by walmyrcarvalho** [comment]
@igorescodro Fala Igor, tudo bem?

Obrigado pela submissão, vamos revisar o artigo nessa semana e aviso aqui caso precise de algum ajuste!

Abraço!

**Comment by orafaaraujo** [comment]
Oi @igorescodro Tudo bem?

Parabéns pelo artigo, está bem completo e pronto para a submissão 🚀

Percebi que já estava pronto para publicá-lo, então tomei a liberdade de faze-lo.

Obrigado novamente <3
