### ISSUE TITLE
Utilizando SonarQube como sua ferramenta de Code Smells + Cobertura de testes unitários em projeto Android parte 1 e 2

### ISSUE THREAD

**Issue by diegocunhawarren** [androiddevbr/agenda-medium#234]
Autor: Diego Cunha
Perfil no medium: medium.com/@diego-cunha
Título do artigo: Utilizando SonarQube como sua ferramenta de Code Smells + Cobertura de testes unitários em projeto Android pt 1  e 2
Descrição: Artigo ensinando como configurar o SonarQube para metrificar qualidade de código no Android utilizando o Github Actions como ferramenta de CI

- [Link 1](https://diego-cunha.medium.com/utilizando-sonarqube-como-ferramenta-de-an%C3%A1lise-em-projeto-android-parte-1-14ee132727d4)
- [Link 2](https://diego-cunha.medium.com/utilizando-sonarqube-como-sua-ferramenta-an%C3%A1lise-de-c%C3%B3digo-em-projeto-android-parte-2-8ced173ad9f4)

**Comment by diegobcunha** [comment]
Olá, esse usuário que usei para postar a agenda foi desativado pois era um usuário da empresa que trabalhada, se possivel gostaria de migrar para esse usuário.

**Comment by orafaaraujo** [comment]
Oi @diegobcunha 

Obrigado pelos posts, quebrá-lo em duas partes foi uma ótima decisão, ambos estão leves para a leitura!

Poderia submete-los em nosso Medium? Quando fizer isso, eu já publico 🚀

Fico no aguardo 🙏

**Comment by diegocunhaml** [comment]
@orafaaraujo Publicado e obrigado pelo feedback <3

**Comment by orafaaraujo** [comment]
Olá @diegocunhaml 

Posts publicados, muito obrigado novamente 🙏

Tenha um bom fim de semana!
