### ISSUE TITLE
Acessibilidade com Jetpack Compose - Gabriel Bronzatti Moro

### ISSUE THREAD

**Issue by gabrielbmoro** [androiddevbr/agenda-medium#237]
* **Autor:** Gabriel Bronzatti Moro
* **Perfil no medium:** medium.com/@gabrielbronzattimoro.es
* **Título do artigo:** Acessibilidade com Jetpack Compose
* **Descrição:** Relato de experiência ao aplicar recursos de acessibilidade do Jetpack Compose em um projeto pessoal.
* **Link do artigo:** https://medium.com/@gabrielbronzattimoro.es/acessibilidade-com-jetpack-compose-2372b99ce731

**Comment by gabrielbmoro** [comment]
Olá @walmyrcarvalho , alguma sugestão para que eu possa implementar. Grande abraço!

**Comment by walmyrcarvalho** [comment]
@gabrielbmoro opa, eu vou dar uma olhada nos artigos pendentes essa semana, valeu e desculpa pela demora, mano!

**Comment by orafaaraujo** [comment]
Olá, @gabrielbmoro 

Post revisado e pronto para submissão! 🚀
Assim que subemter a gente publica, tá bem?

Obrigado novamente, o post ficou muito bom!

**Comment by gabrielbmoro** [comment]
> Olá, @gabrielbmoro
> 
> Post revisado e pronto para submissão! 🚀 Assim que subemter a gente publica, tá bem?
> 
> Obrigado novamente, o post ficou muito bom!

Submetido.

Obrigado pelas sugestões @orafaaraujo!

**Comment by orafaaraujo** [comment]
Oi @gabrielbmoro 

Publicado! Obrigado novamente 🚀
