### ISSUE TITLE
 Resolvendo OWASP crackme level 1 com Android Studio + bytecode viewer - Jeferson Oliveira

### ISSUE THREAD

**Issue by jefoliveira-mobile** [androiddevbr/agenda-medium#238]
* **Autor:** Jeferson Oliveira
* **Perfil no medium:** medium.com/@jefoliveira.mobile
* **Título do artigo:** Resolvendo OWASP crackme level 1 com Android Studio + bytecode viewer
* Link do artigo: (https://medium.com/@jefoliveira.mobile/resolvendo-owasp-crackme-level-1-com-android-studio-bytecode-viewer-af72b9f57df)
* **Descrição:** Falo sobre o popular framework de segurança da informação, OWASP; mais especificamente sobre os materiais públicos do MSTG ou Mobile Security Testing Guide e como eles podem melhorar a forma como construímos aplicativos seguros.

**Comment by jefoliveira-mobile** [comment]
Bom dia @orafaaraujo,

Não estou conseguindo realizar a publicação. Minha conta foi adicionada ao perfil?

Obrigado pela ajuda.

![image](https://user-images.githubusercontent.com/118688160/225615825-1633a49e-9975-46cf-8149-fb0c77d6d25f.png)

**Comment by orafaaraujo** [comment]
Oii @jefoliveira-mobile 
Poderia tentar novamente?

Obrigado!

**Comment by orafaaraujo** [comment]
agora está adicionado!

Faltou salvar haha

**Comment by jefoliveira-mobile** [comment]
Agora foi. kkk

Obrigado @orafaaraujo

**Comment by orafaaraujo** [comment]
Obrigado você @jefoliveira-mobile!
A comunidade agradece a publicação 🙏
