### ISSUE TITLE
Arquitetura Android Moderna: utilizando Single Activity Pattern - William Amaral

### ISSUE THREAD

**Issue by WillACosta** [androiddevbr/agenda-medium#239]
* **Autor:** William Amaral
* **Perfil no medium:** medium.com/@willAmaral
* **Título do artigo:** Arquitetura Android Moderna: utilizando Single Activity Pattern
* **Descrição:** A ideia central desse artigo, é trazer à tona a discussão sobre como pequenas mudanças em nossa arquitetura podem trazer benefícios ao longo do tempo, nesse caso, utilizando uma sugestão de arquitetura fornecida pelo time do Google.
* **Link do artigo:**  https://medium.com/@willAmaral/arquitetura-android-moderna-utilizando-single-activity-pattern-e38aa658a129

**Comment by orafaaraujo** [comment]
Fala @WillACosta tudo bem?
Obrigado pela submissão!

Acabei de ler o post e ficou bem bom, conciso e objetivo! 
Te coloquei como writer em nosso Medium, quando tiver um tempinho, pode submete-lo, por gentileza?

Fico no aguardo 🙏

**Comment by WillACosta** [comment]
Olá! @orafaaraujo muito obrigado! 😄
Só não encontrei a opção de publicação.

![Screenshot 2023-03-20 at 09 30 20](https://user-images.githubusercontent.com/22602504/226339351-b27ffda9-c5e6-4d52-8194-a3c92abdfe48.png)

**Comment by orafaaraujo** [comment]
Oi @WillACosta 
Pode tentar novamente?

Obrigado!

**Comment by WillACosta** [comment]
Tudo certo agora! Muito obrigado!! 🎉💚😉

**Comment by orafaaraujo** [comment]
Publicado!

Muuuito obrigado pela colaboraçnao, @WillACosta !
Estamos sempre aberto a novas publicações 🙏
