### ISSUE TITLE
05/12/16 - Fazendo um ótimo app, além dos bits & bytes - Vítor de Almeida

### ISSUE THREAD

**Issue by vitordealmeida** [androiddevbr/agenda-medium#24]
- **Autor:** Vítor de Almeida
- **Data escolhida:** 05/12/16
- **Título do artigo:** Fazendo um ótimo app, além dos bits & bytes
- **Descrição:** Cada dia saem novas ferramentas, e nós, desenvolvedores, buscamos estar sempre atualizados. Frameworks, bibliotecas, arquiteturas. Nosso código está desacoplado, os testes estão passando, o servidor gera o APK e automaticamente já faz o upload para a Google Play, porém, nosso número de usuários continua baixo.
  Neste artigo, mostrarei problemas comuns de apps Android e técnicas para detectarmos e corrigirmos esses problemas, passando por ferramentas da Google Play, testes A/B e analytics.

**Comment by walmyrcarvalho** [comment]
@vitordealmeida Tema bacana, cara! Aprovado! :)

**Comment by davidtcdeveloper** [comment]
@vitordealmeida  Estamos reorganizando a agenda de publicações para retomar o ritmo em 2017. Como está o post? Temos uma previsão de versão inicial?

**Comment by vitordealmeida** [comment]
Olá @davidtcdeveloper, ainda está em fase inicial, tive uma série de contratempos e, inclusive, no momento estou viajando a trabalho, sem possibilidade de continuar a publicação.
Fique a vontade para remover da lista de publicações pois não vou conseguir fornecer uma data, mas continuarei o artigo e, quando tiver ele mais próximo de uma finalização, entro em contato.

**Comment by davidtcdeveloper** [comment]
Tudo bem @vitordealmeida, fecharei essa issue por enquanto. Mas a proposta do artigo é ótima, então gostaríamos de ter ele em nossa publicação no futuro :)
Obrigado
