### ISSUE TITLE
ADBR Meetup #12: Principais novidades da Android Dev Summit 2022 + AMA - Igor Escodro e Walmyr Carvalho

### ISSUE THREAD

**Issue by igorescodro** [androiddevbr/agenda-medium#240]
* **Autor:** Igor Escodro e Walmyr Carvalho
* **Perfil no medium:** escodro.medium.com
* **Título do artigo:** ADBR Meetup 12: Principais novidades da Android Dev Summit 2022 + AMA
* **Descrição:** Quer saber o que rolou no ADBR Meetup 12? Esse artigo traz um resumo desse evento que focou no ADS 2022 e teve um AMA com a comunidade.
* **Link:** https://medium.com/@escodro/adbr-meetup-12-principais-novidades-da-android-dev-summit-2022-ama-735b4ee35998

**Comment by orafaaraujo** [comment]
Oi, @igorescodro e @walmyrcarvalho 

Obrigado pela submissão. Li e já publiquei, ficou muito bom este resumo!

Até! <3
