### ISSUE TITLE
Como gerar um diagrama wbs de seus projetos Android - Jeferson Oliveira

### ISSUE THREAD

**Issue by jefoliveira-mobile** [androiddevbr/agenda-medium#242]
* **Autor:** Jeferson Oliveira
* **Perfil no medium:** https://medium.com/@jefoliveira.mobile
* **Título do artigo:** Como gerar um diagrama wbs de seus projetos Android
* Link do artigo: (https://medium.com/@jefoliveira.mobile/como-gerar-um-diagrama-wbs-de-seus-projetos-android-ce14516280db)
* **Descrição:** Gostaria de falar um pouco mais sobre Work breakdown structure (Wbs) e Uml em projetos mobile. A ideia do meu artigo é gerar uma documentação básica wbs para que seja possível demonstrar o estado atual do projeto android e seus principais módulos.

**Comment by orafaaraujo** [comment]
Oi @jefoliveira-mobile,
Tudo bem? 

Obrigado pela submissão! Acabei de ler o post e ele está pronto para submissão! 🚀
Te coloquei como writer em nosso Medium, quando tiver um tempinho, pode submete-lo, por gentileza?

Fico no aguardo 🙏

**Comment by orafaaraujo** [comment]
Oi @jefoliveira-mobile 

Post publicado!
Obrigado pela colaboração, as portas estão sempre abertas!
