### ISSUE TITLE
Como um desenvolvedor Android pode se reinventar para usar o Jetpack Compose - Bruno Martho

### ISSUE THREAD

**Issue by bmartho** [androiddevbr/agenda-medium#244]
Autor: Bruno Martho
Perfil no medium: https://medium.com/@bjmartho
Título do artigo: Como um desenvolvedor Android pode se reinventar para usar o Jetpack Compose
Descrição: Relato de como um desenvolvedor Android começou a sua jornada no Jetpack Compose e como superou o desafio de parar de pensar em XML
Link: https://medium.com/@bjmartho/como-um-desenvolvedor-android-pode-se-reinventar-para-usar-o-jetpack-compose-68e8ab7c1026

**Comment by orafaaraujo** [comment]
Oi @bmartho 

Obrigado pelo post, acabei de ler e ele é inspirador. Felizmente temos que aprender coisas novas sempre no mundo Android.

Pode submeter o post. Te coloquei como writer em nosso Medium.

Em nome da nossa comunidade, muito obrigado.

**Comment by bmartho** [comment]
Oi!
Submeti o post, acho que falta a aprovação de alguém.

Obrigado!

**Comment by orafaaraujo** [comment]
Feito, obrigado novamente!
