### ISSUE TITLE
Utilizando Bill of Materials em seu design system - Thiago Souto

### ISSUE THREAD

**Issue by othiagosouto** [androiddevbr/agenda-medium#245]
* **Autor:** Thiago Souto
* **Perfil no medium:** https://othiagosouto.medium.com/
* **Título do artigo:** Utilizando Bill of Materials em seu design system
* **Descrição:** Objetivo do post é explicar oque é Bill of materials, benefícios em sua utilização, e apresentar um gradle plugin que facilite essa criação através de um projeto demo. 
* **Link do artigo:** [draft link](https://medium.com/@othiagosouto/utilizando-bill-of-materials-em-seu-design-system-88f828065203)

**Comment by othiagosouto** [comment]
@orafaaraujo, acabei de submeter :)

**Comment by orafaaraujo** [comment]
@othiagosouto 

Feito! Muito obrigado novamente pelo conteúdo 🙏
