### ISSUE TITLE
23/01/17 - RecyclerViews - Rafael de Araújo

### ISSUE THREAD

**Issue by orafaaraujo** [androiddevbr/agenda-medium#25]
* **Autor:** Rafael de Araújo
* **Data escolhida:** 01/01/17
* **Título do artigo:** Trabalhando com RecyclerViews
* **Descrição:** Explicar como o RecyclerView funciona, como fazer listas e grids usando LayoutManager, como adicionar/atualizar/remover apenas a View que foi alterada para garantir performance, como utilizar views diferentes (como header ou footer) e boas práticas. Também poderia falar sobre como fazer um "Endless Scrolling" (paginação) mas acho que ficaria muito extenso. Poderia ser um novo post...
A ideia deste post é utilizá-lo posteriormente para fazer um post conceitos de Rx na prática.

**Comment by davidtcdeveloper** [comment]
Boa ideia de post. Sugiro focar nos conceitos mais avançados, se possível usando listas heterogêneas, gerenciadores de layouts menos comuns e conceitos como integração com CoordinatorLayout e nested scroll.

**Comment by orafaaraujo** [comment]
-Lista heterogêneas pretendo abordar, junto com o conceito de header/footer.
-Pretendo usar os layouts de listas verticals e horizontais, e também o esquema de Grids. Vou tentar fazer um layout que se adapte fácil em todos pontos citados.
-NestedScroll, boa ideia!
-CoordinatorLayout será um ótimo bônus :-)

**Comment by davidtcdeveloper** [comment]
@orafaaraujo: Estamos reorganizando a agenda de publicações para retomar o ritmo em 2017. Como está o post? Temos uma previsão de versão inicial?

**Comment by orafaaraujo** [comment]
Ainda estou trabalhando nele, @davidtcdeveloper 
Creio que até o próximo final de semana estará fechado!

**Comment by davidtcdeveloper** [comment]
Beleza, quando tiver uma primeira versão pode adicionar à publicação que a gente revisa :)

**Comment by orafaaraujo** [comment]
Em rascunho, para revisão
https://medium.com/@orafaaraujo/list-recycler-view-d3f41e0d653c

**Comment by davidtcdeveloper** [comment]
Publicado! https://medium.com/android-dev-br/listas-com-recyclerview-d3f41e0d653c#.6jvsgdx5n
