### ISSUE TITLE
Princípios de trabalho Home-office

### ISSUE THREAD

**Issue by thiagoneves1** [androiddevbr/agenda-medium#26]
Autor: Thiago Neves
Data escolhida: 02/12/2016
Título do artigo: Princípios de trabalho Home-office
Descrição:  Escrevi um post sobre alguns princípios de trabalho home-office, acredito que seja útil já que muitos devs querem trabalho assim.

**Comment by davidtcdeveloper** [comment]
Oi @thiagoneves1, obrigado pela submissão.
O post já foi publicado? Poderia passar o link?
Nossa publicação é voltada para desenvolvimento de aplicativos Android. Então o post faz sentido na publicação caso fale da experiência de desenvolver aplicativos trabalhando remotamente. O ideal é que o post traga informações relevantes para desenvolvedores Android que querem atuar trabalhando remotamente.

**Comment by thiagoneves1** [comment]
Olá @davidtcdeveloper  o post foi publicado ontem (https://medium.com/@Thiago_neves/princ%C3%ADpios-de-trabalho-home-office-ad30a05c3f8d#.cm9icgcjk) eu não falo especificamente de Android, apesar de trabalhar com Android também, mas como comentei com o Walmyr e ele concordou, é um conteúdo não técnico que tem relevância por causa do tema home-office. Obrigado.

**Comment by davidtcdeveloper** [comment]
pOi @thiagoneves1, conferi aqui que o post já foi adicionado a outra publicação. Como o post fala mais sobre home office e não especificamente sobre Android, vamos deixar de fora da publicação do Android Dev BR.
De qualquer forma, agradecemos pela participação.
