### ISSUE TITLE
16/01/17 - Introdução ao Dagger 2 - Caique Oliveira

### ISSUE THREAD

**Issue by jcaiqueoliveira** [androiddevbr/agenda-medium#27]
* **Autor:** Caique Oliveira
* **Data escolhida:** 16/01/17
* **Título do artigo:** Introdução ao Dagger2
* **Descrição:** No artigo é explicado sobre inversão de dependência, injeção de dependência e também foi mostrado(a através de exemplos) como utilizar o Dagger2 para fazer a injeção de dependência.

**Comment by davidtcdeveloper** [comment]
Obrigado pela inclusão do post @jcaiqueoliveira 
O post já está pronto? Se estiver, pode enviar o link?
Você já é escritor da nossa publicação no Medium? Se não, por favor me passe seu nome de usuário no Medium :)

**Comment by jcaiqueoliveira** [comment]
@davidtcdeveloper ainda não sou editor do medium
link do texto: https://medium.com/@caiqueoliveira_40648/introdu%C3%A7%C3%A3o-ao-dagger-2-56d193118a6c#.hnnzjpsk0

**Comment by davidtcdeveloper** [comment]
Publicado: https://medium.com/android-dev-br/introdu%C3%A7%C3%A3o-ao-dagger-2-56d193118a6c#.kaifyrshp
