### ISSUE TITLE
06/02/17 - Como criar suas próprias bibliotecas - João de Freitas

### ISSUE THREAD

**Issue by jgabrielfreitas** [androiddevbr/agenda-medium#29]
* **Autor:** João de Freitas
* **Data escolhida:** 06/02/17
* **Título do artigo:** Como criar suas próprias bibliotecas
* **Descrição:** Um simples tutorial de como criar e distribuir bibliotecas com o JFrog e gradle

**Comment by davidtcdeveloper** [comment]
Link para o post: https://medium.com/@jgabrielafreitas/como-criar-suas-pr%C3%B3prias-bibliotecas-b86e4ad77b92#.5fyoxfo23

**Comment by davidtcdeveloper** [comment]
@jgabrielfreitas Te adicionei como escritor da nossa publicação, quando puder, por favor adicione o post à ela ;)

**Comment by jgabrielfreitas** [comment]
obrigado @davidtcdeveloper ! estou finalizando alguns pontos levantado pelo @rsicarelli e já adiciono

**Comment by davidtcdeveloper** [comment]
Oi @jgabrielfreitas, você chegou a ver que adicionamos alguns comentários ao post.
Precisamos que você dê uma revisada nestes comentários e os responda conforme possível para que a gente possa publicar o artigo assim que estiver tudo ok ;)

**Comment by jgabrielfreitas** [comment]
Oi @davidtcdeveloper ! Vi sim e até já acertei algumas, mas no momento não estou no Rio, volto dia 30 e acerto o que estiver faltando

**Comment by davidtcdeveloper** [comment]
Beleza, qualquer coisa é só falar :)

**Comment by jgabrielfreitas** [comment]
Oi @davidtcdeveloper , fiz lá as alterações :)

Abraço
