### ISSUE TITLE
16/05/16 - Testes: unitário vs aceitação  - Rodrigo Sicarelli

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/agenda-medium#3]
* **Autor:** Rodrigo Sicarelli
* **Data escolhida:** 16/05/16
* **Título do artigo:** Testes: unitário vs aceitação
* **Descrição:**  Constantemente, recebo dúvidas como "O que devo testar unitariamente ou não no Android?" ou até "O que vale mais a pena eu investir meu tempo?". Esse post tem como intuito desmistificar e entender tipos de teste que podemos explorar no Android.

**Comment by walmyrcarvalho** [comment]
Excelente tema @rsicarelli! :)

**Comment by walmyrcarvalho** [comment]
@rsicarelli Você acha que o tema é p/ iniciantes, intermediário ou avançado? Estou colocando umas labels pra identificar. :)

**Comment by rsicarelli** [comment]
@walmyrcarvalho intermediário!

**Comment by walmyrcarvalho** [comment]
Publicado! https://medium.com/android-dev-br/testes-unit%C3%A1rios-vs-aceita%C3%A7%C3%A3o-30691fc8578d#.ck2g06ubu
