### ISSUE TITLE
30/01/17 - Dependências duplicadas no Gradle - Rafa Araujo

### ISSUE THREAD

**Issue by orafaaraujo** [androiddevbr/agenda-medium#30]
* **Autor:** Rafael de Araújo
* **Perfil no medium:** medium.com/@orafaaraujo
* **Data escolhida:** 30/01/17
* **Título do artigo:** Dependências duplicadas no Gradle
* **Descrição:** Abordar o problema e dependências duplicadas no Gradle. Porque acontece, como investigá-las e como resolve-las.

**Rascunho:** https://medium.com/@orafaaraujo/depend%C3%AAncias-duplicadas-no-gradle-8bf2a25fccbc

**Comment by davidtcdeveloper** [comment]
Oi @orafaaraujo, quando o post estiver concluído por favor avisa para a gente revisar de novo ;)

**Comment by douglasdrumond** [comment]
Oi @orafaaraujo, ainda pretende submeter esse artigo?

**Comment by orafaaraujo** [comment]
Sim, por isso deixei ele aberto ainda... Só falta pequenos ajustes para liberar. Tentarei esta semana.

**Comment by douglasdrumond** [comment]
Blz, valeu!
