### ISSUE TITLE
13/02/17 - SOLID no Android - Iago Mendes Fucolo

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#31]
* **Autor:** Iago Mendes Fucolo
* **Perfil no medium:** medium.com/@iagofucolo
* **Data escolhida:** 13/02/17
* **Título do artigo:**  https://medium.com/@iagofucolo/s-o-l-i-d-no-android-d55e23f1c72d#.q2taz6481
* **Descrição:** Escrevi um artigo sobre a aplicação de SOLID no Android como aprendizado  e gostaria de compartilhar com a comunidade para que todos possam utilizar em seus códigos esses princípios

**Comment by ifucolo** [comment]
feito as correções

**Comment by douglasdrumond** [comment]
@ifucolo Deixei alguns comentários e tem umas sugestões do David a serem endereçadas

**Comment by ifucolo** [comment]
Boa, já arrumei la
