### ISSUE TITLE
13/02/17 - Comunicação TCP/IP entre um App Android e uma ESP8266 - Cézar Antonio de Sousa

### ISSUE THREAD

**Issue by cezarant** [androiddevbr/agenda-medium#32]
* **Autor:** Cézar Antonio de Sousa 
* **Perfil no medium:**https://medium.com/@czarantoniodesouza
* **Data escolhida:** 13/02/17
* **Título do artigo:** Comunicação Socket entre um App Android e uma ESP8266. 
* **Descrição:** Com dispositivos embarcados, as vezes temos que realizar a comunicação utilizando Sockets. Este artigo detalha um pouco os desafios e soluções que encontrei ao fazer um aplicativo Android se comunicar com uma placa de IoT ESP8266-12, utilizando Sockets. O artigo já foi publicado em meu perfil: http://migre.me/w1ily.

**Comment by davidtcdeveloper** [comment]
Oi @cezarant, te adicionei como escritor na nossa publicação. Agora precisamos que você adicione o post à publicação para que a gente possa revisar ;)

**Comment by cezarant** [comment]
Alteracoes no texto realizadas. Irei gravar os videos novamente, pra ficarem mais didaticos

**Comment by douglasdrumond** [comment]
@cezarant Submeteu p/ nossa publicação?

**Comment by cezarant** [comment]
Olá Douglas, acredito que sim. Fiz as modificações e publiquei novamente.

**Comment by cezarant** [comment]
Na questão dos vídeos ainda estou finalizando. Mas estava esperando o feedback do texto, se ficou OK.

**Comment by douglasdrumond** [comment]
OK. Deixei uns comentários e ainda tem uns do David a serem endereçados. Obrigado =)

**Comment by cezarant** [comment]
Pessoal, corrigi os apontamentos que vocês fizeram e só ficou faltando a regravação dos vídeos. Porém, gostaria de um feedback se há alguma previsão de publicação do artigo.
