### ISSUE TITLE
06/03/17 - Transição, Zoom Pinch e Drag to back de ImageView - Iago Mendes Fucolo

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#33]
* **Autor:** Iago Mendes Fucolo
* **Perfil no medium:** https://medium.com/@iagofucolo
* **Data escolhida:** 06/03/17
* **Título do artigo:** Transição, Zoom Pinch e Drag to back de ImageView 
* **Descrição:** Quero nesse artigo explicar como fazer transição de imagens entre views de forma fluida, drag to back, e ZoomPinch cal

**Comment by ifucolo** [comment]
feito as correções

**Comment by douglasdrumond** [comment]
@ifucolo Apagou o artigo? Não encontro.

**Comment by ifucolo** [comment]
Não apaguei, ele é um draft ainda

**Comment by ifucolo** [comment]
alguma previsão para a postagem?
