### ISSUE TITLE
01/05/17 - Dominando seus logs com o Timber - Thiago Passos

### ISSUE THREAD

**Issue by burnermanx** [androiddevbr/agenda-medium#36]
* **Autor:** Thiago Passos
* **Perfil no medium:** medium.com/@thiagompassos
* **Data escolhida:** 01/05/17
* **Título do artigo:** Dominando seus logs com o Timber
* **Descrição:** Gostaria de abordar sobre tratamentos de Log para o Logcat e apresentar a biblioteca Timber, que tem outras utilidades bem interessantes além de simplesmente mandar logs ao Logcat.

**Comment by davidtcdeveloper** [comment]
Oi @burnermanx 
Seria este post aqui: https://medium.com/@thiagompassos/dominando-seus-logs-com-o-timber-8e9730b2090b ?
Te adicionei como escritor da nossa publicação. Poderia adicionar o post a publicação para que a gente possa fazer a revisão certinho?

**Comment by burnermanx** [comment]
Opa esse mesmo. Farei isso
