### ISSUE TITLE
08/05/17 - Usando styles do Android com a Anko

### ISSUE THREAD

**Issue by jonathanrz** [androiddevbr/agenda-medium#37]
* **Autor:** Jonathan Rafael Zanella 
* **Perfil no medium:** medium.com/@jonathanrafaelzanella
* **Data escolhida:** 08/05/17 - porém pode ser publicado em outra data.
* **Título do artigo:** Usando styles do Android com a Anko
* **Descrição:** A ideia do artigo é explicar uma abordagem alternativa que eu desenvolvi para continuar seguindo um padrão que eu já seguia, porém migrando para a DSL da Anko.
* **Link para o artigo:** https://medium.com/@jonathanrafaelzanella/usando-styles-do-android-com-a-anko-c99b39542e76

**Comment by douglasdrumond** [comment]
@jonathanrz Te adicionei como escritor, agora você consegue submeter esse artigo p/ https://medium.com/android-dev-br
