### ISSUE TITLE
15/05/17 - Faça seu app bilhar: Como transformar um botão em um load spinner

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [androiddevbr/agenda-medium#38]
* **Autor:** Leandro Borges Ferreia
* **Perfil no medium:** https://medium.com/@lehen01
* **Data escolhida:** 15/05/17 - Pode ser outra dada
* **Título do artigo:** Faça seu app bilhar: Como transformar um botão em um load spinner
* **Descrição:** Esse artigo é um tutorial de como fazer um botão se transformar em um loading spinner. É um exemplo interessante de componente customizado de UI, através do mesmo conceito pode-se fazer vários outros tipos de layouts.

**Comment by douglasdrumond** [comment]
@leandroBorgesFerreira Te adicionei como escritor, agora você consegue submeter o artigo p/ https://medium.com/android-dev-br

**Comment by leandroBorgesFerreira** [comment]
Oi Douglas. Não ficou muito claro para mim quando eu devo publicar o artigo... Publico agora?
