### ISSUE TITLE
05/06/17 - O que seu time precisa saber para desenvolver um aplicativo Android

### ISSUE THREAD

**Issue by RichardSilveira** [androiddevbr/agenda-medium#39]
* **Autor:** Richard Lee da Silva Silveira
* **Perfil no medium:** medium.com/@richardleecba
* **Data escolhida:** 05/06/17
* **Título do artigo:** O que seu time precisa saber para desenvolver um aplicativo Android
* **Descrição:** Sou Arquiteto de Sistemas do Tribunal de Justiça de MT e iremos começar uma fase de desenvolvimento de aplicativos (fase que passei inclusive na empresa que trabalhei anteriormente). Para essa empreitada e novo rumo em uma empresa de desenvolvimento de software, é importante o time, **desenvolvedores, gestores, testers, UX Designers** entenderem alguns conceitos e práticas acerca do desenvolvimento de apps Android. Gostaria de abordar temas como Estratégias de Desenvolvimento, Experiência de Usuário, Engajamento e Qualidade nesse artigo.

* Postei um artigo no [linkedin](https://www.linkedin.com/pulse/desenvolvendo-um-app-android-de-sucesso-richard-lee)

* Criei um app específicamente para esse artigo, o código-fonte está no [github](https://github.com/RichardSilveira/MoviesOfTheYear) e foi publicado na [PlayStore](https://play.google.com/store/apps/details?id=com.richardlee.moviesoftheyear)

**Comment by douglasdrumond** [comment]
Oi Richard,

O artigo ficou muito genérico e foge um pouco da linha editorial do AndroidDevBR, com artigos mais focados e mais aprofundados tecnicamente. 

Se tiver interesse, acho que dele daria p/ tirar vários outros artigos excelentes, basta aprofundar um pouco nos temas.

Qualquer coisa, nos procure no canal #meta no Slack e não se sinta desencorajado a publicar no medium da comunidade.

De qualquer forma, obrigado pela submissão da proposta
