### ISSUE TITLE
23/05/16 - Novidades Android Google I/O '16 -  Bruno Scrok Brunoro

### ISSUE THREAD

**Issue by brunosbrunoro** [androiddevbr/agenda-medium#4]
- **Autor:** Bruno Scrok Brunoro
- **Data escolhida:** 23/05/16
- **Título do artigo:** Novidades Android Google I/O '16
- **Descrição:** Vou contar todas as novidades do Google I/O 16 com relação ao Android

**Comment by walmyrcarvalho** [comment]
Boa Bruno, feito! :)

**Comment by walmyrcarvalho** [comment]
Só vou editar o título com o teu nome. o/

**Comment by walmyrcarvalho** [comment]
@brunosbrunoro Algum update em relação aos ajustes sugeridos? Tu quer alguma ajuda?

**Comment by brunosbrunoro** [comment]
Ei fiz os update solicitados, estava aguardando a revisão

**Comment by walmyrcarvalho** [comment]
@brunosbrunoro Certo, vamos revisar de novo e te atualizamos pelo Slack! :)
