### ISSUE TITLE
16/06/2017 - Uma introdução aos Instant Apps - Mateus Gondim

### ISSUE THREAD

**Issue by mateusgrb** [androiddevbr/agenda-medium#40]
* **Autor:** Mateus Gondim
* **Perfil no medium:** https://medium.com/@mateusgondim
* **Data escolhida:** 16/06/2017
* **Título do artigo:** Uma introdução aos Instant Apps
* **Descrição:** Gostaria de fazer uma introdução aos Instant Apps, com teoria e prática. A ideia é falar o que são, qual sua utilidade, como funcionam, etc, e mostrar a criação de um projeto muito simples seguindo o wizard do Android Studio, para comentar sua estrutura.

Meu deadline para terminar o artigo é a próxima quarta(14/06), então coloquei dia 16 no título para ter um tempo de revisão. Que acham?

**Comment by mateusgrb** [comment]
Rascunho já tá engatilhado =P

**Comment by douglasdrumond** [comment]
Manda bala. Qual o nível do post? Intermediário ou avançado?

**Comment by mateusgrb** [comment]
Acabei já postando no meu medium: https://medium.com/@mateusgondim/uma-introdução-aos-android-instant-apps-5027c74434ee 
Diria nível intermediário.

**Comment by davidtcdeveloper** [comment]
@mateusgrb Te adicionei como escritor na nossa publicação. Pode submeter o post para a gente revisar :)

**Comment by davidtcdeveloper** [comment]
@mateusgrb Estamos aguardando você adicionar o post à nossa publicação para fazer a revisão ;)

**Comment by mateusgrb** [comment]
@davidtcdeveloper Como acabei já postando este texto há um tempo atrás no meu medium, acho q não faz muito sentido postar de novo. Pode fechar esta issue, e pretendo em breve submeter uma nova proposta sobre outro tópico. Obrigado!

**Comment by davidtcdeveloper** [comment]
Beleza @mateusgrb 
Aguardamos a nova publicação :)
