### ISSUE TITLE
10/07/17 - Custom Exoplayer em Kotlin

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#41]
* **Autor:** Iago Mendes Fucolo
* **Perfil no medium:** medium.com/@iagofucolo
* **Data escolhida:** 10/07/17
* **Título do artigo:**Custom Exoplayer em Kotlin
* **Descrição:**  Vou falar bem objetivamente como desenvolver um player usando o framework Exoplayer em kotlin com layout custom

**Comment by douglasdrumond** [comment]
@ifucolo O tema é interessante. Qual o nível? Iniciante, intermediário ou avançado? Manda bala no post e, se quiser uma mão, ping no Slack :)

**Comment by ifucolo** [comment]
Blz, o nivel é intermediário, estou começando a escrever ele e qualquer coisa prendo o grito

**Comment by ifucolo** [comment]
https://medium.com/p/906d96b79807/edit 90% pronto, no aguardo dos reviews

**Comment by ifucolo** [comment]
Alguma previsão de publicação ?

**Comment by douglasdrumond** [comment]
Nos enrolamos, mas agora foi
