### ISSUE TITLE
24/07/17 - Validação de formuláriosem Android - Wellington Costa

### ISSUE THREAD

**Issue by WellingtonCosta** [androiddevbr/agenda-medium#42]
* **Autor:** Wellington Costa
* **Perfil no Medium:** https://medium.com/@wellingtoncosta128
* **Data escolhida:** 24/07/17
* **Título do artigo:** Validação de formuláriosem Android
* **Descrição:** Gostaria de falar um pouco sobre uma lib que desenvolvi como parte do trabalho de conclusão de curso da minha pós graduação que tem como objetivo facilitar a vida do desenvolvedor quando se trata de validações de campos.

* **Link do post no meu Medium:** https://medium.com/@wellingtoncosta128/validação-de-formulários-em-android-25af8e942aad

**Comment by davidtcdeveloper** [comment]
Oi @WellingtonCosta 
Agradecemos o interesse em participar da nossa publicação.

Revisamos seu artigo aqui e temos alguns pontos para considerar:
- O termo _Formulário_ não é muito comum no mundo Android e lembra muito frameworks web e afins. Sugerimos que ajuste o texto para algo mais próximo do mundo Android, relacionado à Activities, Fragments, Views e afins.
- O texto foca muito em como usar a lib. Sugerimos que ajuste para focar mais no desenvolvimento da lib e dos próprios componentes, como forma de demonstrar como criar bibliotecas e componentes reutilizáveis no mundo Android.

**Comment by WellingtonCosta** [comment]
Oi, @davidtcdeveloper 

Agradeço o feedback e já ajustei o post quanto ao primeiro ponto que você levantou.
Quanto ao segundo ponto, eu escrevi o post justamente para que os leitores tomem conhecimento da lib, como utilizá-la e ainda falei um pouquinho de como ela funciona e os conceitos envolvidos.

Vejo que não teria muito sentido em adaptar o post para explicar como criar componentes reutilizáveis e afins, pois já existe um post que fala justamente sobre isso.

**Link do post:** https://medium.com/android-dev-br/annotation-processing-no-android-d28b734b8043

Grato!

**Comment by douglasdrumond** [comment]
Oi @WellingtonCosta,

A ideia de explicar como o processamento de anotações funciona é legal. Apesar de já existir um post sobre isso, publicar outro que tivesse uma abordagem diferente ou mostrasse alguma característica não apresentada, alguma armadilha que o desenvolvedor deve prestar atenção ou algo assim seria totalmente válido.

No entanto, essa publicação é o manual da lib e não vejo muito sentido (editorialmente falando) em publicá-lo no Medium desse jeito. Uma publicação simplesmente divulgando a lib não é o propósito do Medium Android Dev BR. Faz mais sentido publicar a lib nos canais `#feedback` e `#opensource` no Slack, que são os locais para divulgação de apps e libs desenvolvidos (obviamente, como o nome diz, em `#opensource` o código precisa ser aberto).

Espero que compreenda.

**Comment by WellingtonCosta** [comment]
Ok. Teria como me colocar no grupo do Slack para que eu possa divulgar a lib, pois creio que seja de grande utilidade para muitos desenvolvedores.

Em paralelo vou escrever um outro post fazendo uma abordagem mais intrínseca da lib, explicando a arquitetura, como foi implementada, as dependências utilizadas e algumas dicas sobre trabalhar com Annotation Processing, para que assim eu consiga, de facto, postar no Android Dev BR.

No mais, fico grato pelos feedbacks e fico no aguardo sobre o Slack.

**Comment by douglasdrumond** [comment]
@WellingtonCosta https://slack.androiddevbr.org

**Comment by WellingtonCosta** [comment]
Obrigado! :)
