### ISSUE TITLE
20/07/17 - Utilizando Room Database no Android - Gabriel Prado

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#43]
* **Autor:** Gabriel Prado
* **Perfil no medium:** https://medium.com/@gabrielprado_70441
* **Data escolhida:** 24/07/17
* **Título do artigo:** Utilizando Room Database no Android
* **Descrição:** Gostaria de levar conhecimento a comunidade sobre a utilização da bibliotéca Room, que faz parte do conceito de Architeture Components (apresentado no Google IO de 2017).

**Comment by davidtcdeveloper** [comment]
@sp4wna1 Conseguiu evoluir naqueles comentários que adicionamos ao texto?
Quando tiver concluído, por favor comente aqui para que façamos uma nova revisão.

**Comment by orafaaraujo** [comment]
Olá, @sp4wna1 
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. 👍

**Comment by sp4wna1** [comment]
Olá @orafaaraujo e @davidtcdeveloper, realizei os ajustes porem esqueci de notificar.

**Comment by orafaaraujo** [comment]
Vou tentar revisar hoje e já planejamos uma publicação, @sp4wna1 

Abraços

**Comment by orafaaraujo** [comment]
Link: https://medium.com/@sp4wna1/utilizando-room-database-no-android-fd76c2e6ccee

**Comment by sp4wna1** [comment]
@orafaaraujo Fiz o ajuste. Obrigado
