### ISSUE TITLE
Melhorando a segurança app Android pt 1 - Gildênio Neto

### ISSUE THREAD

**Issue by netok99** [androiddevbr/agenda-medium#44]
* **Autor:** Gildênio Neto
* **Perfil no medium:** medium.com/@netok99
* **Data escolhida:** 25/07/17
* **Título do artigo:** Melhorando a segurança app Android pt 1
* **Descrição:** Uma série dividida em duas partes para melhorar a segurança dos aplicativos que produzimos. Ultimamente tenho encarado alguns desafios de segurança e quero compartilhar algumas informações sobre o assunto.

Texto em edição: https://medium.com/@netok99/melhorando-a-seguran%C3%A7a-app-android-pt-1-ab925dc0b77c

**Comment by douglasdrumond** [comment]
Manda bala, @netok99 Se precisar de qualquer coisa, chame a gente no Slack

**Comment by douglasdrumond** [comment]
@netok99 Te adicionei como escritor no Medium. Quando estiver pronto, basta submeter pelo Medium mesmo e seremos notificados para revisão e aprovação.

**Comment by davidtcdeveloper** [comment]
@netok99 Temos alguns comentários pendentes  no post ainda.
Poderia revisar e comentar aqui quando tiver concluído?

**Comment by netok99** [comment]
Vou ver isso segunda para subirmos isso rápido.

Em 30 de set de 2017 11:14, "David Tiago Conceição" <
notifications@github.com> escreveu:

**Comment by netok99** [comment]
Poderiam dar uma revisada lá agora?

**Comment by davidtcdeveloper** [comment]
@netok99 Vou dar dismiss em todas as notas e começar de novo, para facilitar a revisão.
Quando resolver algum ponto citado, por favor, dê dismiss nos comentários também ;)

**Comment by davidtcdeveloper** [comment]
Acabei de revisar o post e acabei incluindo notas muito parecidas com as que já existiam.
Acredito que o post ainda pode evoluir.
Uma coisa que acabei notando é que ele é uma mistura de vários pontos diferentes, alguns explicados bem por cima e alguns com muito detalhes, como é o caso do NDK.
Uma sugestão minha é quebrar a série em muito mais posts. Talvez um focado no NDK, como usar as coisas básicas e proteger o código.
Outro só focado na troca de informações entre os aplicativos.
Outro só focado no proguard, como o código pode ser decompilado e etc.
Acho que desta forma você terá vários posts com bem mais detalhes e bem mais produtivos.

**Comment by orafaaraujo** [comment]
Olá, @netok99  
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. 👍

**Comment by orafaaraujo** [comment]
Fechando a issue.
Podemos reabri-la caso há novidades, ok?

Abraços
