### ISSUE TITLE
04/09/2017 - Adotando Dagger2: Todos os passos necessários - Allan Yoshio Hasegawa

### ISSUE THREAD

**Issue by AllanHasegawa** [androiddevbr/agenda-medium#45]
* **Autor:** Allan Yoshio Hasegawa
* **Perfil no medium:** medium.com/@AllanHasegawa
* **Data escolhida:** 04/09/2017
* **Título do artigo:** Adotando Dagger2: Todos os passos necessários
* **Descrição:** Um projeto mostrando todos os passos necessários para que se possa utilizar Dagger2. A ideia é pegar um app mal codificado, com o código todo bagunçado, e ir refatorando ele até chegar em uma solução limpa.

Link em inglês: https://medium.com/@AllanHasegawa/lets-learn-dagger2-by-refactoring-a-poorly-coded-android-app-a5015a8ae108

(O post seria a tradução do link em inglês, e com as modificações necessárias)

---

E ai pessoal do AndroidDevBr, tudo bem?

Não sei se meu post é algo compatível com uma publicação, pois ele é bem extenso. Mas é algo que eu gostaria de ter lido quando comecei a aprender sobre essas coisas.

Enfim, qualquer feedback é bem vindo.

**Comment by douglasdrumond** [comment]
Show de bola

**Comment by AllanHasegawa** [comment]
Ola @douglasdrumond o/

Isso significa que posso começar a escrita do artigo em pt-br? Estou pensando em re-escrever (não só traduzir) algumas partes, e por isso pode demorar um pouco.

**Comment by davidtcdeveloper** [comment]
Excelente post @AllanHasegawa! Quando tiver novidades por favor nos avise.

**Comment by AllanHasegawa** [comment]
Olá @davidtcdeveloper o/

Desculpa a demora! Acabei revisando todo o post e fiz várias modificações, mas o draft está pronto.

**Comment by davidtcdeveloper** [comment]
@AllanHasegawa Ainda não consegui revisar, pretendo fazer isso hoje.
Obrigado pela resposta.

**Comment by AllanHasegawa** [comment]
@davidtcdeveloper 

Segue o link do draft com a versão melhorada:  https://medium.com/@AllanHasegawa/adotando-dagger2-todos-os-passos-necess%C3%A1rios-91bdf8567206

**Comment by davidtcdeveloper** [comment]
@AllanHasegawa Vi o post mas não consegui ler com calma.
Reservei um tempo para ler com atenção amanhã.
Enquanto isso, poderia adicionar à nossa publicação? Assim consigo fazer comentários que são privados mas visíveis para os outros editores.

**Comment by AllanHasegawa** [comment]
@davidtcdeveloper Pronto :) Enviei o draft para vocês.

**Comment by davidtcdeveloper** [comment]
Show, assim que terminar a revisão comento aqui.

**Comment by davidtcdeveloper** [comment]
Revisamos o post, está excelente!
Provavelmente publicaremos ele em breve.

**Comment by davidtcdeveloper** [comment]
Post publicado!
https://medium.com/android-dev-br/adotando-dagger2-todos-os-passos-necess%C3%A1rios-91bdf8567206

**Comment by AllanHasegawa** [comment]
Show! Muito Obrigado @davidtcdeveloper  !
