### ISSUE TITLE
26/09/2017 - Adeus XML. Muito prazer, Anko. - Jefferson Tavares de Pádua

### ISSUE THREAD

**Issue by jeffersontpadua** [androiddevbr/agenda-medium#46]
* **Autor:** Jefferson Tavares de Pádua
* **Perfil no medium:** medium.com/@jeffersontpadua
* **Data escolhida:** 02/10/2017
* **Título do artigo:** Adeus XML. Muito prazer, Anko.
* **Descrição:** Nesse artigo (que é uma sequência de 5) faço uma introdução sobre como utilizar a biblioteca Anko Layouts para o desenvolvimento de interfaces no Android.

**Comment by douglasdrumond** [comment]
manda bala!

**Comment by jeffersontpadua** [comment]
OMG. O que eu faço agora? *--*

**Comment by davidtcdeveloper** [comment]
@jeffersontpadua Você pode escrever o post no Medium, adicionar à nossa publicação e aguardar a revisão.

**Comment by davidtcdeveloper** [comment]
@jeffersontpadua Te adicionei como escritor da nossa publicação.

**Comment by davidtcdeveloper** [comment]
@jeffersontpadua Revisei o post e coloquei alguns comentários :)

**Comment by jeffersontpadua** [comment]
Ok, farei uma revisão e entrarei em contato novamente.

**Comment by jeffersontpadua** [comment]
Reestruturei o meu post. Pode dar uma olhada novamente?
https://medium.com/@jeffersontpadua/adeus-xml-muito-prazer-anko-1-9ba3d16ff9b1

**Comment by davidtcdeveloper** [comment]
@jeffersontpadua Revisarei o post hoje ainda e te mando novidades.

**Comment by davidtcdeveloper** [comment]
@jeffersontpadua O post evoluiu muito!
A explicação do código em etapas ficou bem mais clara e bem interessante.
Os pontos negativos no final ficaram legais também.
Coloquei comentários pontuais de pequenos ajustes sugeridos.
De qualquer forma, acredito que está bem próximo de uma versão final.

**Comment by orafaaraujo** [comment]
Olá, @jeffersontpadua   
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. 👍
