### ISSUE TITLE
06/10/17 - Como usar Singleton e Observer para comunicação de eventos no Android - José Vieira

### ISSUE THREAD

**Issue by NetoDevel** [androiddevbr/agenda-medium#48]
* **Autor:** José Vieira Neto
* **Perfil no medium:** https://medium.com/@josevieiraneto
* **Data escolhida:** 10/10/17
* **Título do artigo:** Como usar Singleton e Observer para comunicação de eventos no Android
* **Descrição:** Gostaria de falar um pouco mais sobre como usar padrões de projetos evitando muitas vezes em adicionar uma lib de terceiros.

**Já foi publicado!**
**Link:** https://medium.com/@josevieiraneto/como-usar-singleton-e-observer-para-comunica%C3%A7%C3%A3o-de-eventos-no-android-6777b65553b6

**Comment by davidtcdeveloper** [comment]
@NetoDevel Obrigado pela sua contribuição.
Acabei de ler seu post e acho que ele tem algumas situações que precisam ser resolvidas antes.
O listener do evento, por exemplo, é registrado e nunca é removido, o que configura um leak de memória.
Outro ponto importante é que este post vai diretamente contra outro que já tempos publicado: https://medium.com/android-dev-br/guerra-contra-singletons-721ab89aa94
Precisamos que seu post leve em consideração os pontos citados nestre outro, caso contrário teremos uma inconsistência grande na nossa publicação.

**Comment by NetoDevel** [comment]
@davidtcdeveloper tranquilo, vou fazer as alterações mencionadas acima. Obrigado.

**Comment by NetoDevel** [comment]
@davidtcdeveloper fiz algumas citações sobre o uso do singleton e o foco do artigo, e as alterações mencionadas.

**Comment by orafaaraujo** [comment]
Olá, @NetoDevel   
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. 👍

**Comment by NetoDevel** [comment]
Olá, @orafaaraujo 
Meu tempo realmente apertou para concluir as alterações pedidas, se quiser pode fechar a issue, quando eu terminar eu dou um toque lá no slack do `androiddev`, qualquer ajuda para terminar é bem-vinda também :+1:

**Comment by orafaaraujo** [comment]
Olá, @NetoDevel 
Okay, fique tranquilo.

Estamos abertos a novos posts. Qualquer dúvida, nos procure. :)
