### ISSUE TITLE
08/11/17 - Implementando um cache para o Room com BehaviorSubject - Jonathan Zanella

### ISSUE THREAD

**Issue by jonathanrz** [androiddevbr/agenda-medium#49]
* **Autor:** Jonathan Zanella
* **Perfil no medium:** medium.com/@jonathanrz
* **Data escolhida:** Quando acharem melhor.
* **Título do artigo:** Implementando um cache para o Room com BehaviorSubject
* **Descrição:** Eu decidi implementar na mão o mesmo comportamento que o Room prove quando você define o retorno do Dao como Flowable com o intuito de estudar RX.

Link para o post: https://medium.com/tech-track/implementando-um-cache-para-o-room-com-behaviorsubject-2b48dc7ed69b
Fiz outra cópia do post e já submeti pra revisão no medium do android dev br.

**Comment by davidtcdeveloper** [comment]
@jonathanrz Só para alinhar: o post foi publicado em algum momento mas não entendemos bem o motivo. Vamos ajustar esses comentários que a gente fez e depois anunciamos ele no slack, ok?
