### ISSUE TITLE
09/05/16 - Validando dados com Android Saripaar 2 - Felipe Oliveira

### ISSUE THREAD

**Issue by oliveiradev** [androiddevbr/agenda-medium#5]
* **Autor:** Felipe Oliveira
* **Data escolhida:** 30/05/16
* **Título do artigo:**  Validando dados com Android Saripaar 2
* **Descrição:** Mostrar um pouco sobre a lib Android Saripaar 2. A idéia do meu artigo é falar sobre a lib e mostrar uma pequena implementação de como podemos validar nossos forms .

**Comment by rsicarelli** [comment]
Muito bom! Uma sugestão: mostrar, por cima, como fazer uma custom validation (https://github.com/ragunathjawahar/android-saripaar/tree/master/saripaar-tests/src/main/java/com/mobsandgeeks/saripaar/tests/ui/validation)

**Comment by oliveiradev** [comment]
@rsicarelli eu já escrevi, achei q ia ficar um pouco longo se eu mostrasse nesse post, mas já falei no post que da pra criar as regras customizadas e que falarei sobre isso em outro post. :/

**Comment by davidtcdeveloper** [comment]
@oliveiradev: Ótimo post, obrigado pela contribuição.
Anotei algumas sugestões lá no medium.
Obrigado.

**Comment by walmyrcarvalho** [comment]
Obrigado @oliveiradev pela contribuição, bem interessante o assunto! :)

**Comment by oliveiradev** [comment]
@walmyrcarvalho e @davidtcdeveloper obrigado , sempre que eu puder vou estar por aqui kk

**Comment by walmyrcarvalho** [comment]
@oliveiradev Você acha que o tema é p/ iniciantes, intermediário ou avançado? Estou colocando umas labels pra identificar. :)

**Comment by oliveiradev** [comment]
@walmyrcarvalho o post é bem simples ao meu ver é iniciante , mas cabe um intermediário também , fica ao seu critério

**Comment by rsicarelli** [comment]
@oliveiradev Tem algum problema de adiantarmos seu post para hoje, **09/05/16**?

**Comment by oliveiradev** [comment]
sem problemas @rsicarelli

**Comment by walmyrcarvalho** [comment]
Publicado! https://medium.com/android-dev-br/validando-dados-com-android-saripaar-2-9b76842bb86b#.t239c3iyr

**Comment by walmyrcarvalho** [comment]
Data atualizada pois o post foi antecipado. :)
