### ISSUE TITLE
Kotlin Extension Functions - Novos Horizontes para o Framework Android

### ISSUE THREAD

**Issue by jeffersontpadua** [androiddevbr/agenda-medium#50]
* **Autor:** Jefferson Tavares de Pádua
* **Perfil no medium:** medium.com/@jeffersontpadua
* **Data escolhida:** 22/01/2018
* **Título do artigo:** Kotlin Extension Functions - Novos Horizontes para o Framework Android
* **Descrição:** Devido à recente popularidade da linguagem Kotlin, gostaria de expor as vantagens de se utilizar Extension Functions como alternativa à criação de arquivos *Util.

**Comment by davidtcdeveloper** [comment]
Ótima ideia de post @jeffersontpadua 
Farei a revisão do post hoje.

**Comment by jeffersontpadua** [comment]
Obrigado :) Estou no aguardo ^^

**Comment by davidtcdeveloper** [comment]
Revisei o post e adicionei alguns comentários. Se tiver alguma dúvida ou outro comentário, pode me responder pelo Medium mesmo :)

**Comment by jeffersontpadua** [comment]
Obrigado pelo feedback. As revisões que você havia feito foram corrigidas. Qual é o próximo passo?

**Comment by davidtcdeveloper** [comment]
Vou revisar o post inteiro e qualquer coisa comento por lá.
Obrigado pela resposta rápida.

**Comment by orafaaraujo** [comment]
Link da publicação
https://medium.com/android-dev-br/kotlin-extension-functions-novos-horizontes-para-o-framework-android-ba7d2782fecf
