### ISSUE TITLE
01/03/2018 - Android e arquitetura MVVM

### ISSUE THREAD

**Issue by fdias** [androiddevbr/agenda-medium#51]
Autor: Fernando Dias Silva
Perfil no medium: medium.com/@fernandodias_8236
Data planejada: 01/03/2018
Título do artigo: Android e a arquitetura MVVM
Descrição: Eu gostaria de falar um pouco sobre como a arquitetura MVVM nos auxilia na criação de um projeto Android junto com a tão falada arquitetura de componentes.

**Comment by orafaaraujo** [comment]
Olá, @fdias 
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. :+1:
