### ISSUE TITLE
Começando com Android Databinding

### ISSUE THREAD

**Issue by WellingtonCosta** [androiddevbr/agenda-medium#52]
* **Autor:** Wellington Costa
* **Perfil no medium:** https://medium.com/@wellingtoncosta128
* **Data escolhida:** 01/03/18
* **Título do artigo:** Começando com Android Databinding
* **Descrição:** Este artigo tem como objetivo principal fazer uma abordagem introdutória sobre a Android Databinding Library, destacando seus benefícios e como o código pode se tornar mais limpo com a sua utilização.

**Comment by orafaaraujo** [comment]
Olá, @WellingtonCosta 
Estamos revisando as propostas e gostaria de saber você tem alguma novidade sobre este post.
Se precisar de alguma coisa nos avise. :+1:

**Comment by WellingtonCosta** [comment]
Oi, @orafaaraujo

Irei organizar o post e assim que tiver uma versão para revisão, eu aviso. Ok?

**Comment by orafaaraujo** [comment]
Olá, @WellingtonCosta 
alguma novidade?
Abraços

**Comment by WellingtonCosta** [comment]
Oi @orafaaraujo. Desculpe pela demora em responder. Estava ocupado com umas palestras que vim ministrar aqui no FISL 18. No decorrer da próxima semana te mando uma versão do artigo para que vocês possam revisar.

**Comment by WellingtonCosta** [comment]
Oi @orafaaraujo eu acabei vendo aqui já existe um artigo no Android Dev BR falando sobre Databinding. Teria muita relevância escrever outro?

Eu tenho vontade de escrever um artigo (na verdade já escrevi, mas precisaria atualizar) sobre uma bibliote baseada em anotações e geração de código (também pode ser utilizada via Databinding) para tratar de validação de campos. O que vocâ acha?

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 
Qual post sobre DataBinding? Dei uma olhada e não encontrei.

De qualquer forma, faça o o post que achar mais confortável. 
Sobre o tema de anotações eu acho que seria interessante mostrar como funciona as anotações por trás, como criar e usar. E aí como exemplo você pode usar a biblioteca. O que acha?

Abraços

**Comment by WellingtonCosta** [comment]
Eu achei esse [post](https://medium.com/android-dev-br/introdu%C3%A7%C3%A3o-ao-android-data-binding-d0a528e52883) sobre Databinding. A sua sugestão também parece ser bem interessante. Você acha que eu poderia escrever um novo post sobre Databinding ou escrever sobre annotations e annotation processing, tomando minha lib como exemplo?

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Este post é de 2015, se desejar pode falar das mudanças. Agora não é mais necessário importar a depedencia, faz parte do JetPack, prós e contras, o que fazer e o que não fazer, testes etc. Então se quiser pode seguir esta linha.
Sobre a sua lib, sem problemas. Mas foque na criação dela, para que outras pessoas também possam criar as suas libs dela. Faça o post que você gostaria de ter lido quando pensou em fazer a sua lib hahahaha o que acha?

Abraços

**Comment by WellingtonCosta** [comment]
É exatamente isso o que estava escrevendo no artigo sobre Databinding. hahaha.

Sobre a minha lib, eu acho sua ideia bacana.

Vou focar primeiro no artigo sobre o Databinding. Depois penso em algo sobre annotations / annotation processing.

**Comment by WellingtonCosta** [comment]
Oi, @orafaaraujo 

Conclui a versão para revisão do artigo. Está disponível [neste link](https://medium.com/@wellingtoncosta128/come%C3%A7ando-com-android-data-binding-d7719333eecc).

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Deixei alguns pequenos pontos de correção mas o artigo está show. Parabéns!

Abraços

**Comment by WellingtonCosta** [comment]
Eu estou acompanhando aqui. Todos os pontos que você levantou eu corrigi, exceto os pontos que você sugeriu usar o Markdown, porém não sei se isso funciona no Medium.

Tentei colocar o texto entre aspas invertidas mas sem sucesso.

**Comment by orafaaraujo** [comment]
Meu Medium está doidão.
Estou tentando colocar alguns links de apoio lá mas ele bagunça todo meu texto.
Olha este link
https://help.medium.com/hc/en-us/articles/224550008-Code-blocks-inline-code

Qlqr coisa me pinga no slack.

**Comment by WellingtonCosta** [comment]
Acho que o Medium caiu. hahaha

**Comment by WellingtonCosta** [comment]
Pra ficar mais fácil, vou transformar os textos que você sugeriu ficar em Markdown Gist com extensão .md

**Comment by WellingtonCosta** [comment]
OI @orafaaraujo 

Finalmente deu certo! hehe

**Comment by orafaaraujo** [comment]
@WellingtonCosta 
Te adicionei como writer no nosso medium. Submete lá que eu já publico.

Abraços

**Comment by WellingtonCosta** [comment]
Beleza, @orafaaraujo

**Comment by WellingtonCosta** [comment]
@orafaaraujo 

Submetido!

**Comment by orafaaraujo** [comment]
Publicado!
Amanha fazemos o anuncio no Slack. :)
