### ISSUE TITLE
01/03/18 - Animando as transições de Views em um aplicativo Android - Luciano Medeiros

### ISSUE THREAD

**Issue by lucamenor** [androiddevbr/agenda-medium#53]
* **Autor:** Luciano Carvalho de Medeiros Júnior
* **Perfil no medium:** medium.com/@lucamenor
* **Data escolhida:** 01/03/2018
* **Título do artigo:** Animando as transições de Views em um aplicativo Android
* **Descrição:** Utilizo como base um problema que eu tive, para detalhar um dos tipos de animações do Android. Vou fazendo o passo-a-passo que me levou a solução do problema e como ficou o resultado final da animação.
* **Link:** https://medium.com/@lucamenor/animando-as-transi%C3%A7%C3%B5es-de-views-em-um-aplicativo-android-add527b2544d

**Comment by orafaaraujo** [comment]
Olá, @lucamenor 
Parabéns pelo post, ficou bem explicativo e completo.

Deixei alguns comentários no Medium. Do mais, meus pontos são:
-Deixar todos os nomes em inglês, como views, tags, componentes em _itálico_.
-Transformar os vídeos em GIFs e adicionar legenda à eles.
-Tentar simplificar ou exemplificar melhor quais views estão sendo alteradas. As vezes com tantos ConstraintLayouts, CardViews, LinearLayouts eu me perdia na explicação. Talvez se falar também o que é aquela view ajuda na compreenção. 
-Como sugestão é deixar o post mais no impessoal, evitando "nós desejamos", "nossa view", "temos o método", etc.

Assim que finalizar os ajustes nos avise.
Abraços

**Comment by lucamenor** [comment]
Obrigado pela análise @orafaaraujo 
Assim que fizer os ajustes, notifico aqui.

**Comment by orafaaraujo** [comment]
Olá, @lucamenor 
Como andam os ajustes?

Abraços

**Comment by lucamenor** [comment]
Oi @orafaaraujo 
Fiz quase todos os ajustes que vc sugeriu, ficou faltando apenas transformar os videos em gifs. Tive problemas com meu notebook e estou sem computador pessoal, por isso n conclui ainda. Vc pode revisar do jeito que esta? Tentarei fazer o ponto dos gifs no computador de alguem. Ignore a falta de acentos, teclado com problema.

**Comment by orafaaraujo** [comment]
Sem problemas!

Vou revisar do jeito que está
Abraços

**Comment by lucamenor** [comment]
@orafaaraujo 
Troquei todos os vídeos por gifs e revisei uns pontos que faltavam. Acredito que esteja ok agora. Fico no aguardo.

**Comment by orafaaraujo** [comment]
Olá, @lucamenor 
Vamos publicar? :)

Só gostaria de te pedir para traduzir aquele trecho da definição do Material Design. Pode deixar os termos em inglês, só adicione uma tração... 

Já te adicionei como _writer_ no nosso medium. Depois que adicionar a tradução, submete no nosso medium e já podemos publicar.

Qualquer dúvida pode me chamar no Slack.
Abraços

**Comment by lucamenor** [comment]
Pronto @orafaaraujo adicionei uma tradução e submeti a publicação.

**Comment by orafaaraujo** [comment]
Obrigado, @lucamenor 
Já vou publicar.

Uma pergunta, você participa do nosso Slack? Qual o seu usuário lá?
É para a divulgação :)

Abraços

**Comment by lucamenor** [comment]
@orafaaraujo Acabei de me cadastrar lá. Só procurar por Luciano Medeiros. Valeu!
