### ISSUE TITLE
28/03/18 - Desenvolvimento com Android em 2018 - Thiago Santos

### ISSUE THREAD

**Issue by programadorthi** [androiddevbr/agenda-medium#54]
* **Autor:** Thiago Santos
* **Perfil no medium:** https://medium.com/@programadorthi
* **Data escolhida:** 28/03/18
* **Título do artigo:** Desenvolvimento com Android em 2018
* **Descrição:** O artigo mostra uma conversa entre um desenvolvedor que não está atualizado com as tecnologias e um desenvolvedor experiente que conhece o que o mercado e os padrões recomendam. A ideia do meu artigo é abordar, através de uma narrativa, como é o mundo do desenvolvimento Android no início do ano de 2018.
* **Link:** https://medium.com/@programadorthi/desenvolvimento-com-android-em-2018-a92d215754cb

**Comment by orafaaraujo** [comment]
Olá, @programadorthi 
Gostamos do seu post, é realmente o resumo da rotina de muitos desenvovledores Android nos dias atuais. 
No nosso medium buscamos publicações com enfoque voltado na busca de resoluções de problemas ou informações que ajudam ao desenvolvedor a tomar uma decisão.
Achamos que este tipo de post é mais pessoal porque envolve sua visão e opniões, portanto não vamos publicá-lo, tudo bem?
Estamos abertos a novas propostas.
Abraços
