### ISSUE TITLE
02/05/2018 - Utilizando JUnit 5 no Android - Pedro Henrique

### ISSUE THREAD

**Issue by pedrohfp** [androiddevbr/agenda-medium#55]
* **Autor:** Pedro Henrique
* **Perfil no medium:** https://medium.com/@pedrohfp
* **Data escolhida:** 09/05/18
* **Título do artigo:** Utilizando JUnit 5 no Android
* **Descrição:** Gostaria de falar um pouco sobre JUnit 5, algumas novidades e como começar a utilizar no Android.
* **Link:** https://medium.com/@pedrohfp/utilizando-junit-5-no-android-57464dd688a2

**Comment by pedrohfp** [comment]
Olá, @orafaaraujo 

Imagina, eu agradeço muito.

Pra mim está ótimo essa data, se precisar de alguma correção, só me avisar :) 

Abraços

**Comment by orafaaraujo** [comment]
Oi, @pedrohfp 
O seu post está muito bom.
Só deixei uma pequena anotação lá... 

Segunda que vem publicamos :)

Abraços

**Comment by pedrohfp** [comment]
Olá, @orafaaraujo 

Muito obrigado :)

Já arrumei o texto conforme seu comentário 

Grande Abraço

**Comment by orafaaraujo** [comment]
Oi, @pedrohfp 
Te coloquei como _writer_ lá, submete que a gente já publica.

Abraços!

**Comment by pedrohfp** [comment]
Olá, @orafaaraujo 

Acabei de submeter :) 

Abraços!!
