### ISSUE TITLE
14/05/18 - Novidades do Android no Google I/O 2018, para desenvolvedores

### ISSUE THREAD

**Issue by orafaaraujo** [androiddevbr/agenda-medium#56]
* **Autor:** Rafael Araujo
* **Perfil no medium:** medium.com/@orafaaraujo
* **Data escolhida:** 14/05/18
* **Título do artigo:** Novidades do Android no Google I/O 2018, para desenvolvedores
* **Descrição:** Dar um pequeno overview das novidades do Google I/O 18 voltado para os desenvovledores. Post já finalizado, posso subir para revisão?

**Comment by davidtcdeveloper** [comment]
@orafaaraujo pode enviar para a gente revisar sim :)

**Comment by orafaaraujo** [comment]
https://medium.com/@orafaaraujo/novidades-do-android-no-google-i-o-2018-para-desenvolvedores-10f952304bc6

Um amigo já fez uma pre-revisão e vou mudar algumas coisinhas, mas a ideia é uma leitura de 5 minutos sobre as novidades que são interessantes para os desenvolvedores.
