### ISSUE TITLE
01/06/2018 - WorkManager — O que é? Como usar? - Haldny Santos

### ISSUE THREAD

**Issue by haldny** [androiddevbr/agenda-medium#57]
* **Autor:** Haldny Santos
* **Perfil no medium:** medium.com/@haldnysantos
* **Link do post:** https://medium.com/@haldnysantos/workmanager-o-que-%C3%A9-como-usar-26f5b800984e
* **Data escolhida:** 01/06/18
* **Título do artigo:** WorkManager — O que é? Como usar?
* **Descrição:** Gostaria de falar um pouco sobre o WorkManager. A idéia do meu artigo é falar de forma introdutória sobre o assunto, dando exemplos simples para fins de demonstração.

**Comment by orafaaraujo** [comment]
Link da publicação
https://medium.com/android-dev-br/workmanager-o-que-%C3%A9-como-usar-26f5b800984e
