### ISSUE TITLE
Persistência de dados no Android com Room #1 - Criando Entidades

### ISSUE THREAD

**Issue by jeffersontpadua** [androiddevbr/agenda-medium#58]
* **Autor:** Jefferson Tavares de Pádua
* **Perfil no medium:** medium.com/@jeffersontpadua
* **Data escolhida:** 18/06/2018
* **Título do artigo:** Persistência de dados no Android com Room #1 - Criando Entidades
* **Descrição:** Nesse artigo, que é o primeiro de uma série, falo sobre como como criar entidades para persistência com a biblioteca Room, parte integrante do Android Architecture Components.

https://medium.com/@jeffersontpadua/persistência-de-dados-no-android-com-room-1-criando-entidades-c5e116413d05

**Comment by orafaaraujo** [comment]
Olá, @jeffersontpadua 
Já temos um post programado sobre Room, mas o seu é mais voltado para a criação de uma Entity pelo que vi.
Iremos avaliar se fazer sentido haver dois posts do "mesmo assunto" e te damos um retorno, ok?

Abraços

**Comment by jeffersontpadua** [comment]
Perfeito! De qualquer forma gostaria de receber o feedback de vocês em relação ao artigo, realmente ajuda muito!

**Comment by jeffersontpadua** [comment]
Pessoal, bom dia! Alguma novidade?

**Comment by orafaaraujo** [comment]
Fala @jeffersontpadua 
O seu post está bem legal. Como disse anteriormente, já temos outro post falando sobre Room mas ele não vai tão afundo nas camadas como você está fazendo. Você se importaria em relacionar este no seu post e o seu servir como um aprofundamente no assunto? Pelo que li, ele entraria na parte de "Configuração básica" do seu post.

Obrigado!

**Comment by jeffersontpadua** [comment]
Sem problemas. Poderia fazer isso sim. Quem é o autor do outro post?

**Comment by jeffersontpadua** [comment]
Posso linkar a postagem sim! Aí como fica? O meu seria linkado nesse artigo para um aprofundamento?

**Comment by orafaaraujo** [comment]
Oi, @jeffersontpadua 
Isso mesmo.

Abraços

**Comment by orafaaraujo** [comment]
Fechando a issue.
Podemos reabri-la caso há novidades, ok?

Abraços
