### ISSUE TITLE
12/07/18 - Kotlin: Como criar vários construtores - Caio Cardozo

### ISSUE THREAD

**Issue by caiocardozo** [androiddevbr/agenda-medium#59]
* **Autor:**Caio Cardozo
* **Perfil no medium:** medium.com/@caio.cardozo
* **Data escolhida:** 12/07/18
* **Título do artigo:** Kotlin: Como criar vários construtores
* **Descrição:** Este artigo objetiva demonstrar como criar vários construtores em uma classe Kotlin.

**Artigo ja publicado, link: https://medium.com/android-caio-cardozo/kotlin-como-criar-v%C3%A1rios-construtores-e6d84759c5b3

**Comment by orafaaraujo** [comment]
E este post vou agendá-lo para o dia 20 de agosto, o que acha?

Abraços!

**Comment by caiocardozo** [comment]
Fechado garoto! Obrigado!

**Comment by caiocardozo** [comment]
Corrigido !

**Comment by caiocardozo** [comment]
como publico no medium do Android dev br agora? Obrigado

**Comment by orafaaraujo** [comment]
Oi, @caiocardozo 

Desculpa a demora.
Estava revisando os posts aqui e o seu parece estar finalizado, né?

Vou agendar a publicação.

Abraços e obrigado.

**Comment by orafaaraujo** [comment]
Oi, @caiocardozo 

Acho que você já está como writer no Medium, é só submeter a publicação que eu aprovo, ok?

Qualquer dúvida pode me procurar no Slack.
