### ISSUE TITLE
06/06/16 - Utilizando AutoValue em aplicativos Android - David Tiago Conceição

### ISSUE THREAD

**Issue by davidtcdeveloper** [androiddevbr/agenda-medium#6]
* **Autor:** David Tiago Conceição
* **Data escolhida:** 06/06/16
* **Título do artigo:** Utilizando AutoValue em aplicativos Android
* **Descrição:** Motivação para uso de classes com AutoValue em aplicativos Android. Configuração básica de projeto para utilização da geração automática de classes. Exemplos de uso e resultados da geração automática.

**Comment by walmyrcarvalho** [comment]
@davidtcdeveloper Você acha que o tema é p/ iniciantes, intermediário ou avançado? Estou colocando umas labels pra identificar. :)

**Comment by davidtcdeveloper** [comment]
Rascunho do post: https://medium.com/@davidtiagocon/8f37f0005899
Falta introdução, uma imagem de abertura e alguns links :)

**Comment by walmyrcarvalho** [comment]
Boa @davidtcdeveloper, vou ler com calma mais tarde!

**Comment by davidtcdeveloper** [comment]
Publicado: https://medium.com/android-dev-br/autovalue-em-aplicativos-android-8f37f0005899#.5vk91r7mi
