### ISSUE TITLE
12/07/18 - Criando o primeiro APP Android Kotlin - Caio Cardozo

### ISSUE THREAD

**Issue by caiocardozo** [androiddevbr/agenda-medium#60]
* **Autor:** Caio Cardozo
* **Perfil no medium:** medium.com/@caio.cardozo
* **Data escolhida:** 12/07/2018
* **Título do artigo:** Criando o primeiro APP Android Kotlin
* **Descrição:** Este artigo demonstra como criar seu primeiro app Android utilizando a linguagem kotlin. Para isto foi utilizado um exemplo prático de um placar de jogo de basquete.

**Artigo ja publicado, link: https://medium.com/android-caio-cardozo/recentemente-o-google-adicionou-o-kotlin-em-sua-lista-de-linguagens-de-programa%C3%A7%C3%A3o-suportadas-para-76cc3a60998c

**Comment by caiocardozo** [comment]
Ola @orafaaraujo combinado! Agradeço!

**Comment by orafaaraujo** [comment]
Oi, @caiocardozo 

Deixei alguns comentários lá no post, poderia dar uma olhada antes de publicarmos?

Acabei não revisando todo o post ainda pois notei que os comentários estavam se repetindo... então, por favor, siga aquelas dicas até o fim e me avise, assim o reviso todo e já podemos publicar.

Passei o olho no seu outro post que você submeteu e deixairia os mesmo comentários... então se quiser corrigir nele também seria ótimo.

Qualquer dúvida me avise ou pode me pingar no slack.

Obrigado e abraços!

**Comment by orafaaraujo** [comment]
@caiocardozo 

Deixei alguns comentários e muito deles são os mesmo do outro review.
Vou deixar o prazo de uma semana para alinhar o post, caso contrário vamos fechar o issue, okay?

Vamos focar neste post, depois vamos para o próximo, o de construtores.

Abraços

**Comment by caiocardozo** [comment]
@orafaaraujo pronto! está corrigido. 

Muitos são os mesmos porque eu ja havia corrigido mas não havia publicado novamente, assim não aparecia corrigido para você.(eu não sabia que tinha que publicar as alterações, descobri isso agora).

Aceitas as suas sugestões ja atualizei o rascunho e está pronto para publicação.

Obrigado!

Abraços

**Comment by orafaaraujo** [comment]
Oi @caiocardozo 
Deixei alguns poucos comentários, estamos quase lá.

Abraços

**Comment by caiocardozo** [comment]
JA MATEI ELES!

Vamos conseguir Brow! meu primeiro artigo, nunca fiz isso entao nao tenho muita pratica. ObrigadO!

**Comment by caiocardozo** [comment]
Rafael?

**Comment by orafaaraujo** [comment]
Oi, Caio

Retomei as revisões.
Deixei alguns poucos comentários e já já podemos publicar.

Abraços

**Comment by caiocardozo** [comment]
Corrigido

**Comment by caiocardozo** [comment]
@orafaaraujo ja foi corrigido com as suas sugestões
