### ISSUE TITLE
15/08/2018 - Quando utilizar inicialização lazy do Kotlin - Alex Felipe

### ISSUE THREAD

**Issue by alexfelipe** [androiddevbr/agenda-medium#62]
* **Autor:** Alex Felipe
* **Perfil no medium:** medium.com/@alex.felipe
* **Data escolhida:** 15/08/2018
* **Título do artigo:** Quando utilizar inicialização lazy do Kotlin
* **Descrição:** O artigo vai apresentar as possibilidades comuns de inicialização de properties em entidades do Android (Activities, Fragment...) e vai mostrar os detalhes de tipos nullables e mutáveis, então, vai apresentar a lazy initialization para manter a ideia de property imutável mesmo tendo a peculiaridade do ciclo de vida, entre outros benefícios.

**Comment by orafaaraujo** [comment]
Ola, @alexfelipe 
Você pode deixar um rascunho aqui quando quiser, ok?

Também gostaria de te pedir para alterar o título do Issue para o nosso padrão
Exemplo: `02/05/16 - Criando aplicativos para Android - Maria da Silva`

Obrigado

**Comment by alexfelipe** [comment]
Acabei de alterar o título da issue e segue o link do rascunho https://medium.com/@alex.felipe/quando-utilizar-inicializa%C3%A7%C3%A3o-lazy-do-kotlin-45377c8b68ad

**Comment by orafaaraujo** [comment]
Oi, @alexfelipe 
Estou colocando seu post para o dia 27 de agosto, ok?

Abraços

**Comment by alexfelipe** [comment]
Opa Rafa, blz? A revisão ainda está em procedimento, né?

**Comment by orafaaraujo** [comment]
Oi @alexfelipe 
Acabei de ler sua publicação e está bem legal!
Deixei alguns comentários para você corrigir antes de publicarmos, ok?

Outros pontos que você poderia destacar são os pontos de atenção do _Detekt_ ao _lateinit_.
Segue alguns links para te auxiliar:
https://arturbosch.github.io/detekt/style.html#modifierorder
https://arturbosch.github.io/detekt/potential-bugs.html#lateinitusage

Acho que isso deixaria o post ainda mais rico em conteúdo.

Abraços

**Comment by alexfelipe** [comment]
Oi Rafa, fiz todos os ajustes. 

Como haváimos conversado via Slack, adicione o tópico "Para saber mais" e coloquei um pouco sobre o Detekt. 

Se estiver tudo certo, me fala como posso deixar certinho para ser publicado :)

[]s
