### ISSUE TITLE
Sugestão de Artigo

### ISSUE THREAD

**Issue by paulocns** [androiddevbr/agenda-medium#63]
* **Autor:** Paulo Vitor Sato
* **Perfil no medium:** https://medium.com/@paulocns/https-medium-com-paulocns-android-databind-plus-architecture-components-2c26bc8163ba
* **Data escolhida:** 10/08/2018
* **Título do artigo:** Android DataBind plus Architecture Components: the good, the bad and the ugly
* **Descrição:** O que você precisa saber sobre integrar Architecture Component a um projeto com MVVM existente que utilize DataBind e Dagger, implementado em Java

**Comment by orafaaraujo** [comment]
Olá, Paulo

Obrigado pela submissão.
Nossa comunidade é focada em artigos em português, portanto não seria interessante publicarmos o artigo em inglês.
Você pode encontrar mais informações das nossas [motivações aqui](https://github.com/androiddevbr/agenda-medium/blob/master/_info/motivacao.md).

Se desejar, faça uma versão em português e reabra essa issue. 

Outro ponto a destacar é que recentemente publicamos um post sobre [DataBinding](https://medium.com/android-dev-br/começando-com-android-data-binding-d7719333eecc). Sei que o seu post aborda mais os componentes do JetPack e o uso dele no MVVM, mas seria legal dar mais destaque ao ganho deles do que o uso de DataBinding em si, só para não publicarmos conteúdos com o mesmo tema em um curto espaço de tempo.

Qualquer coisa estamos à disposição.
