### ISSUE TITLE
25/08/18 - Android Jetpack :  Navegação - Levi Moreira

### ISSUE THREAD

**Issue by Levi-Moreira** [androiddevbr/agenda-medium#64]
* **Autor:** Levi Moreira
* **Perfil no medium:** medium.com/@levi.m.albuquerque
* **Data escolhida:** 25/08/18
* **Título do artigo:**  Android Jetpack — Navegação
* **Descrição:** Neste artigo descrevo como dar os primeiros passos na utilização da biblioteca de navegação, um dos mais novos componentes do recém lançado Jetpack. Utilizo um app simples de exemplo para demonstrar a integração da lib com componentes já existentes no Framework (como BottomNavigationViews e FABs).
* **Link:** https://medium.com/@levi.m.albuquerque/android-jetpack-navega%C3%A7%C3%A3o-a65d4d341231

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 
Me desculpe a demora.

Estava relendo o seu post e gostaria de te pedir, por gentileza, reescrever os trechos que estão escritos no pessoal, do tipo "eu fiz", "eu coloquei" e etc.
O conteúdo está legal, só precisamos deixá-lo mais com cara de atigo.

Qualquer dúvida pode me procurar por aqui ou pelo Slack.

Abraços.

**Comment by Levi-Moreira** [comment]
Oi, @orafaaraujo 
Sem problemas :)

Então, revisei o post de acordo com as suas guidelines, espero que esteja tudo certo.

Abraços.

**Comment by orafaaraujo** [comment]
Fala @Levi-Moreira 

Deixei 2 ou 3 pequenos comentários lá mas do resto está legal!
Acho que já podemos publicar na segunda-feira. 

Obrigado e abraços!

**Comment by Levi-Moreira** [comment]
Opa @orafaaraujo 

Obrigado pelo empenho na revisão do artigo, fiz as alterações que vc pediu.

Abraços.

**Comment by orafaaraujo** [comment]
Show!

Vamos publicar na segunda-feira!
Já te coloquei como writer, depois você submete no nosso medium.

Abraços!

**Comment by Levi-Moreira** [comment]
Submetido @orafaaraujo 

Abraços.
