### ISSUE TITLE
Manipulando Eventos entre Activities e Fragments Utilizando RxJava

### ISSUE THREAD

**Issue by WellingtonCosta** [androiddevbr/agenda-medium#68]
* **Autor:** Wellington Costa Pereira
* **Perfil no medium:** https://medium.com/@wellingtoncosta128
* **Data escolhida:** 01/10/18
* **Título do artigo:** Manipulando Eventos entre Activities e Fragments Utilizando RxJava
* **Descrição:** Neste artigo pretendo falar sobre a criação de event bus utilizando RxJava, tornando manipulação de eventos e a troca de dados entre Activities e Fragments de forma mais reativa e sem a verbosidade dos famosos Event Listeners.

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Poderia nos contar mais detalhes sobre este post? Qual é o problema que o post pretende solucinar? Há outras alternativas?

Abraços

**Comment by WellingtonCosta** [comment]
A ideia é falar um pouco sobre Event Bus no Android, aplicando o RxJava como uma forma de implementar um Event Bus (ou RxBus como chamamos), mostrando alguns casos de uso, tais como troca de mensagens entre Activity e Fragment sem a necessidade de se criar os famosos Callback Listeners, ou até mesmo ficar observando um determinado evento do app e executar alguma ação quando tal evento for concluído (como por exemplo uma sincronização de dados).

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Já discutimos algumas vezes na comunidade que "event bus" não é um conceito que é considerado uma prática muito boa... a forma como colocou é mais voltado à stream de dados usando RxJava do que event bus em si.
Também temos posts contra singletons na nossa publicação, então se for usar singleton tem que ter argumentos melhores do que o que já temos (https://medium.com/android-dev-br/guerra-contra-singletons-721ab89aa94).

Convido você à trazer a idea lá no Slack para clarear um pouco se ainda é uma boa ideia. O que acha?
Vou fechar o issue, mas podemos reabria-la depois ok?

Abraços.

**Comment by AlbertoLourenco** [comment]
E aqui tivemos uma aula de como ser boçal. 🤭

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Achamos que você está confundindo os conceitos.

Publish/Subscribe são pattern de observable, utilizada pelo RxJava no stream de dados, ou seja, servem para enviar e receber eventos. EventBus é um outro conceito que é qualquer um pode receber o evento, sem ao menos ter a necessidade de registrar seguindo estrutura obserable/observer (consumer). Isso pode deixar o código cheio de amarras e pontas perdidas.

Outra diferença é que com Event Bus você não consegue controlar threads... coisas que só RxJava você consegue fazer.
Para você ter uma noção, o Otto foi deprecated por conta destas deficiências.
https://github.com/square/otto#deprecated

Na nossa opinião, não concordamos com este tipo de abordagem. Por isso pedi para você levar o assunto para a comunidade e de lá podemos esclarecer melhor as ideias.

Pode fazer isso?

Abraços

**Comment by WellingtonCosta** [comment]
Vamos lá. Na seção Deprecated do Otto eles mencionam que é possível implementar mecanismos event-driven com RxJava / RxAndroid. Essa é a minha ideia. Implementar um "event bus" com RxJava (observe as aspas), justamente alinhando com o que você mencionou de o Event Bus de fato não haver um controle de threads e por.nao haver necessidade de fazer um subscribe para observar os eventos, coisa que é possível com RxJava.

Talvez eu deveria parar de utilizar o termo "Event Bus" para não confundir as coisas.

**Comment by orafaaraujo** [comment]
Beleza, agora sim! :smiley:

Acho legal você destacar este ponto porque EventBus é um conceito facil de se aprender e "difícil" de entender o porque ele não é tão bom assim.
Acho que o seu post pode ser para quem usa e pretende migrar pra o uso do RxJava da maneira correta.

**Comment by WellingtonCosta** [comment]
Agora sim! :D

A minha ideia é basicamente essa. Implementar a manipulação de eventos e troca de mensagens entre componentes Android com uma abordagem reativa utilizando RxJava.

**Comment by WellingtonCosta** [comment]
Bom, agora vou começar a escrever o artigo e mando o link assim que eu tiver uma versão inicial pronta. Beleza?

**Comment by orafaaraujo** [comment]
Fala, @WellingtonCosta 
Tudo bem?

Sem problemas, quando tiver pode mandar! Agora começando o ano já voltamos com todos os projetos hahaha.

Abraços

**Comment by WellingtonCosta** [comment]
Fala, @orafaaraujo! Beleza?

Acabei de concluir o artigo. Está disponível [neste link](https://medium.com/@wellingtoncosta128/manipulando-eventos-no-android-utilizando-rxjava-34b7cef9dfcd).

**Comment by WellingtonCosta** [comment]
Fala, @orafaaraujo!

Vi as suas considerações no artigo e já ajustei todas.

**Comment by orafaaraujo** [comment]
Fala, @WellingtonCosta 

Ainda não finalizei hahaha mas te aviso quando acabar, ok?

Obrigado e abraços!

**Comment by WellingtonCosta** [comment]
Beleza. hehehe

**Comment by WellingtonCosta** [comment]
Oi @orafaaraujo 

Vi lá suas notas e já corrigi. O lance dos layouts eu tava meio na dúvida se colocava no texto ou não. Como vc disse, isso não vai fazer tanta diferença para o leitor.

**Comment by marcellogalhardo** [comment]
Oi @WellingtonCosta, tudo bem?

A moderação do Android Dev BR revisou seu artigo, e acreditamos que houve algum mal entendido. O artigo que foi aprovado dizia:

> Implementar a manipulação de eventos e troca de mensagens entre componentes Android com uma **abordagem reativa** utilizando RxJava.

Porém, o artigo na verdade apresenta uma implementação de EventBus usando RxJava como uma "boa prática". EventBus tem suas aplicações, e por algum tempo foi bem visto na comunidade, mas já faz alguns anos que caiu em desuso por causa das diversas desvantagens que ele apresentou conforme seu projeto cresce: código de difícil manutenção, dificuldade em escalar sua arquitetura, problemas para testar, dificuldade na depuração eventos, e muitos outros.

O Android Dev BR, tem como objetivo propagar boas práticas de desenvolvimento e, por conta disso se reserva no direito de não relacionar seu nome a publicações que não acreditamos que siga nesta direção.

Se tiver dúvidas, fique a vontade para entrar em contato comigo ou qualquer outro moderador pelo Slack.

Atenciosamente, equipe Android Dev BR.

**Comment by WellingtonCosta** [comment]
> A moderação do Android Dev BR revisou seu artigo, e acreditamos que houve algum mal entendido. O artigo que foi aprovado dizia:
> 
> > Implementar a manipulação de eventos e troca de mensagens entre componentes Android com uma **abordagem reativa** utilizando RxJava.

E de fato não é troca de mensagens utilizando RxJava? Não estou usando [Otto ](https://github.com/square/otto)ou [EventBus ](https://github.com/greenrobot/EventBus)do Green Robot como engine, mas sim o próprio RxJava.

O que de fato foi proposto e apresentado está de acordo. É uma demonstração de como trocar mensagens dentro da sua app utilizando o PublishSubject do RxJava, que vai muito mais além do que só um Publish Subscribe da vida. 

O mais legal de tudo é que o artigo foi aceite, escrevi o artigo (mesmo com toda a demora da minha parte), e agora simplesmente reprovam o artigo e aparentemente vai ficar por isso mesmo. Mas beleza, é isso aí.
