### ISSUE TITLE
Bitrise CI - Introdução a ferramenta de Integração contínua e Entrega contínua

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#69]
* **Autor:** Gabriel Danilo do Prado
* **Perfil no medium:** https://medium.com/@sp4wna1
* **Data escolhida:** 07/10/18
* **Título do artigo:** Introdução - Bitrise CI para Android
* **Descrição:** Gostaria de falar um pouco mais sobre a ferramenta de Integração contínua e Entrega contínua para mobiles. Também pretendo criar uma série com tópicos mais avançados desse mesmo tema, desde a criação de workflows, configuração, etc.

Draft: https://medium.com/@sp4wna1/introdu%C3%A7%C3%A3o-bitrise-ci-para-android-ded947f2ee47

**Comment by sp4wna1** [comment]
@orafaaraujo Show! Irei começar a escrever e assim que tiver um rascunho... envio para vocês!

**Comment by sp4wna1** [comment]
@orafaaraujo atualizei com o link para o Draft. Estou escrevendo aos poucos e aceito qualquer tipo de sugestão.

**Comment by orafaaraujo** [comment]
Show, já deixei alguns comentários, mas nada demais... deixar as palavras em inglês em itálico e algumas sugestões. :D

**Comment by sp4wna1** [comment]
@orafaaraujo Acredito que seja o suficiente para dar inicio a utilização do Bitrise. Pretendo avançar com esse tema, explicando como criar as builds customizadas (workflows,steps,triggers).
Você poderia dar uma analisada? Não sei o que mais poderia acrescentar...

Obrigado pela ajuda.

**Comment by orafaaraujo** [comment]
Oi, @sp4wna1 

O que acha de colocar imagens ou prints? Principalmente na parte de "Configurando o projeto".
Seria possível subir um projeto configurado no GitHub como exemplo?
O post está muito curto... se quiser continuar o que continuaria na próxima história eu acho que seria válido também.

Abraços

**Comment by sp4wna1** [comment]
@orafaaraujo Feito. O que achou?

**Comment by orafaaraujo** [comment]
Vou dar uma olhada, @sp4wna1 

Obrigado :)
