### ISSUE TITLE
13/06/16 - MVA - Quando menos é mais - Rafael Toledo

### ISSUE THREAD

**Issue by rafaeltoledo** [androiddevbr/agenda-medium#7]
* **Autor:** Rafael Toledo
* **Data escolhida:** 13/06/16
* **Título do artigo:** MVA - Quando menos é mais
* **Descrição:** Numa época de MVP, MVVM e muitos outros MVs, vamos discutir sobre a MVA - Minimum Viable Architecture. O que é, por que usar/não usar, o princípio de pensar no momento, mas sem descuidar do futuro e sem burocratizar tudo, enfim, discutir sobre sua aplicação. A ideia é ir na contra-mão de muito do que tem sido falado nos últimos tempos :)

**Comment by walmyrcarvalho** [comment]
Bacana @rafaeltoledo, gostei do tema! :) 

Editei o título pra ficar no formato dos outros. o/

**Comment by walmyrcarvalho** [comment]
@rafaeltoledo Você acha que o tema é p/ iniciantes, intermediário ou avançado? Estou colocando umas labels pra identificar. :)

**Comment by rafaeltoledo** [comment]
Acredito que seja intermediário :)

**Comment by davidtcdeveloper** [comment]
Post publicado! Faltou atualizar aqui :)

https://medium.com/android-dev-br/mva-quando-menos-%C3%A9-mais-363f1303bb36#.9nd37ui1v
