### ISSUE TITLE
16/02/19 - Android Jetpack :  Paginação - Levi Moreira

### ISSUE THREAD

**Issue by Levi-Moreira** [androiddevbr/agenda-medium#70]
* **Autor:** Levi Moreira
* **Perfil no medium:** medium.com/@levi.m.albuquerque
* **Data escolhida:** 11/10/18
* **Título do artigo:** Android Jetpack :  Paginação 
* **Descrição:** Nesse artigo irei discutir um dos residentes mais antigos do Jetpack, a biblioteca de paginação, mostrando como utilizá-la para consultar a API do Stackoveflow usando Retrofit2.
* **Link:** https://medium.com/@levi.m.albuquerque/android-jetpack-usando-a-biblioteca-de-pagina%C3%A7%C3%A3o-e29e570db1b5

**Comment by orafaaraujo** [comment]
Fala, @Levi-Moreira 
Show de bola!
Vou tirar um tempo para revisar ainda, e assim que tiver um status te aviso, okay?

Abraços

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 

Dei uma lida no seu post e vou colocar as sugestões aqui:
- Deixe em itálico todo texto que não seja em português e/ou seja próprio (RxJava, ViewModel, MVVM)...
- Tente deixar o texto o mais impessoal possível. É ok citar suas motivações, seus experimentos e suas ideias sobre o que está apresentando. Mas evite "vou explicar/usar", coloque "será explicado/usado" e etc. O post será publicado no medium da comunidade, portanto quanto mais impessoal melhor.
- Coloque também referências ao AndroidX, seria legal pelo menos colocar a dependencia dele caso alguém já esteja usando.

Por favor, sinta-se a vontade para nós procurar para qualquer ajuda. O assunto é bem interessante.

Abraços

**Comment by Levi-Moreira** [comment]
Oi @orafaaraujo , desculpa pela grande demora, vou revisar imediatemente

**Comment by Levi-Moreira** [comment]
@orafaaraujo eu fiz as correções que vc pediu, obrigado pela paciência :)
Abraços.

**Comment by Levi-Moreira** [comment]
@orafaaraujo fiz as últimas correções que vc solicitou, obrigado pelo feedback :)

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 
Deixei alguns comentários e vou deixar outros aqui.

- Deixe todos os códigos em Gists, assim deixamos um padrão no post. Creio que aquele highlight só fica legal se o código for muito pequeno. Ou se for tudo em highlight.
- Deixei os Gists de maneira que o leitor não precise usar o scroll horizontal.
- Deixe todos os nomes em inglês (de libraries, apis etc) em itálico.
- Deixe links de referência nos nomes das bibliotecas ou nas api (nas que achar interessante caso o leitor queira mais detalhes sobre)


Qualquer coisa pode me chamar no Slack.
Abraços

**Comment by Levi-Moreira** [comment]
Oi @orafaaraujo, novamente agradeço pelo feedback e pela paciência. Fiz as correções que você solicitou.

Obrigado.

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 

Agora ficou legal! :)

Passei também para outros moderadores darem uma olhada. Se não houver comentários pode submeter que segunda-feira publicamos, ok?

Abraços

**Comment by Levi-Moreira** [comment]
Sounds great @orafaaraujo , muito obrigado :)

Abraços

**Comment by Levi-Moreira** [comment]
Oi @orafaaraujo submeti o artigo alguns dias atrás, vc tem alguma novidade sobre a publicação?

Obrigado

**Comment by orafaaraujo** [comment]
Oi, @Levi-Moreira 

Me desculpe, perdi o timming... vou publicar na segunda-feira, tudo bem?
Abraços

**Comment by Levi-Moreira** [comment]
Tudo bem sim @orafaaraujo :)
Thanks :)
