### ISSUE TITLE
Explorando a pirâmide de testes no Android — parte 1

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#72]
* **Autor:** Phellipe Silva
* **Perfil no medium:** medium.com/@phellipealexandre
* **Data escolhida:** 28/10/2018
* **Título do artigo:** Explorando a pirâmide de testes no Android — parte 1
* **Descrição:** Essa é a primeira parte de uma série de quatro artigos falando sobre pirâmide de testes no Android. Nesse artigo dou uma introdução ao conceito de pirâmide de testes demonstrando as características de cada camada e também mostrando as ferramentas disponíveis para testar no universo Android.
* **Link:** https://medium.com/@phellipealexandre/explorando-a-pir%C3%A2mide-de-testes-no-android-parte-1-18ea135808df

**Comment by phellipealexandre** [comment]
Todos os artigos da série já estão no Medium, então a data escolhida para publicação é irrelevante para mim, coloquei 28/10/2018 apenas como sugestão. Agradeço por terem criado a página como forma de disseminação do conhecimento e fico feliz por ter a oportunidade de receber uma revisão de vocês. Valeu!

**Comment by orafaaraujo** [comment]
Olá, @phellipealexandre 
Acabei de ler o seu post, está bem legal, parabéns!

Te coloquei como writer no medium. Assim que der, pode submeter?

Assim que for lendo os demais eu vou publicando, ok?
Depois faço apenas um anuncio.

Abraços
