### ISSUE TITLE
Explorando a pirâmide de testes no Android — A base da pirâmide — parte 2

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#73]
* **Autor:** Phellipe Silva
* **Perfil no medium:** medium.com/@phellipealexandre
* **Data escolhida:** 28/10/2018
* **Título do artigo:** Explorando a pirâmide de testes no Android — A base da pirâmide — parte 2
* **Descrição:** Essa é a segunda parte de uma série de quatro artigos falando sobre pirâmide de testes no Android. Nesse artigo falo com mais profundidade sobre a camada não instrumentada da pirâmide. Nesse post demonstro exemplos de como construir testes unitários puros e com Robolectric, explicitando as vantagens e desvantagens de cada abordagem.
* **Link:** https://medium.com/@phellipealexandre/explorando-a-pir%C3%A2mide-de-testes-no-android-a-base-da-pir%C3%A2mide-parte-2-7ba5f43159f2

**Comment by phellipealexandre** [comment]
Todos os artigos da série já estão no Medium, então a data escolhida para publicação é irrelevante para mim, coloquei 28/10/2018 apenas como sugestão. Agradeço por terem criado a página como forma de disseminação do conhecimento e fico feliz por ter a oportunidade de receber uma revisão de vocês. Valeu!

**Comment by orafaaraujo** [comment]
Fala, @phellipealexandre 
Pode submeter este também

Abraços

**Comment by phellipealexandre** [comment]
Submetido!
