### ISSUE TITLE
Explorando a pirâmide de testes no Android — Testes instrumentados — parte 3

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#74]
* **Autor:** Phellipe Silva
* **Perfil no medium:** medium.com/@phellipealexandre
* **Data escolhida:** 28/10/2018
* **Título do artigo:** Explorando a pirâmide de testes no Android — Testes instrumentados — parte 3
* **Descrição:** Essa é a terceira parte de uma série de quatro artigos falando sobre pirâmide de testes no Android. Nesse artigo falo com mais profundidade sobre a camada instrumentada da pirâmide. Nesse post abordamos a construção de testes com Robolectric 4.0, AndroidJUnitRunner, Espresso e UIAutomator.
* **Link:** https://medium.com/@phellipealexandre/explorando-a-pir%C3%A2mide-de-testes-no-android-testes-instrumentados-parte-3-eddf8ab2e224

**Comment by phellipealexandre** [comment]
Todos os artigos da série já estão no Medium, então a data escolhida para publicação é irrelevante para mim, coloquei 28/10/2018 apenas como sugestão. Agradeço por terem criado a página como forma de disseminação do conhecimento e fico feliz por ter a oportunidade de receber uma revisão de vocês. Valeu!

**Comment by orafaaraujo** [comment]
Oi, @phellipealexandre 

Neste post deixei alguns poucos comentários. Arrumando já pode publicar também :tada: 

Abraços

**Comment by phellipealexandre** [comment]
Legal, vi os comentários e todos fazem sentido. Assim que corrigir irei submeter para revisão. Valeu!

**Comment by phellipealexandre** [comment]
Feito
