### ISSUE TITLE
Explorando a pirâmide de testes no Android — Testes end-to-end e manuais — parte 4

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#75]
* **Autor:** Phellipe Silva
* **Perfil no medium:** medium.com/@phellipealexandre
* **Data escolhida:** 28/10/2018
* **Título do artigo:** Explorando a pirâmide de testes no Android — Testes end-to-end e manuais — parte 4
* **Descrição:** Essa é a quarta parte de uma série de quatro artigos falando sobre pirâmide de testes no Android. Nesse artigo falo com mais profundidade sobre a última e mais alta camada da pirâmide. Nesse post abordamos vários tipos de testes end-to-end que podem ser feitos no Android e explicamos um pouco mais sobre a importância de testes manuais. 
* **Link:** https://medium.com/@phellipealexandre/explorando-a-pir%C3%A2mide-de-testes-no-android-testes-end-to-end-parte-4-e94b5c6ac968

**Comment by phellipealexandre** [comment]
Todos os artigos da série já estão no Medium, então a data escolhida para publicação é irrelevante para mim, coloquei 28/10/2018 apenas como sugestão. Agradeço por terem criado a página como forma de disseminação do conhecimento e fico feliz por ter a oportunidade de receber uma revisão de vocês. Valeu!

**Comment by orafaaraujo** [comment]
Este tá show, é só publicar :tada: 

Abraços

**Comment by phellipealexandre** [comment]
Feito
