### ISSUE TITLE
10/12/18 - Adapter com Radio Button? O Jetpack pode te ajudar! - Guilherme Pereira

### ISSUE THREAD

**Issue by guuilp** [androiddevbr/agenda-medium#76]
* **Autor:** Guilherme Lima Pereira
* **Perfil no medium:** https://medium.com/@guuilp
* **Data escolhida:** Em aberto
* **Título do artigo:** Adapter com Radio Button? O Jetpack pode te ajudar!
* **Descrição:** A minha ideia é mostrar um jeito mais moderno de controlar Radio Button em listas no Android, utilizando ViewModel e LiveData. Já escrevi uma versão inicial do artigo: https://medium.com/@guuilp/adapter-com-radio-button-o-jetpack-pode-te-ajudar-9793a434bfeb

**Comment by orafaaraujo** [comment]
Oi, @guuilp 

Deixei alguns comentários.
Assim que mudá-los a gente já publica.

Abraços

**Comment by guuilp** [comment]
Respondi alguns comentários e realizei a mudança solicitada em outros. Revise novamente, por favor.

**Comment by orafaaraujo** [comment]
Deixei mais alguns.

Obrigado.

**Comment by orafaaraujo** [comment]
Olá, @guuilp 

Te coloquei como writer em nosso medium. Agora você já pode submeter pra publicação.

Tem apenas 3 comentários que você pode matar fácilmente.
Assim que finalizar já pode publicar.

Abraços
