### ISSUE TITLE
01/01/2019 - Utilizando Kotlin Coroutines no Android

### ISSUE THREAD

**Issue by WellingtonCosta** [androiddevbr/agenda-medium#77]
* **Autor:** Wellington Costa
* **Perfil no medium:** medium.com/@wellingtoncosta128
* **Data escolhida:** 01/01/2019
* **Título do artigo:** Utilizando Kotlin Coroutines no Android
* **Descrição:** Neste artigo pretendo explicar o que é o Kotlin Coroutines, seus principais conceitos e como aplicá-los dentro do ecossistema do Android, permitindo trabalhar com operações assíncronas.

**Comment by orafaaraujo** [comment]
Fala, @WellingtonCosta 
Tudo bem?

como anda o post? Precisa de alguma ajuda?

Abraços

**Comment by WellingtonCosta** [comment]
E aí, @orafaaraujo! Beleza?

Cara, já tenho material desse artigo praticamente pronto, pois palestrei sobre isso no TDC POA 2018. Só preciso compilar tudo para transformar em artigo. Irei fazer isso assim que terminar o outro artigo sobre RxJava. Acredito que até o final de semana devo ter uma versão para revisão.

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 
Sem pressa!

Só não deixe fugir do radar :)

Abraços

**Comment by WellingtonCosta** [comment]
Tranquilo, @orafaaraujo.

Vou começar a escrever hoje. Inclusive o outro artigo sobre RxJava #68 já finalizei. Dá uma olhada lá. :)

**Comment by WellingtonCosta** [comment]
Oi, @orafaaraujo 

Acabei de finalizar o artigo. Segue o link: https://medium.com/@wellingtoncosta128/utilizando-kotlin-coroutines-no-android-c73fcda71e27

**Comment by orafaaraujo** [comment]
Oi, @WellingtonCosta 

Está excelente o artigo.
Deixei apenas pequenos comentários que julgo que melhoraria a legibilidade do texto.

É arrumar isso e publicamos.

Abraços

**Comment by WellingtonCosta** [comment]
Oi, @orafaaraujo 

Já arrumei todos. hehehe
