### ISSUE TITLE
Bitrise CI/CD - Criando workflow de testes unitários e cobertura de código

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#78]
* **Autor:** Gabriel Danilo do Prado
* **Perfil no medium:** https://medium.com/@sp4wna1
* **Data escolhida:** A definir
* **Título do artigo:** Bitrise CI/CD - Criando workflow de testes unitários
* **Descrição:** Gostaria de falar um pouco mais sobre como criar o workflow de teste unitário com cobertura de código e análise estática de código, utilizando JUnit, Jacoco e Detekt.

Draft: https://medium.com/@sp4wna1/bitrise-ci-criando-workflow-de-testes-unit%C3%A1rios-com-cobertura-de-c%C3%B3digo-1e7ed648a86b

**Comment by orafaaraujo** [comment]
Fala, @sp4wna1 

Manda bala :)

Abraços

**Comment by sp4wna1** [comment]
Show @orafaaraujo,

Vou atualizar com um link para o draft. Estou evoluindo ele, qlqr sugestão é bem vinda.

Abraços

**Comment by orafaaraujo** [comment]
Oi, @sp4wna1 

Dei uma lida e está tomando forma.
Lembre-se de deixar as palavras em ingles em itálico e sempre que haver um link da documentação referência-lo com hyperlinks.
Tome cuidado com o uso de muitas virtulas para o texto não ficar intervalado.
E deixe prints, gists, gráficos, imagens etc para enriquecer o post e deixar mais compreesivel para os leitores.

Abraços

**Comment by sp4wna1** [comment]
Oi, @orafaaraujo.

Estou tentando deixar ele o mais simples e direto possível... adicionei print e gist.
Acabei de fazer os ajustes, você pode revisar novamente?


Obrigado por ajudar, abraços!

**Comment by orafaaraujo** [comment]
Oi, @sp4wna1 

O post está completo e explicativo. Só deixei 2 comentários que acho que deixaria o post mais rico e mais compreensivel. Veja lá e qualquer coisa pode me chamar no Slack.

Abraços

**Comment by orafaaraujo** [comment]
Oi, @sp4wna1 

Só alterei onde está o arquivo e publiquei.

Muito obrigado novamente! 
Eu, os moderadores e a comunidade agradece :)
