### ISSUE TITLE
22/01/2019 - Android UI: Bottom Sheet

### ISSUE THREAD

**Issue by itscorey** [androiddevbr/agenda-medium#79]
* **Autor:** Lucas Cavalcante
* **Perfil no medium:** https://medium.com/@luke8.co
* **Data escolhida:** 22/01/2019
* **Título do artigo:** Android UI: Bottom Sheet
* **Descrição:** É um artigo para iniciantes sobre componentes de UI no Android, este, espeficamente, trata-se do Bottom Sheet.

**Comment by itscorey** [comment]
Já existe uma versão do artigo publicada e ela pode ser lida [aqui](https://medium.com/@luke8.co/android-ui-bottom-sheet-4709cad826d2).

**Comment by orafaaraujo** [comment]
Fala, @itscorey 
Só tenho duas sugestões:

- Uma imagem de header, que dá um destaque legal na publicação.
- Diminuir os vídeos das telas, para ver sem precisar scrollar ou ocupar a tela inteira. Se precisar de ajuda me chama no Slack.

Do mais está ótimo, é dar um tapa nisso e publicar.

Abraços

**Comment by itscorey** [comment]
@orafaaraujo atualizarei logo mais e volto aqui.

Obrigado.

**Comment by itscorey** [comment]
Feito @orafaaraujo

**Comment by orafaaraujo** [comment]
Obrigado, @itscorey 

Publicamos na segunda-feira, ok?
Já te coloquei como _writer_ no nosso Medium, então você já pode submeter que eu publico na segunda-feira.

Abraços e obrigado!
