### ISSUE TITLE
27/06/16 - Fresco, sim! - Rodrigo Sicarelli

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/agenda-medium#8]
* **Autor:** Rodrigo Sicarelli
* **Data escolhida:** 20/06/16
* **Título do artigo:** Fresco, sim!
* **Descrição:** Irei apresentar a incrível lib de carregar imagem do Facebook, o Fresco, e mostrar o por que utiliza-la e também o por que você deve substitui-la pelas suas libs de carregamento de imagem atuais.

**Comment by walmyrcarvalho** [comment]
Boa! <3

**Comment by davidtcdeveloper** [comment]
Publicação postergada para a próxima semana :)

**Comment by walmyrcarvalho** [comment]
Publicado! https://medium.com/android-dev-br/fresco-sim-cda40fabae82#.hiorxlphj
