### ISSUE TITLE
23/01/2019 - Arquiteturas em Android : MVVM + Kotlin + Android Architecture Components (Databinding, Lifecycle, LiveData, Room)

### ISSUE THREAD

**Issue by soutoss** [androiddevbr/agenda-medium#80]
* **Autor:** Thiago Souto
* **Perfil no medium:** medium.com/@soutoss
* **Data escolhida:** 23/01/19
* **Título do artigo:** Arquiteturas em Android : MVVM + Kotlin + Android Architecture Components (Databinding, Lifecycle, LiveData, Room)
* **Descrição**: A ideia deste artigo é refatorar um aplicativo desenvolvido em kotlin utilizando MVVM e alguns elementos do architecture components.

Já existe uma versão do post publicada [aqui](https://medium.com/@soutoss/arquiteturas-em-android-mvvm-kotlin-android-architecture-components-databinding-lifecycle-d5e7a9023cf3)

**Comment by orafaaraujo** [comment]
Oi, @soutoss 

Revisei o post e deixei alguns comentários. Basicamente são:

- algumas correções de nomes (ex databinding para Data Binding)
- deixar os nomes próprios em itálicos
- colocar link nas descrições dos tópicos
- retirar "gist com" dos gists
- remover packages e importes irrelevantes para o código apresentado
- quebrar o código do gist para evitar scroll horizontal.

Outra coisa que me chamou a atenção foi a introdução ao Room no final do artigo. Você comentou que irá falar mais sobre ele no próximo post e não vi muita ligação com o que foi apresentado até agora. Minha sugestão seria retirar esta parte e abrir o próximo artigo nela, e aí já fala de main thread and como associar ao LiveData, ViewModel... o que acha? Acha que faz sentido?

Obrigado!
