### ISSUE TITLE
Injetando Dependências No Android Com Koin

### ISSUE THREAD

**Issue by wellingtoncosta** [androiddevbr/agenda-medium#81]
* **Autor:** Wellington Costa Pereira
* **Perfil no medium:** medium.com/@wellingtoncosta128
* **Data escolhida:** 11/02/19
* **Título do artigo:** Injetando Dependências No Android Com Koin
* **Descrição:** Neste artigo será abordado o projeto Koin para trabalhar com injeção de dependências. No artigo será detalhado os componentes do Koin, sua DSL, como criar os módulos de dependências e como injetá-las dentro dos componentes.

**Comment by orafaaraujo** [comment]
Olá, @wellingtoncosta 

Alguma novidade sobre este post?

Abraços

**Comment by orafaaraujo** [comment]
Fala @wellingtoncosta 

Tranquilo, leve o seu tempo.
E sim, trazer coisas do Koin 2.0 já seria mega interessante!

Abraços
