### ISSUE TITLE
27/01/19 - Ciclo de vida no Android — Um estudo de caso - Phellipe Silva

### ISSUE THREAD

**Issue by phellipealexandre** [androiddevbr/agenda-medium#83]
* **Autor:** Phellipe Silva
* **Perfil no medium:** https://medium.com/@phellipealexandre
* **Data escolhida:** 27/01/19 (pode ser qualquer data daqui para frente)
* **Título do artigo:** Ciclo de vida no Android — Um estudo de caso
* **Descrição:** Gostaria de mostrar um exemplo um pouco mais complexo de ciclos de vida no Android baseado em uma situação real. Através desse post tento mostrar o que acontece com cada componente durante a navegação do usuário e no final mostro algumas conclusões obtidas com o fluxo.

Link para o post [aqui](https://medium.com/@phellipealexandre/ciclo-de-vida-no-android-um-estudo-de-caso-65d59398ab6f)

**Comment by orafaaraujo** [comment]
Oi, @phellipealexandre 

Li o post e está bem interessante!

Tenho alguns pontos para te pedir.
- Deixar todas as palavras em inglês em itálico (menos aquela lista de eventos, ali é OK)
- Deixe Fragment ao invés de Fragmento. Acho que não é muito comum traduzir Fragment na comunidade brasileiro.

Geralmente peço para os colaborares escreverem os posts no impessoal, evitando "eu fiz", "eu coloquei", "eu criei" e usando mais "foi feito", "foi colocado", "foi criado" etc. 
Mas como o objetivo do seu post não é um "tutorial" e sim compartilhar um estudo que você fez acho que esta regra não cabe aqui. 
(Só comentando para deixar registrado o porque não deste pedido para você).

Obrigado!

**Comment by phellipealexandre** [comment]
Fala @orafaaraujo,

Coloquei todas as palavras do inglês em itálico. Inclusive _stack, back, landscape_ e _callback_ (que utilizei no texto). Também troquei todos os fragmentos por _fragments_ Valeu pelo toque!

Eu tentei deixar o texto impessoal também, mas tive dificuldade de escrever já que se trata de um estudo de caso. Vou levar o feedback para os próximos posts.

**Comment by phellipealexandre** [comment]
Olá @orafaaraujo, algum update sobre a publicação desse post? 😄

**Comment by orafaaraujo** [comment]
Olá, @phellipealexandre 

Vamos publicar essa semana, tudo bem?
Abraços!
