### ISSUE TITLE
18/02/19 - OTP de forma segura com a SMS Retriever API  - Wilder Pereira

### ISSUE THREAD

**Issue by wilder** [androiddevbr/agenda-medium#84]
* **Autor:** Wilder Pereira
* **Perfil no medium:** [medium.com/@wilderpereira](https://medium.com/@wilderpereira)
* **Data escolhida:** 07/02/19
* **Título do artigo:** One Time Password de forma segura com a SMS Retriever API
* **Descrição:** Nesse artigo pretendo falar sobre as atualizações de segurança anunciadas pelo Google para aplicativos que utilizam permissões de Call Log e SMS e explorar um dos usos mais comuns da permissão de SMS, implementando o fluxo de uma verificação OTP utilizando a SMS Retriever API.

Por enquanto apenas possuo o [artigo publicado em inglês](https://medium.com/@wilderpereira/secure-android-otp-account-verification-with-the-sms-retriever-api-c395c1985fbf)

**Comment by orafaaraujo** [comment]
Olá, @wilder 

Legal o tema!
Mas para publicar em nosso Medium ele precisa ser em português. Você pode fazer a tradução?

Abraços

**Comment by wilder** [comment]
@orafaaraujo claro!

Assim que terminar aviso aqui.

Valeu!

**Comment by wilder** [comment]
@orafaaraujo desculpe pela demora.

Mudei a data escolhida para que possam revisar com calma.

Aqui está o link do artigo no Medium:
https://medium.com/@wilderpereira/verifica%C3%A7%C3%A3o-de-contas-por-sms-utilizando-a-sms-retriever-api-ce501d57d592

**Comment by orafaaraujo** [comment]
Está show, @wilder 

Vamos publicar na segunad-feira, dia 18/02.

Abraços
