### ISSUE TITLE
31/01/19 - Usando Navigation Component - Android Jetpack - Alifyz Pires

### ISSUE THREAD

**Issue by Alifyz** [androiddevbr/agenda-medium#85]
Autor: Alifyz Pires
Perfil no medium: https://medium.com/@alifyzfpires
Data planejada: 31/01/19
Título do artigo: Usando Navigation Component - Android Jetpack 
Descrição: Artigo com conceitos importantes sobre o novo componente de navegação do Android Jetpack, uma visão geral de sua utilização e casos de usos reais
para o novo componente.

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 

Já temos uma publicação em andamento neste tema, por isso aconselho a pensar em um outro.
Na verdade não temos problema de ter duas ou mais publicações no mesmo tema, mas o intervalo de tempo será muito curto. 

Qualquer dúvida pode me procurar no Slack.

Abraços

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 

Me desculpe, confundi Navigation com Pagination.

Segue o jogo!

**Comment by Alifyz** [comment]
Opa, segue o link: 
https://medium.com/@alifyzfpires/usando-navigation-component-android-jetpack-e1356921b31d

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 

Deixei alguns comentários no post. Em suma é:
- Deixei palavras em inglês com itálico.
- Deixei links como links em alguns termos para a documentação. Pode ajudar o leitor a pegar mais detalhes.
- Tire código desnecessário dos Gists, como imports banais, código que deixa scroll horitotal, pacotes e o que mais acha legal.
- E por ultimo, mas não menos importante, deixe o texto no impessoal. Evite "vamos", "nosso" e outras palavras. Isso deixará o texto com um tom mais profissional.

Quando acabar as alterações em avise que reviso novamente.
Qualquer dúvida, pode me chamar no Slack.

Abraços

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 

Revisei o post novamente e está ok.
Só tem alguns pontos que você comenta que irá abordar e eu não encontrei no post.
Poderia conferir? Se não estiver lá mesmo, remove aquela parte.

Abraços

**Comment by Alifyz** [comment]
Opa, vou dar uma ajustado. 
Muito obrigado.

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 
Chegou a dar uma olhada?
Abs!

**Comment by Alifyz** [comment]
Opa, esse final de semana eu consigo finalizar. 
Abs

**Comment by orafaaraujo** [comment]
Oi, @Alifyz 
Você corrigiu as anotações?
Não estou encontrando as anotações mas também não estou encontrando os pontos que pedi pra corrigir, então acho que foram corrigidos hahaha

Abraços!

**Comment by Alifyz** [comment]
Opa, eu removi as partes que eu não estava abordando. 
E exclui as anotações, da próxima vez vou deixar rsrsrs

Da uma olhada se é isso mesmo. 
Abs

**Comment by orafaaraujo** [comment]
Vou publicar hoje!

Abs

**Comment by orafaaraujo** [comment]
Alias, pode submeter em nosso Medium?

Abraços

**Comment by orafaaraujo** [comment]
@Alifyz 

Algum status?
Obrigado

**Comment by Alifyz** [comment]
Opa, acabei de mandar.
