### ISSUE TITLE
Chamadas assíncronas no Room, explorando as opções (RxJava, LiveData e Coroutines) - Levi Moreira 

### ISSUE THREAD

**Issue by Levi-Moreira** [androiddevbr/agenda-medium#86]
* **Autor:** Levi Moreira
* **Perfil no medium:** medium.com/@levi.m.albuquerque
* **Data escolhida:** 13/03/19
* **Título do artigo:** Chamadas assíncronas no Room, explorando as opções (RxJava, LiveData e Coroutines)
* **Descrição:** Este artigo irá explorar o suporte dado pelo Room para os diversos frameworks de chamadas assíncronas mais utilizadas na atualidade. Recentemente foi adicionado suporte a coroutines no Room (em alfa) e eu gostaria de fazer um comparativo entre este e as entidades suportadas anteriormente (LiveData e RxJava) mostrando como o desenvolvedor pode utilizar cada uma delas e destacando vantagens de utilizar uma ao invés de outra.

**Comment by Levi-Moreira** [comment]
@orafaaraujo Demorou, mas chegou :0 
https://medium.com/@levi.m.albuquerque/chamadas-ass%C3%ADncronas-no-room-explorando-as-op%C3%A7%C3%B5es-rx-livedata-e-coroutines-215c235b26a1

**Comment by Levi-Moreira** [comment]
@orafaaraujo @davidtcdeveloper Acho q  tinha esquecido de submeter o artigo para que vocês pudessem avaliar :/ O fiz agora, sorry pelo delay.

**Comment by davidtcdeveloper** [comment]
@Levi-Moreira Temos dois posts que estão em revisão agora, assim que estes dois forem revisados nós fazemos a revisão do seu post também ;)

**Comment by davidtcdeveloper** [comment]
@Levi-Moreira Revisei o post, tá excelente! A ideia é muito boa e os comparativos ficaram bem legais.
Adicionei algumas sugestões que acredito que ficariam interessantes. Peço que dê uma lida, veja o que faz sentido e me avise por aqui quando tiver terminado de fazer ajustes ou responder aos comentários.

**Comment by Levi-Moreira** [comment]
Oi @davidtcdeveloper muito obrigado pelo feedback e fico feliz que você gostou do artigo! Eu olhei suas sugestões e fiz as alterações necessárias. Novamente, muito obrigado pelo feedback.

**Comment by davidtcdeveloper** [comment]
Show, obrigado pela resposta. Acabei me enrolando um pouco aqui mas farei a revisão hoje ainda.

**Comment by davidtcdeveloper** [comment]
Revisei aqui, tá excelente. Provavelmente faremos a publicação hoje ainda.

**Comment by davidtcdeveloper** [comment]
@Levi-Moreira O @orafaaraujo Adicionou mais alguns comentários no post. Coisas pontuais pra subir ainda mais o nível.
Se puder dar uma olhada, agradecemos.

**Comment by Levi-Moreira** [comment]
Opa, ta okay @davidtcdeveloper vou dar uma olhada :)

**Comment by Levi-Moreira** [comment]
Prontinho @davidtcdeveloper e @orafaaraujo , novamente muito obrigado pelo feedback, you guys rock!

**Comment by davidtcdeveloper** [comment]
Show, vamos agilizar a publicação

**Comment by davidtcdeveloper** [comment]
Estamos montando a mensagem e logo vamos publicar aqui.
Um último pedido: podes citar a fonte da imagem do header?

**Comment by davidtcdeveloper** [comment]
Post publicado e anunciado!

**Comment by Levi-Moreira** [comment]
Coloquei as infos sobre a foto, obrigado pessoal :)
