### ISSUE TITLE
Por que devo testar minhas aplicações

### ISSUE THREAD

**Issue by DiegoGSantos** [androiddevbr/agenda-medium#88]
* **Autor:** Diego Gonçalves Santos
* **Perfil no medium:** medium.com/@diegogsantos
* **Data escolhida:** Assim que possível, já que já está escrito
* **Título do artigo:** Por que devo testar minhas aplicações
* **Descrição:** Nesse artigo, https://medium.com/@diegogsantos/por-que-devo-testar-minhas-aplica%C3%A7%C3%B5es-3c169716d714, eu trago argumentos para demonstrar para os devs que ainda não estão convencidos dos benefícios de uma boa suíte de testes automatizados, por que vale a pena investir tempo no desenvolvimento de testes e como eles podem podem impactar positivamente a sua rotina de trabalho.

**Comment by orafaaraujo** [comment]
Oi, @DiegoGSantos tudo bom?

Acabei de ler o seu post e ficou legal. Só gostaria de te sugerir para adicionar alguns subtitulos antes de alguns paragrafos, como "**Pontos positivos para testar**", "**TDD**" etc. A ideia aqui é quebrar um pouco o texto para não passar uma impressão de um texto muito longo e extenso, o que pode fazer o leitor achar cansativo de ler. Se quiser quebrar algumas linhas também, ajuda a melhorar a leitura.
Sobre o conteúdo está ótimo! Só um ajuste de UI/UX :joy: 

Abraços

**Comment by DiegoGSantos** [comment]
Muito bem observado @orafaaraujo, obrigado pelo feedback. Já fiz as alterações. Dá uma olhada depois se está ok e qualquer coisa me avise.

**Comment by orafaaraujo** [comment]
Oi, @DiegoGSantos 

Te coloquei como _writer_ em nosso Medium.
Agora é só submeter o post para a nossa página que eu já publico.

Abraços

**Comment by DiegoGSantos** [comment]
Valew @orafaaraujo, já submeti lá! 
Abraço!

**Comment by orafaaraujo** [comment]
Oi, @DiegoGSantos 

Vi aqui e já vou aprovar.
Mas parece que suas alterações de ontem sumira... pode confirmar para mim?

Obrigado

**Comment by DiegoGSantos** [comment]
Estranho, aqui aparece pra mim normal... Se vc abrir https://medium.com/@diegogsantos/por-que-devo-testar-minhas-aplica%C3%A7%C3%B5es-3c169716d714 aparece sem as alterações ?

**Comment by orafaaraujo** [comment]
Acho que você submeteu um outro artigo parecido, porque este está OK pra mim

Confere aí, por favor.

**Comment by DiegoGSantos** [comment]
Pode ser... Mandei de novo, vê se agora deu certo.

**Comment by orafaaraujo** [comment]
Realmente, tem duas submissões 

Este: https://medium.com/p/3c169716d714/edit
E este: https://medium.com/p/c62ddf7e909c/edit

Vamos publicar os que tem os subtopicos, certo?

**Comment by DiegoGSantos** [comment]
Certo!

**Comment by orafaaraujo** [comment]
Publicado!

Mais tarde faço o anuncio!

Muito obrigado pela publicação. Estamos abertos sempre à novos posts!
Abraços
