### ISSUE TITLE
03/03/2019 - Android ConstraintLayout explained using a complex UI - Amod Kanthe

### ISSUE THREAD

**Issue by amodkanthe** [androiddevbr/agenda-medium#89]
* **Autor:** Amod Kanthe
* **Perfil no medium:** https://medium.com/@amodpkanthe
* **Data escolhida:** 03/03/2019
* **Título do artigo:** Android ConstraintLayout explained using a complex UI
* **Descrição:** Explained creating UI using constraintlayout step by step.Explained importance of guideline and other terminology related to ConstraintsLayout

**Comment by orafaaraujo** [comment]
Hi, @amodkanthe 

Great topic! 
Just keep in mind that we are a Brazilian community and our motivation is to make great posts in Portuguese. That's why we only allow posts in Portuguese... is that an issue for you?

Thanks

**Comment by amodkanthe** [comment]
Okay can anyone convert it to Portuguese for me?

**Comment by orafaaraujo** [comment]
Hey, @amodkanthe 
You can ask for it in our community on Slack. Please, be aware to use channels like #devs-abroad, #learn or #random.

I'll close this issue. If you find someone to translate it for you, please, re-open it again.

Thanks
