### ISSUE TITLE
18/07/16 - Dagger 2, um ano depois - Rafael Toledo

### ISSUE THREAD

**Issue by rafaeltoledo** [androiddevbr/agenda-medium#9]
* **Autor:** Rafael Toledo
* **Data escolhida:** 18/07/16
* **Título do artigo:** Dagger 2, um ano depois
* **Descrição:** Após pouco mais de um ano de contato, projetos em produção e com o amadurecimento da biblioteca, correção de bugs, novas features e um novo ciclo de release, o que mudou? O que tem de novo? Como isso pode me ajudar a estruturar melhor minha aplicação e até escrever menos código?

**Comment by davidtcdeveloper** [comment]
@rafaeltoledo Obrigado pela contribuição. Apenas para confirmar, agendou para dia 18/07 e pulou algumas datas de propósito?

**Comment by rafaeltoledo** [comment]
@davidtcdeveloper Sim, pulei pra não ficar dois posts meus quase seguidos :)

**Comment by davidtcdeveloper** [comment]
@rafaeltoledo Show, já adicionei à agenda :smile:

**Comment by davidtcdeveloper** [comment]
Link da para o artigo:
https://medium.com/android-dev-br/dagger-2-um-ano-depois-dac71012b594#.u4g29vtdn
:smile:
