### ISSUE TITLE
Fusão de Manifestos: Como são aplicadas regras para gerar um único arquivo AndroidManifest.xml

### ISSUE THREAD

**Issue by haldny** [androiddevbr/agenda-medium#90]
* **Autor:** Haldny Santos
* **Perfil no medium:** https://medium.com/@haldnysantos
* **Data escolhida:** 12/03/19
* **Título do artigo:** Fusão de Manifestos: Como são aplicadas regras para gerar um único arquivo AndroidManifest.xml
* **Descrição:** Neste artigo, busquei mostrar como e quais regras são aplicadas para gerar o arquivo AndroidManifest.xml empacotado no APK.

**Comment by orafaaraujo** [comment]
Link do post: https://medium.com/@haldnysantos/fus%C3%A3o-de-manifestos-como-s%C3%A3o-aplicadas-regras-para-gerar-um-%C3%BAnico-arquivo-androidmanifest-xml-f7a9ff0fafa7

**Comment by orafaaraujo** [comment]
Está bem bacana o post, @haldny 

Deixei alguns poucos comentários... podemos publicar em breve :)

Abraços!

**Comment by haldny** [comment]
Oi @orafaaraujo,

Muito obrigado pelo feedback, fiz alguns ajustes lá no post.


Abraços!

**Comment by orafaaraujo** [comment]
Oi, @haldny 

Acabei de ler e está show!
Bora publicar? :sunglasses: 

Abraços

**Comment by haldny** [comment]
Oi, @orafaaraujo 

Vamos publicar sim!
Só não lembro como era o procedimento.

Abraços,

**Comment by orafaaraujo** [comment]
Rapaz, agora você me pegou :smiley: 

Você já tem permissões de writer em nosso Medium. 
Veja se nas opções do seu post tem como enviar para publicação pela gente.
Assim que enviar eu publico.

Abraços

**Comment by haldny** [comment]
Acabei de enviar.

Abraços,

**Comment by orafaaraujo** [comment]
Publicado!

Vou pedir para a equipe do Medium mudar pra data de hoje e mais tarde anunciamos!

Obrigado novamente!
A comunidade agradece <3
