### ISSUE TITLE
20/03/19 - Usando arquivos Kotlin para gerenciar suas dependência - Lucas Marciano

### ISSUE THREAD

**Issue by lucas-marciano** [androiddevbr/agenda-medium#91]
* **Autor:** Lucas Marciano
* **Perfil no medium:** https://medium.com/@lucas_marciano
* **Data escolhida:** 20/03/19
* **Título do artigo:** Usando arquivos Kotlin para gerenciar suas dependência
* **Descrição:** O artigo explica como realizar um gerencia das dependências do projeto usando o Kotlin para gerir diminuindo a interação com o gradle.

**Comment by lucas-marciano** [comment]
O artigo já foi publicado, segue o link : https://medium.com/@lucas_marciano/usando-arquivos-kotlin-para-gerenciar-suas-depend%C3%AAncia-b61d2480a501

**Comment by orafaaraujo** [comment]
Olá, @lucas-marciano 

Parabéns pelo post, achei bem legal!
Segue algumas sugestões:
- Deixe os termos em inglẽs em itálico, só para demostrar que é uma palavra "diferente" e tem um signifcado próprio para nós.
- Geralmente peço para todos escreverem de forma impessoal, para o post ficar mais profissional. Mas na sua dinâmica, não faz muito sentido pois tem as perguntas, sua pesquisa e experiência etc. Então só deixei no informal quando você estiver fazendo a parte de "tutorial" mesmo. Tudo bem?

Qualquer dúvida pode me chamar aqui e ou no Slack.

Abraços

**Comment by lucas-inatel** [comment]
@orafaaraujo fiz as alterações que tu solicitou

**Comment by orafaaraujo** [comment]
Obrigado, Lucas.

Vou passar revisando mais tarde.
Se estiver Ok, já publicamos.

Abraços!

**Comment by orafaaraujo** [comment]
Oi, @lucas-inatel 
Deixei alguns pequenos comentários.

Te coloquei como writer em nosso Medium. Assim que acabar as alterações vocẽ já pode submeter o post e já publicamos. :tada: 

Obrigado novamente.
Abraços

**Comment by lucas-inatel** [comment]
@orafaaraujo fiz os ajustes que tu informou, gostaria de averiguar algo mais antes de eu por no Medium da comunidade?

**Comment by orafaaraujo** [comment]
Fala, @lucas-inatel 

Nada, publicado! :tada: 

Em nome da comunidade gostaria de agradecer pelo post!
Anunciamos mais tarde.

Abraços!
