### ISSUE TITLE
05/04/19 - Modularização Android

### ISSUE THREAD

**Issue by ifucolo** [androiddevbr/agenda-medium#92]
* **Autor:** Iago Fucolo
* **Perfil no medium:** https://medium.com/@iagofucolo
* **Data escolhida:** 05/04/19
* **Título do artigo:** Modularização Android
* **Descrição:** Criei uma serie de 3 artigos, explicando como criar seu projeto modularizado com MVVM, Koin, Room, Databinding, Rx e etc.

https://medium.com/@iagofucolo/modulariza%C3%A7%C3%A3o-android-parte-1-b69b509571c9

https://medium.com/@iagofucolo/modulariza%C3%A7%C3%A3o-android-parte-2-aab52b903d90

https://medium.com/@iagofucolo/modulariza%C3%A7%C3%A3o-android-parte-3-22622ae7d162

**Comment by orafaaraujo** [comment]
Oi, @ifucolo 
Deixei alguns comentários no post 2 e 3.
Estão grandes, mas estão bem completos, parabéns!

**Comment by ifucolo** [comment]
Opa @orafaaraujo, ja arrumei os ajustes, valeu!

**Comment by orafaaraujo** [comment]
Valeu, @ifucolo 
Vamos dar mais uma olhada e se tiver tudo certo ja publicamos hoje o/

**Comment by ifucolo** [comment]
Blz, ja arrumei os ultimos comentarios tambem.

**Comment by orafaaraujo** [comment]
Show,  vamos publicar hoje 🎉

**Comment by orafaaraujo** [comment]
Alias, pode submeter em nosso Medium?

Abraços
