### ISSUE TITLE
10/04/19 Android strings.xml — Detalhes que não podemos esquecer - Victor Oliveira

### ISSUE THREAD

**Issue by victorlopesjg** [androiddevbr/agenda-medium#93]
* **Autor:** Victor Oliveira
* **Perfil no medium:** https://medium.com/@victorlopesjg
* **Data escolhida:** 10/04/19
* **Título do artigo:** Android strings.xml — Detalhes que não podemos esquecer
* **Descrição:** Gostaria de falar sobre as boas práticas que não podemos esquecer ao usar o strings.xml. 

https://medium.com/@victorlopesjg/android-string-xml-detalhes-que-n%C3%A3o-podemos-esquecer-2c4fb57f9bd

**Comment by orafaaraujo** [comment]
Oi, @victorlopesjg 

Post bem simples e direto.
Já vamos publicá-lo!

Abraços e muito obrigado!
