### ISSUE TITLE
01/05/19 - Arquitetura limpa nas apps: Utilizando VIPER no Android - Diogo Cabral

### ISSUE THREAD

**Issue by drcabral** [androiddevbr/agenda-medium#94]
* **Autor:** Diogo Cabral
* **Perfil no medium:** medium.com/@drkbral
* **Data escolhida:** 01/05/19
* **Título do artigo:** Arquitetura limpa nas apps: utilizando VIPER no Android
* **Descrição:** Quantas vezes já nos deparamos com um projeto com uma estrutura confusa, muitas vezes com classes infladas e sem responsabilidades e objetivos únicos? Isso claramente nos traz uma série de dificuldades: desde a sua manutenção até a forma como testamos o nosso código. Neste artigo será proposta uma alternativa para este problema: a utilização do VIPER, que é uma arquitetura baseada nos conceitos do Clean Architecture e que, além disso, é totalmente aplicável a um contexto de aplicação Android.

Obs: ainda estou iniciando a estruturação do texto, mas ele será baseado em uma talk que eu fiz sobre o tema e que apresentei em alguns eventos. Logo posso trazer um rascunho deles para revisão.

**Comment by drcabral** [comment]
Olá!

como prometido, segue o link da primeira versão não revisada do artigo

https://medium.com/@drkbral/f39e51b44723

demorei um pouco mais que o esperado pois tive uma viagem no mês passado (sorry por isso)

**Comment by anacoimbrag** [comment]
@drcabral ótimo post! Deixamos alguns comentários sobre alguns ajustes.. se puder dar uma olhada e nos avisar quando resolvê-los, em seguida publicaremos.

**Comment by drcabral** [comment]
Feito!

**Comment by orafaaraujo** [comment]
Oi, @drcabral 

Pode subemter a publicação ?

Obrigado

**Comment by drcabral** [comment]
O medium está com alguns problemas de carregamento e acesso de páginas, mas assim que normalizar eu vou submeter!

**Comment by drcabral** [comment]
Funcionou agora, submissão feita!
