### ISSUE TITLE
Configurando e utilizando o Charles Proxy para interceptar Requests

### ISSUE THREAD

**Issue by sp4wna1** [androiddevbr/agenda-medium#95]
* **Autor:** Gabriel Prado
* **Perfil no medium:** medium.com/@sp4wna1
* **Data escolhida:** A definir
* **Título do artigo:** Configurando e utilizando Charles Proxy para interceptar requests
* **Descrição:** Gostaria de falar um pouco mais sobre como interceptar requests e alterar seus resultados, para criar determinados estados independentes do backend.

**Comment by orafaaraujo** [comment]
Fala, @sp4wna1 
Tudo bom?

Alguma novidade sobre este post?

Abraços

**Comment by gabriel-prado-ifood** [comment]
Oi @orafaaraujo, estou bem obrigado!

Me desculpe pela demora, já tinha iniciado porem não consegui termina-lo. Pretendo dar continuidade nessa próxima semana (25/08-02/09).

Abraços!

**Comment by sp4wna1** [comment]
Olá @orafaaraujo, consegui dar inicio ao Draft.
Aqui está: https://medium.com/@sp4wna1/introdu%C3%A7%C3%A3o-charles-proxy-para-interceptar-requests-e-responses-876f66399c70
Seria possivel abrirmos novamente essa issue?
