### ISSUE TITLE
Testes em Android: Test Driven Development com custom Views

### ISSUE THREAD

**Issue by soutoss** [androiddevbr/agenda-medium#96]
* **Autor:** Thiago Souto
* **Perfil no medium:** https://medium.com/@soutoss
* **Data escolhida:** 25/04/19
* **Título do artigo:** Testes em Android: Test Driven Development com custom Views
* **Descrição:** O objetivo deste post é falar um pouco sobre TDD e sobre algumas ferramentas que ajudaram no desenvolvimento da minha jornada com TDD, apresentando um exemplo com alguns testes escritos utilizando a nova biblioteca de testes da google que permite que o teste possa ser executado tanto na JVM quanto instrumentado utilizando essas ferramentas. As ferramentas que serão apresentadas são: Roboletric, Espresso, Android Test e mockk.

**Comment by soutoss** [comment]
Link para o rascunho: https://medium.com/p/24d08dccd11a/edit

**Comment by soutoss** [comment]
link para o rascunho: https://medium.com/p/24d08dccd11a

**Comment by soutoss** [comment]
Link atualizado: https://medium.com/@soutoss/testes-em-android-test-driven-development-com-activities-e-custom-views-24d08dccd11a

**Comment by davidtcdeveloper** [comment]
Estou fazendo a revisão aqui. Pra facilitar, poderia adicionar o post à nossa publicação?

**Comment by davidtcdeveloper** [comment]
Revisei o post aqui, o conteúdo está muito bom! Adicionei alguns comentários e sugestões, mas no geral o post está excelente!

**Comment by orafaaraujo** [comment]
Fala @soutoss 
Revisei o post e concordo com o @davidtcdeveloper que está excelente.
Coloquei poucos comentários pessoais nele, pode dar uma olhada?
Você retornando já pode submeter no nosso Medium, ta bom?

Abraços

**Comment by soutoss** [comment]
opa @orafaaraujo , tudo bem? Já fiz as alterações.

https://medium.com/@soutoss/testes-em-android-test-driven-development-com-activities-e-custom-views-24d08dccd11a?postPublishedType=repub

**Comment by orafaaraujo** [comment]
Pode publicar!
