### ISSUE TITLE
Dos livros pro software: Antifrágil

### ISSUE THREAD

**Issue by vitordealmeida** [androiddevbr/agenda-medium#97]
* **Autor:** Vítor Bruno de Almeida
* **Perfil no medium:** medium.com/@VitorDeAlmeida
* **Data escolhida:** ASAP
* **Título do artigo:** Dos livros pro software: Antifrágil
* **Descrição:** O artigo já está publicado: https://medium.com/@VitorDeAlmeida/dos-livros-pro-software-antifr%C3%A1gil-9ac6c68af4d8
Não se trata de Android em específico, mas em desenvolvimento de software num aspecto mais geral, e associado a momentos da carreira do desenvolvedor em que ele venha a assumir cargos de maior responsabilidade e liderança. A ideia do artigo é de traçar um paralelo entre as ideias discutidas no livro "Antifragile" e trazer essas ideias para a realidade do desenvolvimento de software. Caso queiram incluir no medium da comunidade, seria muito bom :)

**Comment by davidtcdeveloper** [comment]
Excelente texto @vitordealmeida. Nossa publicação tem sido bastante focada em posts específicos para Android. Por isso, vamos abrir uma discussão no canal #meta do slack para confirmar se a galera concorda em adicionar posts mais variados. Assim que tivermos uma conclusão a gente avança com este post :)

**Comment by vitordealmeida** [comment]
Obrigado pelo feedback, fico feliz se contribuir com algo :)

**Comment by davidtcdeveloper** [comment]
O feedback da galera foi bem positivo, vamos avançar com a inclusão na publicação :)
Você já é escritor da nossa publicação? O Medium está instável agora, não estou conseguindo conferir isso. Se você já for escritor, por favor adicione à publicação que nós fazemos uma nova revisão e logo publicamos.

**Comment by vitordealmeida** [comment]
Oi David, que bom!

Não sou, na verdade é o primeiro artigo que eu publiquei, vou precisar de
sua ajuda nos passos pra adicionar na publicação...

Quando melhorar a instabilidade fazemos isso (aqui também está problemático
o Medium)

**Comment by davidtcdeveloper** [comment]
Consegui te adicionar como escritor da publicação. Precisamos agora que você adicione o post para revisão. O menu do Medium não é muito intuitivo, aqui tem detalhes de como fazer: https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publication
Assim que você adicionar a gente revisa e adiciona notas privadas se for necessário.

**Comment by davidtcdeveloper** [comment]
Revisei o post já, tá excelente.
Faremos a publicação hoje ainda.

**Comment by davidtcdeveloper** [comment]
Post publicado! Em breve enviaremos o anúncio no slack.

**Comment by davidtcdeveloper** [comment]
Post publicado! Em breve enviaremos o anúncio no slack.

**Comment by vitordealmeida** [comment]
Que bom, fico muito feliz em contribuir! Parabéns pela agilidade!
