### ISSUE TITLE
Minha experiência no Google IO 2019

### ISSUE THREAD

**Issue by DiegoGSantos** [androiddevbr/agenda-medium#98]
* **Autor:** Diego Gonçalves Santos
* **Perfil no medium:** medium.com/@DiegoGSantos
* **Data escolhida:** Assim que possível, já que já está publicado
* **Título do artigo:** Minha experiência no Google IO 2019
* **Descrição:** Nesse artigo (https://medium.com/@diegogsantos/minha-experi%C3%AAncia-no-google-io-2019-3462a0b2a72a) eu conto um pouco de como foi minha experiência participando do Google IO e dou algumas dicas importantes pra quem pretende participar nas próximas edições do evento.

**Comment by davidtcdeveloper** [comment]
Você já é escritor da nossa publicação? O Medium está instável agora, não estou conseguindo conferir isso. Se você já for escritor, por favor adicione à publicação que nós fazemos uma nova revisão e logo publicamos.

**Comment by DiegoGSantos** [comment]
Opa sou sim! Acabei de submeter lá pra vocês

**Comment by DiegoGSantos** [comment]
Boa! Vou fazer as correções e te aviso

**Comment by DiegoGSantos** [comment]
Corrigido! ;)

**Comment by davidtcdeveloper** [comment]
Show, bem legais as correções. Estou alinhando com o pessoal para a gente publicar assim que possível.

**Comment by davidtcdeveloper** [comment]
Post publicado! Em breve enviaremos o anúncio no slack.

**Comment by DiegoGSantos** [comment]
Boa! Muito obrigado! ;)
