### ISSUE TITLE
Configurar o Jenkins para Android: Integração Contínua

### ISSUE THREAD

**Issue by victorlopesjg** [androiddevbr/agenda-medium#99]
* **Autor:** Victor Oliveira
* **Perfil no medium:** https://medium.com/@victorlopesjg
* **Data escolhida:** 11/06/19
* **Título do artigo:** Configurar o Jenkins para Android: Integração Contínua
* **Descrição:** Esse artigo tem como objetivo apresentar um guia prático de configuração do Jenkins com o Android. 

https://medium.com/@victorlopesjg/configurar-o-jenkins-para-android-integra%C3%A7%C3%A3o-cont%C3%ADnua-a2f8a18516f6

**Comment by orafaaraujo** [comment]
Olá, @victorlopesjg Parabéns pelo post, está bem legal.
Deixei alguns poucos comentarios, dá uma olhada que é coisa simples e logo iremos publica-lo :)

Abraços

**Comment by victorlopesjg** [comment]
Opa @orafaaraujo . Acabei de corrigir!
